#!/usr/bin/env python
########################################################################################################
# Name: ASC_PTB_SF_Table_Load.py
#
# Desc: ASC_PTB_SF_Table_Load.py will load PSPS_EXT_DATA with Extract data.
#
# Modified:
#
# Paul Baranoski 2025-07-11 Create SQL
# Paul Baranoski 2025-09-12 Add 'if __name__ == "__main__":' logic so that this module can be a python import module. 
# Paul Baranoski 2025-09-19 Changed back to be executed from shell script.
########################################################################################################


#############################################################
# Functions
#############################################################
#def executeSFSQL():
    
import os
import sys
import datetime
from datetime import datetime

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

# Use Timestamp generated by shell script so logs and output files will have timestamp
ENVNAME=os.getenv('ENVNAME')

EXT_SRVC_YR=os.getenv('EXT_SRVC_YR')
EXT_RUN_DT=os.getenv('EXT_RUN_DT')
EXT_FILENAME=os.getenv('EXT_FILENAME')

# boolean - Python Exception status
bPythonExceptionOccurred=False

     
########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Method to execute the extract SQL using Timestamp 
########################################################################################################
try:
   snowconvert_helpers.configure_log()
   con = snowconvert_helpers.log_on()   
   snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
   snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}""", con,exit_on_error = True)

   ## Delete records from TARGET TABLE ##
   snowconvert_helpers.execute_sql_statement(f"""DELETE FROM BIA_{ENVNAME}.CMS_EXTNL_XTR_{ENVNAME}.ASCPS_EXT_DATA
                                                 WHERE EXT_SRVC_YR = '{EXT_SRVC_YR}' 
                                                   AND EXT_RUN_DT  = TO_DATE('{EXT_RUN_DT}','YYYYMMDD')                                                     
                                              """, con,exit_on_error = True)
                                                        
   ## INSERT Extract FILE value into TO THE TARGET TABLE ##
   snowconvert_helpers.execute_sql_statement(f""" COPY INTO BIA_{ENVNAME}.CMS_EXTNL_XTR_{ENVNAME}.ASCPS_EXT_DATA
                                                          ( EXT_SRVC_YR, EXT_RUN_DT,
                                                            CLM_CNTRCTR_NUM, CLM_LINE_HCPCS_CD, HCPCS_1_MDFR_CD,
                                                            HCPCS_2_MDFR_CD, BENE_ZIP_CD, GEO_SSA_STATE_CD, GEO_SSA_CNTY_CD, 
                                                            CARR_PROV_ZIP, CLM_RNDRG_PRVDR_NPI_NUM, CLM_RNDRG_PRVDR_UPIN_NUM, CLM_FED_TYPE_SRVC_CD,
                                                            CLM_LINE_ALOWD_CHRG_AMT, CLM_LINE_CVRD_PD_AMT, CLM_LINE_PRFNL_MTUS_CNT )
                                                
                                                        FROM (SELECT '{EXT_SRVC_YR}'     AS EXT_SRVC_YR
                                                                    ,TO_DATE('{EXT_RUN_DT}','YYYYMMDD')  AS EXT_RUN_DT
                                                                    ,SUBSTR(f.$1,1,5)    AS CLM_CNTRCTR_NUM
                                                                    ,SUBSTR(f.$1,6,5)    AS CLM_LINE_HCPCS_CD
                                                                    ,SUBSTR(f.$1,11,2)   AS HCPCS_1_MDFR_CD
                                                                    ,SUBSTR(f.$1,13,2)   AS HCPCS_2_MDFR_CD
                                                                    ,SUBSTR(f.$1,15,9)   AS BENE_ZIP_CD
                                                                    ,SUBSTR(f.$1,24,2)   AS GEO_SSA_STATE_CD
                                                                    ,SUBSTR(f.$1,26,3)   AS GEO_SSA_CNTY_C
                                                                    ,SUBSTR(f.$1,29,9)   AS CARR_PROV_ZIP
                                                                    ,SUBSTR(f.$1,38,10)  AS CLM_RNDRG_PRVDR_NPI_NUM
                                                                    ,SUBSTR(f.$1,48,10)  AS CLM_RNDRG_PRVDR_UPIN_NUM
                                                                    ,SUBSTR(f.$1,58,1)   AS CLM_FED_TYPE_SRVC_CD
                                                                    ,SUBSTR(f.$1,59,22)  AS CLM_LINE_ALOWD_CHRG_AMT
                                                                    ,SUBSTR(f.$1,81,22)  AS CLM_LINE_CVRD_PD_AMT
                                                                    ,SUBSTR(f.$1,103,8)  AS CLM_LINE_PRFNL_MTUS_CNT
                                             
                                                                FROM @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_EFT_FILES_STG/{EXT_FILENAME}  f)
                                                                FILE_FORMAT = (TYPE=CSV  EMPTY_FIELD_AS_NULL=false ) FORCE=TRUE """, con,exit_on_error = True)
                    
    


   
   #**************************************
   # End Application
   #**************************************    
   snowconvert_helpers.quit_application()
   
except Exception as e:
   print(e)
   
   # Let shell script know that python code failed.
   bPythonExceptionOccurred=True   
   
finally:
   if con is not None:
      con.close()

   # Let shell script know that python code failed.      
   if bPythonExceptionOccurred == True:
      sys.exit(12) 
   else:   
      snowconvert_helpers.quit_application()


#if __name__ == "__main__":
    
#    executeSFSQL()