WITH BENE_INFO AS (

SELECT *
    FROM (
        SELECT BENE_SK, BENE_BRTH_DT, BENE_DEATH_DT, COALESCE(BENE_DEATH_DT,CURRENT_DATE) AS END_AGE_DT
        ,DATEDIFF(year, BENE_BRTH_DT, COALESCE(BENE_DEATH_DT,CURRENT_DATE)) AS AGE
        FROM IDRC_PRD.CMS_DIM_BENE_PRD.BENE BENE
        WHERE NOT BENE_BRTH_DT = TO_DATE('1000-01-01','YYYY-MM-DD')
    ) 

    WHERE AGE >= 120

)

--SELECT BENE.*, C.CLM_TYPE_CD, C.CLM_FROM_DT, C.CLM_THRU_DT
SELECT DISTINCT BENE.* 

FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C   

INNER JOIN BENE_INFO BENE
ON C.BENE_SK = BENE.BENE_SK

WHERE C.CLM_TYPE_CD IN (10,20,30,40,50,60,61,62,63,64)
--WHERE C.CLM_TYPE_CD IN (71,72,81,82)
--WHERE C.CLM_TYPE_CD IN (1,2,3,4)
AND C.CLM_FINL_ACTN_IND = 'Y'
AND C.CLM_FROM_DT BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') AND TO_DATE('2025-12-31','YYYY-MM-DD')
;
