
-- Version created 12/2/2025
CREATE OR REPLACE VIEW BIA_PRD.CMS_VDM_VIEW_PTB_PRD.V2_UTIL_EXT_CALENDAR (
SCHEDULED_DT, BEFORE_NEXT_SCHEDULED_DT, DOW, EXT_KEY, EXT_DESC, TIMEFRAME_IND, DOW_DOM,
	CAL_MONTHS, CAL_DAY, FINDER_FILE_REQ, FF_PRE_PROCESS,DELIVERY_METHOD,
	MF_DEPENDENCY,ETL_DEPENDENCY,SAS_DEPENDENCY, AUTOMATED
) 
AS 

WITH CALENDAR_ENTRIES AS (

    SELECT EXT_DT AS SCHEDULED_DT,
        (LEAD(EXT_DT) OVER (PARTITION BY EXT_KEY ORDER BY EXT_DT) - 1) AS BEFORE_NEXT_SCHEDULED_DT, 
        DOW, EXT_KEY, EXT_DESC,
    	TIMEFRAME_IND, 
        COALESCE(DOW_DOM,' ') AS DOW_DOM,
    	COALESCE(CAL_MONTHS,' ') AS CAL_MONTHS, COALESCE(CAL_DAY,' ') AS CAL_DAY,
    	COALESCE(FINDER_FILE_REQ,'N') AS FINDER_FILE_REQ,
    	COALESCE(FF_PRE_PROCESS,' ') AS FF_PRE_PROCESS,
    	DELIVERY_METHOD,
    	COALESCE(MF_DEPENDENCY,'N') AS MF_DEPENDENCY, COALESCE(ETL_DEPENDENCY,'N') AS ETL_DEPENDENCY,
        COALESCE(SAS_DEPENDENCY,'N') AS SAS_DEPENDENCY, COALESCE(AUTOMATED,'N') AS AUTOMATED
    
    FROM BIA_PRD.CMS_TARGET_XTR_PRD.UTIL_EXT_CALENDAR
)

,CALENDAR_POST_PROCESS AS (

    SELECT SCHEDULED_DT, COALESCE(BEFORE_NEXT_SCHEDULED_DT,'2099-12-31') AS BEFORE_NEXT_SCHEDULED_DT, 
         DOW, EXT_KEY, EXT_DESC, TIMEFRAME_IND, DOW_DOM,
    	CAL_MONTHS, CAL_DAY, FINDER_FILE_REQ, FF_PRE_PROCESS,DELIVERY_METHOD,
    	MF_DEPENDENCY,ETL_DEPENDENCY,SAS_DEPENDENCY, AUTOMATED
    FROM CALENDAR_ENTRIES
)

SELECT SCHEDULED_DT, GREATEST(BEFORE_NEXT_SCHEDULED_DT,SCHEDULED_DT) AS BEFORE_NEXT_SCHEDULED_DT, 
     DOW, EXT_KEY, EXT_DESC, TIMEFRAME_IND, DOW_DOM,
    CAL_MONTHS, CAL_DAY, FINDER_FILE_REQ, FF_PRE_PROCESS,DELIVERY_METHOD,
    MF_DEPENDENCY,ETL_DEPENDENCY,SAS_DEPENDENCY, AUTOMATED
FROM CALENDAR_POST_PROCESS
    
ORDER BY EXT_KEY, SCHEDULED_DT
;

--********************************************************************************
-- Updated SQL to use. Make same mods to other SQL
--********************************************************************************

--*** Year Report
select	a19.EXT_KEY  EXT_KEY,
	a19.EXT_DESC  EXT_DESC,
	a19.SCHEDULED_DT  SCHEDULED_DT, 
	--****\/***** Optional
	BEFORE_NEXT_SCHEDULED_DT,
	--****/\***** 
	a19.RUN_DT  RUN_DT,
	Year(a19.SCHEDULED_DT)  SCHEDULED_YR,
	a19.FINDER_FILE_REQ  FINDER_FILE_REQ,
	a19.SUCCESS_IND  SUCCESS_IND,
	a19.TIMEFRAME_IND  TIMEFRAME_IND,
	a19.STATUS  STATUS
from	(SELECT  
CAL.EXT_KEY, 
CAL.EXT_DESC, 
CAL.SCHEDULED_DT, 
CAL.BEFORE_NEXT_SCHEDULED_DT,
CAL.TIMEFRAME_IND, 
CAL.FINDER_FILE_REQ,
CAL.AUTOMATED,
EXT.RUN_DT, 
EXT.SUCCESS_IND,
(
CASE 
  WHEN EXT.SUCCESS_IND = 'Y' THEN 'Successful Execution' 
  WHEN (coalesce(EXT.SUCCESS_IND,'N') <> 'Y' AND (CAL.SCHEDULED_DT < CURRENT_DATE) AND CAL.FINDER_FILE_REQ = 'Y') THEN 'Potential Issue'  
  WHEN (coalesce(EXT.SUCCESS_IND,'N') <> 'Y' AND (CAL.SCHEDULED_DT < CURRENT_DATE) AND CAL.FINDER_FILE_REQ = 'N') THEN 'Did Not Execute'  
  WHEN ((CAL.SCHEDULED_DT >= CURRENT_DATE)) THEN 'Still to Run' ELSE 'Others' END 
) AS STATUS
FROM BIA_PRD.CMS_VDM_VIEW_PTB_PRD.V2_UTIL_EXT_CALENDAR CAL
LEFT OUTER JOIN BIA_PRD.CMS_VDM_VIEW_PTB_PRD.V2_UTIL_EXT_RUN_INFO EXT
ON CAL.EXT_KEY = EXT.EXT_KEY
--****\/***** Required
--AND EXT.RUN_DT >= CAL.SCHEDULED_DT
--AND CAL.SCHEDULED_DT >= EXT.RUN_DT  
AND EXT.RUN_DT BETWEEN CAL.SCHEDULED_DT AND CAL.BEFORE_NEXT_SCHEDULED_DT
--****/\*****


)	a19
where	a19.SCHEDULED_DT between DATE_TRUNC('YEAR', CURRENT_DATE()) and LAST_DAY(CURRENT_DATE(),'YEAR')
--AND EXT_KEY like  'HOS%'
group by	a19.EXT_KEY,
	a19.EXT_DESC,
	a19.SCHEDULED_DT,
	--****\/***** THis is optional
    a19.BEFORE_NEXT_SCHEDULED_DT,
	--****/\*****
	a19.RUN_DT,
	Year(a19.SCHEDULED_DT),
	a19.FINDER_FILE_REQ,
	a19.SUCCESS_IND,
	a19.TIMEFRAME_IND,
	a19.STATUS
ORDER BY a19.EXT_KEY, a19.SCHEDULED_DT, a19.BEFORE_NEXT_SCHEDULED_DT, a19.RUN_DT    
;

