WITH DETAIL_INFO AS (

    SELECT EXT_NAME,YYYY_MM AS TIME_PERIOD, COUNT(EXT_FILENAME) AS NOF_EXT_FILES, SUM(REC_COUNT) AS REC_CNT, SUM(BYTE_COUNT) AS BYTE_CNT
    FROM (
        SELECT UPPER(EXT_NAME) AS EXT_NAME 
              ,TO_CHAR(RUN_TMSTMP,'YYYY-MM') AS YYYY_MM
              ,EXT_FILENAME
              ,REC_COUNT
              ,BYTE_COUNT
        FROM BIA_PRD.CMS_TARGET_XTR_PRD.UTIL_EXT_RUN_EXT_FILES
        WHERE TO_DATE(RUN_TMSTMP) BETWEEN TO_DATE('2026-04-01','YYYY-MM-DD')  
          AND TO_DATE('2026-05-15','YYYY-MM-DD')

    )
    GROUP BY EXT_NAME, TIME_PERIOD
    
)

,RECURRING_EXTS AS (

   SELECT 'Recurring Extracts' AS LINE_DESC, '1' as ORDER_SEQ, BYTE_CNT, NOF_FILES, REC_CNT   
   FROM (
       SELECT SUM(NOF_EXT_FILES) AS NOF_FILES, SUM(REC_CNT) AS REC_CNT, SUM(BYTE_CNT) AS BYTE_CNT
        FROM DETAIL_INFO 
	   WHERE NOT (EXT_NAME Like 'DOJ_%' OR EXT_NAME Like 'FOIA_%' OR EXT_NAME = 'DSH') 
   ) 
)

,ADHOCS_EXTS AS (

   SELECT 'Adhocs' AS LINE_DESC, '2' as ORDER_SEQ, BYTE_CNT, NOF_FILES, REC_CNT   
   FROM (
       SELECT SUM(NOF_EXT_FILES) AS NOF_FILES, SUM(REC_CNT) AS REC_CNT, SUM(BYTE_CNT) AS BYTE_CNT
        FROM DETAIL_INFO 
	   WHERE (EXT_NAME Like 'DOJ_%' OR EXT_NAME Like 'FOIA_%') 
   ) 
)

,DSH_EXTS AS (

   SELECT 'DSH' AS LINE_DESC, '3' as ORDER_SEQ, BYTE_CNT, NOF_FILES, REC_CNT   
   FROM (
       SELECT SUM(NOF_EXT_FILES) AS NOF_FILES, SUM(REC_CNT) AS REC_CNT, SUM(BYTE_CNT) AS BYTE_CNT
        FROM DETAIL_INFO 
	   WHERE EXT_NAME = 'DSH'
   ) 
)

,GRAND_TOTAL AS (

   SELECT 'Grand Total' AS LINE_DESC, '4' as ORDER_SEQ, BYTE_CNT, NOF_FILES, REC_CNT   
   FROM (
       SELECT SUM(NOF_EXT_FILES) AS NOF_FILES, SUM(REC_CNT) AS REC_CNT, SUM(BYTE_CNT) AS BYTE_CNT
        FROM DETAIL_INFO 
   ) 
)


SELECT LINE_DESC AS "Request Type"

	  ,CASE WHEN BYTE_CNT > 1000000000000 
		 THEN (TO_CHAR( (BYTE_CNT / 1000000000000), '9,999,999.00') || ' TB') 
		 ELSE  (TO_CHAR( (BYTE_CNT / 1000000000), '9,999.00') || ' GB') 
		 END AS "Data Size"
	 
	,TO_CHAR(NOF_FILES,'999,999,999') AS "Number of Files", TO_CHAR(REC_CNT,'999,999,999,999') AS "Number of Records"   
	
FROM (        
	SELECT * FROM RECURRING_EXTS  UNION 
	SELECT * FROM ADHOCS_EXTS     UNION 
	SELECT * FROM DSH_EXTS        UNION 
	SELECT * FROM GRAND_TOTAL 

   )
ORDER BY ORDER_SEQ
;