WITH CLM_INFO_BY_DT AS ( 

    SELECT 
       (C.GEO_BENE_SK || C.CLM_DT_SGNTR_SK || C.CLM_TYPE_CD || C.CLM_NUM_SK) AS CLM_KEY    
      ,C.CLM_TOT_LINE_CNT
      ,CDS.CLM_NCH_WKLY_PROC_DT
      ,C.CLM_THRU_DT
      ,C.CLM_FROM_DT
      
    FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) C    
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) CDS
    ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK
    
    INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
    ON C.BENE_SK = B.BENE_SK
    
    WHERE C.CLM_TYPE_CD IN ('40')
    AND C.CLM_FINL_ACTN_IND = 'Y'
	-- 2024-01-05 (first Friday of prior year);   2024-03-28 (last Friday of Qtr)
    AND CDS.CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2024-01-05','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
	AND YEAR(C.CLM_THRU_DT) in ('2024','2025')
	
)

,QTR_COUNTS AS (
    SELECT 'Q'
          ,COUNT(DISTINCT CLM_KEY) AS NOF_CLAIMS
          ,SUM(CLM_TOT_LINE_CNT) as TOT_LINE_CNT
    FROM CLM_INFO_BY_DT
    WHERE CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2025-01-01','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
      AND YEAR(CLM_THRU_DT) = '2025'

)

,YRLY_COUNTS AS (

    SELECT 'Y'
          ,COUNT(DISTINCT CLM_KEY) AS NOF_CLAIMS
          ,SUM(CLM_TOT_LINE_CNT)   AS TOT_LINE_CNT
    FROM CLM_INFO_BY_DT
	-- 2024-01-05 (first Friday of prior year);   2024-03-28 (last Friday of Qtr)
    WHERE CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2024-01-05','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
      AND year (CLM_THRU_DT) = '2024' 
      
)

SELECT * FROM QTR_COUNTS UNION ALL
SELECT * FROM YRLY_COUNTS 

;
