
WITH CLM_INFO AS (

    SELECT C.*
        -- What should the default date be in the results-set if its null in database
		,CASE WHEN CDS.CLM_FROM_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_FROM_DT,'YYYYMMDD') END AS CDS_CLM_FROM_DT
		,CASE WHEN CDS.CLM_THRU_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_THRU_DT,'YYYYMMDD') END AS CDS_CLM_THRU_DT
		
		,CASE WHEN CDS.CLM_NCH_WKLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_WKLY_PROC_DT,'YYYYMMDD') END AS CDS_CLM_NCH_WKLY_PROC_DT
		,CASE WHEN CDS.CLM_CWF_ACRTN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CWF_ACRTN_DT,'YYYYMMDD') END         AS CDS_CLM_CWF_ACRTN_DT
		
		,CASE WHEN CDS.CLM_NCH_DLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_DLY_PROC_DT,'YYYYMMDD') END   AS CDS_CLM_NCH_DLY_PROC_DT
		,CASE WHEN CDS.CLM_SUBMSN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SUBMSN_DT,'YYYYMMDD') END               AS CDS_CLM_SUBMSN_DT
		
		,CASE WHEN CDS.CLM_SCHLD_PMT_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SCHLD_PMT_DT,'YYYYMMDD') END           AS CDS_CLM_SCHLD_PMT_DT
		,CASE WHEN CDS.CLM_TRNSMSN_TO_CMS_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_TRNSMSN_TO_CMS_DT,'YYYYMMDD') END AS CDS_CLM_TRNSMSN_TO_CMS_DT

		,CASE WHEN CDS.CLM_CMS_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CMS_PROC_DT,'YYYYMMDD') END AS CDS_CLM_CMS_PROC_DT
		,CASE WHEN CDS.CLM_PRO_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_PRO_PROC_DT,'YYYYMMDD') END AS CDS_CLM_PRO_PROC_DT

	
    FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) C    
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) CDS
    ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK

    INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
    ON C.BENE_SK = B.BENE_SK
    
    WHERE C.CLM_TYPE_CD IN ('40')
      AND C.CLM_FINL_ACTN_IND = 'Y'
      -- 2024-01-05 (first Friday of prior year);   2024-03-28 (last Friday of Qtr)
      AND CDS.CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2025-01-01','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
      AND YEAR(C.CLM_THRU_DT) = '2025'
	  
)

-- P_MAX=2 R_MAX=3 D_MAX=49 E_MAX=12 S_MAX=25 1_MAX=1
/*
,CLM_P_DGNS_INFO  AS (

    SELECT 
         GEO_BENE_SK
        ,CLM_DT_SGNTR_SK
        ,CLM_TYPE_CD
        ,CLM_NUM_SK
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_P_DGNS_PRCDR_ICD_IND_1
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_P_DGNS_PRCDR_ICD_IND_2
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_P_DGNS_PRCDR_ICD_IND_3
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_P_DGNS_PRCDR_ICD_IND_4
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_P_DGNS_PRCDR_ICD_IND_5
        
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_1
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_2
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_3
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_4
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_5
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_P_DGNS_CD_6    

		
	FROM ( 	
			SELECT  
				 C.GEO_BENE_SK
				,C.CLM_DT_SGNTR_SK
				,C.CLM_TYPE_CD
				,C.CLM_NUM_SK
				
				,CASE WHEN PROD.CLM_DGNS_PRCDR_ICD_IND = '~' THEN NULL ELSE PROD.CLM_DGNS_PRCDR_ICD_IND END AS CLM_DGNS_PRCDR_ICD_IND 
				,CASE WHEN PROD.CLM_DGNS_CD = '~'            THEN NULL ELSE PROD.CLM_DGNS_CD END            AS CLM_DGNS_CD 
				,PROD.CLM_PRCDR_PRFRM_DT
				,PROD.CLM_VAL_SQNC_NUM	

			FROM CLM_INFO C 
			
			INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD PROD
			ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
			AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
			AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
			AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK
			AND PROD.CLM_PROD_TYPE_CD = 'P'
	)		

	GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK
        
)
*/
,CLM_OCRNC_SGNTR_MBR_INFO AS (

-- MAX CLM_OCRNC_SGNTR_SQNC_NUM IN DB = 18

    SELECT 
         CLM_OCRNC_SGNTR_SK
	
		-- SPAN_CD
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_1
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_2
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_3
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_4
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_5
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_6
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_7
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_8
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_9
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_10

        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 11 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_11
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 12 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_12
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 13 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_13
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 14 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_14
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 15 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_15
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 16 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_16
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 17 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_17
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 18 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_18
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 19 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_19
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 20 THEN CLM_OCRNC_SPAN_CD ELSE NULL END)  AS  CLM_OCRNC_SPAN_CD_20

 
		-- SPAN_FROM_DT
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_1
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_2
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_3
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_4
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_5
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_6
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_7
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_8
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_9
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_10

        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 11 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_11
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 12 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_12
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 13 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_13
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 14 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_14
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 15 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_15
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 16 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_16
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 17 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_17
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 18 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_18
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 19 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_19
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 20 THEN CLM_OCRNC_SPAN_FROM_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_FROM_DT_20


		-- SPAN_TO_DT
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_1
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_2
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_3
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_4
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_5
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_6
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_7
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_8
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_9
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_10

        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 11 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_11
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 12 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_12
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 13 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_13
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 14 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_14
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 15 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_15
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 16 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_16
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 17 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_17
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 18 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_18
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 19 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_19
        ,MAX(CASE WHEN CLM_OCRNC_SGNTR_SQNC_NUM = 20 THEN CLM_OCRNC_SPAN_THRU_DT ELSE NULL END)  AS  CLM_OCRNC_SPAN_THRU_DT_20

 
    FROM (

			SELECT
                 C.CLM_OCRNC_SGNTR_SK
                ,COSM.CLM_OCRNC_SGNTR_SQNC_NUM
				,COSM.CLM_OCRNC_SPAN_CD      AS CLM_OCRNC_SPAN_CD
				,TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD')  AS CLM_OCRNC_SPAN_FROM_DT
				,TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD')  AS CLM_OCRNC_SPAN_THRU_DT

			FROM CLM_INFO C 

			LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR_MBR COSM
	        ON C.CLM_OCRNC_SGNTR_SK = COSM.CLM_OCRNC_SGNTR_SK
	)
	
    GROUP BY CLM_OCRNC_SGNTR_SK
	
)	
	
,CLM_RLT_COND_SGNTR_MBR_INFO AS (

    SELECT 
         CLM_RLT_COND_SGNTR_SK
	
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 1  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_1
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 2  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_2
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 3  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_3
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 4  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_4
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 5  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_5
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 6  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_6
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 7  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_7
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 8  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_8
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 9  THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_9
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 10 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_10

        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 11 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_11
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 12 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_12
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 13 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_13
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 14 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_14
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 15 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_15
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 16 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_16
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 17 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_17
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 18 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_18
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 19 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_19
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 20 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_20

        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 21 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_21
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 22 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_22
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 23 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_23
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 24 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_24
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 25 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_25
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 26 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_26
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 27 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_27
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 28 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_28
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 29 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_29
        ,MAX(CASE WHEN CLM_RLT_COND_SGNTR_SQNC_NUM = 30 THEN CLM_RLT_COND_CD ELSE NULL END)  AS  CLM_RLT_COND_CD_30		
   
    FROM (

			SELECT
                 C.CLM_RLT_COND_SGNTR_SK, CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM	
				,CRCSM.CLM_RLT_COND_CD   

			FROM CLM_INFO C 

			LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_COND_SGNTR_MBR CRCSM
	        ON CRCSM.CLM_RLT_COND_SGNTR_SK  = C.CLM_RLT_COND_SGNTR_SK
	)
	
    GROUP BY CLM_RLT_COND_SGNTR_SK
	
)

,CLM_RLT_OCRNC_SGNTR_MBR_INFO AS (

    SELECT 
         CLM_RLT_OCRNC_SGNTR_SK
		
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 1  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_1
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 2  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_2
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 3  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_3
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 4  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_4
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 5  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_5
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 6  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_6
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 7  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_7
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 8  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_8
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 9  THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_9
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 10 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_10

        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 11 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_11
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 12 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_12
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 13 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_13
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 14 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_14
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 15 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_15
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 16 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_16
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 17 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_17
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 18 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_18
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 19 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_19
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 20 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_20

        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 21 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_31
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 22 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_32
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 23 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_33
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 24 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_34
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 25 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_35
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 26 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_36
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 27 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_37
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 28 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_38
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 29 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_39
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 30 THEN CLM_RLT_OCRNC_CD ELSE NULL END)  AS  CLM_RLT_OCRNC_CD_30
		
		
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 1  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_1
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 2  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_2
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 3  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_3
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 4  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_4
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 5  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_5
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 6  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_6
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 7  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_7
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 8  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_8
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 9  THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_9
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 10 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_10

        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 11 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_11
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 12 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_12
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 13 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_13
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 14 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_14
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 15 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_15
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 16 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_16
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 17 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_17
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 18 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_18
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 19 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_19
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 20 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_20

        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 21 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_31
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 22 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_32
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 23 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_33
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 24 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_34
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 25 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_35
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 26 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_36
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 27 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_37
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 28 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_38
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 29 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_39
        ,MAX(CASE WHEN CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 30 THEN CLM_RLT_OCRNC_DT ELSE NULL END)  AS  CLM_RLT_OCRNC_DT_30
   
    FROM (

			SELECT
                 C.CLM_RLT_OCRNC_SGNTR_SK, CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM	
				,REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ')      AS CLM_RLT_OCRNC_CD
				,TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD')   AS CLM_RLT_OCRNC_DT

			FROM CLM_INFO C 

			LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR_MBR CROSM
	        ON  C.CLM_RLT_OCRNC_SGNTR_SK  =  CROSM.CLM_RLT_OCRNC_SGNTR_SK
	)
	
    GROUP BY CLM_RLT_OCRNC_SGNTR_SK
	
)

,CLM_VAL_INFO AS (

    SELECT 
         GEO_BENE_SK
        ,CLM_DT_SGNTR_SK
        ,CLM_TYPE_CD
        ,CLM_NUM_SK
		
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_1
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_2
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_3
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_4
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_5
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_6
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_7
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_8
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_9
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_10
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_11
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_12
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 13 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_13
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 14 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_14
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 15 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_15
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 16 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_16
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 17 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_17
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 18 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_18
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 19 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_19
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 20 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_20		
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 21 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_21
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 22 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_22
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 23 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_23
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 24 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_24
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 25 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_25
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 26 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_26
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 27 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_27
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 28 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_28
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 29 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_29
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 30 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_30		
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 31 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_31
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 32 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_32
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 33 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_33
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 34 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_34
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 35 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_35
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 36 THEN CLM_VAL_CD ELSE NULL END)  AS  CLM_VAL_CD_36

        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_1
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_2
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_3
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_4
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_5
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_6
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_7
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_8
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_9
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_10
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_11
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_12
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 13 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_13
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 14 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_14
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 15 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_15
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 16 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_16
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 17 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_17
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 18 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_18
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 19 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_19
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 20 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_20
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 21 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_21
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 22 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_22
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 23 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_23
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 24 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_24
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 25 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_25
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 26 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_26
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 27 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_27
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 28 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_28
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 29 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_29		
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 30 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_30
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 31 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_31
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 32 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_32
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 33 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_33
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 34 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_34
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 35 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_35
        ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 36 THEN CLM_VAL_AMT ELSE NULL END) AS CLM_VAL_AMT_36
   
    FROM (
	
			SELECT
				 C.GEO_BENE_SK
				,C.CLM_DT_SGNTR_SK
				,C.CLM_TYPE_CD
				,C.CLM_NUM_SK	
				,VAL.CLM_VAL_SQNC_NUM
				,VAL.CLM_VAL_CD
				,VAL.CLM_VAL_AMT 
			FROM CLM_INFO C 
			LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_VAL VAL
			ON  C.GEO_BENE_SK        = VAL.GEO_BENE_SK
			AND C.CLM_DT_SGNTR_SK    = VAL.CLM_DT_SGNTR_SK
			AND C.CLM_TYPE_CD        = VAL.CLM_TYPE_CD
			AND C.CLM_NUM_SK         = VAL.CLM_NUM_SK
	)
	
    GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK
	
)


    SELECT 
    --COUNT(*)
    

		 TO_CHAR(COALESCE(COSG.CLM_OCRNC_SGNTR_MBR_CNT,0),'FM00')     AS CLM_OCRNC_SGNTR_MBR_CNT 
		,TO_CHAR(COALESCE(CROS.CLM_RLT_OCRNC_SGNTR_MBR_CNT,0),'FM00') AS CLM_RLT_OCRNC_SGNTR_MBR_CNT 
		,C.CLM_TYPE_CD
		,RPAD(COALESCE(SUBSTR(TRIM(C.CLM_HIC_NUM),1,12),''),12,' ')   AS BENE_HICN
		,RPAD(C.BENE_CTGRY_EQTBL_BIC_CD,2,' ')                        AS BENE_CTGRY_EQTBL_BIC_CD

		,RPAD(REPLACE(COALESCE(GST.GEO_SSA_STATE_CD,''),'~',''),2,' ')  AS SSA_STATE_CD
		,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')             AS CLM_FROM_DT
		,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')             AS CLM_THRU_DT

		,RPAD(C.CLM_CNTL_NUM,40,' ')                   AS CLAIM_CONTROL_NBR
		,RPAD(COALESCE(C.CLM_ORIG_CNTL_NUM,''),40,' ') AS ORIG_CLAIM_CONTROL_NBR
		,RPAD(C.CLM_QUERY_CD,1,' ')                    AS CLM_QUERY_CD

		,RPAD(COALESCE(C.CLM_BLG_PRVDR_OSCAR_NUM,' '),6,' ')       AS  CLM_BLG_PRVDR_OSCAR_NUM 
		,RPAD(COALESCE(C.CLM_BLG_PRVDR_OSCAR_STATE_CD,' '),2,' ')  AS  CLM_BLG_PRVDR_OSCAR_STATE_CD 
		,RPAD(COALESCE(C.CLM_BLG_PRVDR_OSCAR_FAC_CD,' '),3,' ')    AS  CLM_BLG_PRVDR_OSCAR_FAC_CD
		,RPAD(COALESCE(C.CLM_BLG_PRVDR_OSCAR_EMER_IND,' '),1,' ')  AS  CLM_BLG_PRVDR_OSCAR_EMER_IND

		,TO_CHAR(COALESCE(CLM_TOT_LINE_CNT,0),'FM999')   AS  CLM_TOT_LINE_CNT

		,RPAD(C.CLM_BILL_FAC_TYPE_CD,1,' ') AS CLM_BILL_FAC_TYPE_CD
		,RPAD(C.CLM_BILL_CLSFCTN_CD,1,' ')  AS CLM_BILL_CLSFCTN_CD
		,RPAD(C.CLM_BILL_FREQ_CD,1,' ')     AS CLM_BILL_FREQ_CD
		,C.CLM_DISP_CD
		,RPAD(C.GEO_BENE_SSA_CNTY_CD,3,' ') AS GEO_BENE_SSA_CNTY_CD

		,CASE WHEN C.CLM_PD_DT IS NULL  THEN '00000000' ELSE TO_CHAR(C.CLM_PD_DT,'YYYYMMDD') END

		,RPAD(COALESCE(C.CLM_CNTRCTR_NUM,' '),5,' ')   AS CLM_CNTRCTR_NUM 

		,TO_CHAR(C.GEO_BENE_SK,'FM0000000000')        AS GEO_BENE_SK
		
		,RPAD(REPLACE(COALESCE(C.BENE_SEX_CD,''),'~',''),1,' ')            AS BENE_SEX_CD
		,RPAD(COALESCE(TO_CHAR(C.CLM_PTNT_BIRTH_DT, 'YYYYMMDD'),''),8,' ') AS BENE_DOB
		-- S9(13).99
		,TO_CHAR(C.CLM_PMT_AMT,'S0000000000000.00')  AS CLM_PMT_AMT
		,RPAD(C.CLM_NCH_PRMRY_PYR_CD,1,' ')          AS CLM_NCH_PRMRY_PYR_CD
		
		,RPAD(C.GEO_BLG_SSA_STATE_CD,2,' ')          AS GEO_BLG_SSA_STATE_CD   
		,COALESCE(C.GEO_FAC_SSA_STATE_CD,'  ')       AS GEO_FAC_SSA_STATE_CD

		,RPAD(C.PRVDR_BLG_PRVDR_NPI_NUM,10,' ')      AS PRVDR_BLG_PRVDR_NPI_NUM
		,RPAD(C.CLM_BLG_PRVDR_NPI_NUM,10,' ')        AS CLM_BLG_PRVDR_NPI_NUM

		,RPAD(C.CLM_ATNDG_PRVDR_UPIN_NUM,6,' ')      AS CLM_ATNDG_PRVDR_UPIN_NUM
		,RPAD(C.PRVDR_ATNDG_PRVDR_NPI_NUM,10,' ')    AS PRVDR_ATNDG_PRVDR_NPI_NUM
		,RPAD(C.CLM_ATNDG_PRVDR_NPI_NUM,10,' ')      AS CLM_ATNDG_PRVDR_NPI_NUM

		,RPAD(COALESCE(C.CLM_ATNDG_PRVDR_NAME,' '),120,' ')  AS  CLM_ATNDG_PRVDR_NAME
		
		,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_LAST_NAME = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_ATNDG_PRVDR_LAST_NAME
		,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_ATNDG_PRVDR_1ST_NAME
		,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_ATNDG_PRVDR_MDL_NAME

		,RPAD(C.CLM_OPRTG_PRVDR_UPIN_NUM,6,' ')            AS CLM_OPRTG_PRVDR_UPIN_NUM
		,RPAD(CASE WHEN C.PRVDR_OPRTG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_OPRTG_PRVDR_NPI_NUM END,10,' ') AS PRVDR_OPRTG_PRVDR_NPI_NUM
		,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_NPI_NUM = '~'   THEN ' ' ELSE C.CLM_OPRTG_PRVDR_NPI_NUM END,10,' ')   AS CLM_OPRTG_PRVDR_NPI_NUM

		,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_NAME  = '~'      THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_NAME,' ') END,120,' ')  AS  CLM_OPRTG_PRVDR_NAME
		,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_LAST_NAME  = '~' THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_OPRTG_PRVDR_LAST_NAME
		,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_OPRTG_PRVDR_1ST_NAME
		,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_OPRTG_PRVDR_MDL_NAME

		,RPAD(C.CLM_OTHR_PRVDR_UPIN_NUM,6,' ')            AS CLM_OTHR_PRVDR_UPIN_NUM
		,RPAD(CASE WHEN C.PRVDR_OTHR_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_OTHR_PRVDR_NPI_NUM END,10,' ') AS PRVDR_OTHR_PRVDR_NPI_NUM
		,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_NPI_NUM = '~'   THEN ' ' ELSE C.CLM_OTHR_PRVDR_NPI_NUM END,10,' ')   AS CLM_OTHR_PRVDR_NPI_NUM

		,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_NAME      = '~'  THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_NAME,' ') END,120,' ')  AS  CLM_OTHR_PRVDR_NAME
		,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_LAST_NAME = '~'  THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_OTHR_PRVDR_LAST_NAME
		,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_OTHR_PRVDR_1ST_NAME
		,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_OTHR_PRVDR_MDL_NAME

		-- S9(13).99
		,TO_CHAR(COALESCE(C.CLM_SBMT_CHRG_AMT,0),'S0000000000000.00')       AS CLM_SBMT_CHRG_AMT
		
		,RPAD(REPLACE(COALESCE(C.CLM_RAC_ADJSTMT_IND_CD,''),'~',''),1,' ') AS CLM_RAC_ADJSTMT_IND_CD

	    ,TO_CHAR(GEO_BLG_SK,'FM999999999999999999')  AS GEO_BLK_SK
		
		,RPAD(TO_CHAR(C.CLM_BLG_PRVDR_ZIP5_CD),5) AS ZIP5_CD
		,RPAD(REPLACE(COALESCE(C.CLM_BLG_PRVDR_ZIP4_CD,' '),'~',' '),4,' ') AS CLM_BLG_PRVDR_ZIP4_CD
		,RPAD(C.CLM_DCMTN_CD,2,' ')               AS CLM_DCMTN_CD

		,RPAD(C.CLM_RNDRG_PRVDR_UPIN_NUM,6,' ')            AS CLM_RNDRG_PRVDR_UPIN_NUM
		,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_NPI_NUM = '~'   THEN ' ' ELSE C.CLM_RNDRG_PRVDR_NPI_NUM END,10,' ')   AS CLM_RNDRG_PRVDR_NPI_NUM
	    ,RPAD(CASE WHEN C.PRVDR_RNDRNG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_RNDRNG_PRVDR_NPI_NUM END,10,' ') AS PRVDR_RNDRNG_PRVDR_NPI_NUM

		,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_NAME  = '~'      THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_NAME,' ') END,120,' ')  AS  CLM_RNDRG_PRVDR_NAME
		,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_LAST_NAME  = '~' THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_RNDRG_PRVDR_LAST_NAME
		,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_RNDRG_PRVDR_1ST_NAME
		,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_RNDRG_PRVDR_MDL_NAME

		,RPAD(C.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,2,' ')   AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD
		,RPAD(C.CLM_FPS_MODEL_NUM,2,' ')               AS CLM_FPS_MODEL_NUM
		,RPAD(C.CLM_FPS_MSN_1_CD,5,' ')                AS CLM_FPS_MSN_1_CD
		,RPAD(C.CLM_FPS_MSN_2_CD,5,' ')                AS CLM_FPS_MSN_2_CD
		
		-- S9(9).99
		,TO_CHAR(COALESCE(C.CLM_BLOOD_LBLTY_AMT,0),'S000000000.00')          AS CLM_BLOOD_LBLTY_AMT
		-- S9(13).99
		,TO_CHAR(COALESCE(C.CLM_MDCR_DDCTBL_AMT,0),'S0000000000000.00')    AS CLM_MDCR_DDCTBL_AMT	
		-- S9(13).99
		,TO_CHAR(COALESCE(C.CLM_MDCR_COINSRNC_AMT,0),'S0000000000000.00')  AS CLM_MDCR_COINSRNC_AMT	
		-- S9(09).99
		,TO_CHAR(COALESCE(C.CLM_PRVDR_PMT_AMT,0),'S000000000.00')          AS  CLM_PRVDR_PMT_AMT
		
		,TO_CHAR(COALESCE(C.CLM_BLOOD_PT_FRNSH_QTY,0),'FM000')               AS  CLM_BLOOD_PT_FRNSH_QTY
		,TO_CHAR(COALESCE(C.CLM_BLOOD_PT_RPLC_QTY,0),'FM000')                AS  CLM_BLOOD_PT_RPLC_QTY
		,TO_CHAR(COALESCE(C.CLM_BLOOD_PT_NRPLC_QTY,0),'FM000')               AS  CLM_BLOOD_PT_NRPLC_QTY

		,TO_CHAR(COALESCE(C.CLM_PTA_BLOOD_DDCTBL_QTY,0),'FM000')             AS  CLM_PTA_BLOOD_DDCTBL_QTY

		,RPAD(CASE WHEN C.CLM_ATNDG_FED_PRVDR_SPCLTY_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_ATNDG_FED_PRVDR_SPCLTY_CD,' ') END,2,' ') AS CLM_ATNDG_FED_PRVDR_SPCLTY_CD
		,RPAD(CASE WHEN C.CLM_OPRTG_FED_PRVDR_SPCLTY_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_OPRTG_FED_PRVDR_SPCLTY_CD,' ') END,2,' ') AS CLM_OPRTG_FED_PRVDR_SPCLTY_CD
		,RPAD(CASE WHEN C.CLM_OTHR_FED_PRVDR_SPCLTY_CD  = '~' THEN ' ' ELSE COALESCE(C.CLM_OTHR_FED_PRVDR_SPCLTY_CD,' ') END,2,' ')  AS CLM_OTHR_FED_PRVDR_SPCLTY_CD

		,RPAD(REPLACE(COALESCE(C.CLM_RFRG_PRVDR_UPIN_NUM,''),'~',''),6,' ')     AS CLM_RFRG_PRVDR_UPIN_NUM
		,RPAD(REPLACE(COALESCE(C.CLM_RFRG_PRVDR_NPI_NUM,''),'~',''),10,' ')     AS CLM_RFRG_PRVDR_NPI_NUM
		,RPAD(REPLACE(COALESCE(C.PRVDR_RFRG_PRVDR_NPI_NUM,''),'~',''),10,' ')   AS PRVDR_RFRG_PRVDR_NPI_NUM

		,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_NAME      = '~'  THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_NAME,' ') END,120,' ')  AS  CLM_RFRG_PRVDR_NAME
		,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_LAST_NAME = '~'  THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_RFRG_PRVDR_LAST_NAME
		,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_RFRG_PRVDR_1ST_NAME
		,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_RFRG_PRVDR_MDL_NAME

		,RPAD(COALESCE(C.CLM_RFRG_FED_PRVDR_SPCLTY_CD,' '),2,' ')  AS CLM_RFRG_FED_PRVDR_SPCLTY_CD
		,RPAD(COALESCE(C.CLM_SRVC_PRVDR_NPI_NUM,' '),10)           AS CLM_SRVC_PRVDR_NPI_NUM
		,RPAD(CASE WHEN C.PRVDR_SRVC_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(C.PRVDR_SRVC_PRVDR_NPI_NUM,' ') END,10,' ')  AS PRVDR_SRVC_PRVDR_NPI_NUM
	  
	    ,TO_CHAR(COALESCE(C.CLM_SRVC_UNIT_QTY,0),'FM9999999999.9999')  AS  CLM_SRVC_UNIT_QTY
	    ,RPAD(COALESCE(C.CLM_FFS_IND,' '),1,' ')                       AS CLM_FFS_IND  
	    ,RPAD(COALESCE(C.CLM_DRVD_HDR_IND,' '),20,' ')                 AS CLM_DRVD_HDR_IND
	    ,RPAD(COALESCE(C.CLM_MASS_ADJSTMT_IND,' '),1,' ')              AS CLM_MASS_ADJSTMT_IND 

		,TO_CHAR(COALESCE(C.CLM_UNIQ_ID,0),'FM9999999999999)')         AS CLM_UNIQ_ID   
		,TO_CHAR(COALESCE(C.META_LST_UPDT_SK,0),'FM9999999999999)')    AS META_LST_UPDT_SK 
	 	-- 18 bytes
		,TO_CHAR(COALESCE(C.META_LST_UPDT_SRC_SK,0),'FM999999999999999999)')   AS META_LST_UPDT_SRC_SK   

	     ,RPAD(COALESCE(C.BENE_SK_LKP_CD,' '),1,' ')  AS  BENE_SK_LKP_CD 
	     ,RPAD(COALESCE(C.BENE_ID_TYPE_CD,' '),1,' ') AS  BENE_ID_TYPE_CD 

		/*
		,RPAD(CAS.CLM_1_REV_CNTR_ANSI_GRP_CD,2,' ')  AS  CLM_1_REV_CNTR_ANSI_GRP_CD 
		,RPAD(CAS.CLM_1_REV_CNTR_ANSI_RSN_CD,3,' ')  AS  CLM_1_REV_CNTR_ANSI_RSN_CD 
		,RPAD(CAS.CLM_2_REV_CNTR_ANSI_GRP_CD,2,' ')  AS  CLM_2_REV_CNTR_ANSI_GRP_CD 
		,RPAD(CAS.CLM_2_REV_CNTR_ANSI_RSN_CD,3,' ')  AS  CLM_2_REV_CNTR_ANSI_RSN_CD
		,RPAD(CAS.CLM_3_REV_CNTR_ANSI_GRP_CD,2,' ')  AS  CLM_3_REV_CNTR_ANSI_GRP_CD 
		,RPAD(CAS.CLM_3_REV_CNTR_ANSI_RSN_CD,3,' ')  AS  CLM_3_REV_CNTR_ANSI_RSN_CD
		,RPAD(CAS.CLM_4_REV_CNTR_ANSI_GRP_CD,2,' ')  AS  CLM_4_REV_CNTR_ANSI_GRP_CD 
		,RPAD(CAS.CLM_4_REV_CNTR_ANSI_RSN_CD,3,' ')  AS  CLM_4_REV_CNTR_ANSI_RSN_CD	
*/

		,RPAD(CDN.CLM_NRLN_RIC_CD,1,' ')         AS CLM_NRLN_RIC_CD
		,CASE WHEN CDN.CLM_MDCR_ACRTN_NUM IS NULL THEN '   '  ELSE  TO_CHAR(CDN.CLM_MDCR_ACRTN_NUM,'FM000')  END    AS CLM_MDCR_ACRTN_NUM

		,TO_CHAR(CDN.CLM_NCH_LINK_NUM,'FM000000000')         AS  CLM_NCH_LINK_NUM
		,RPAD(COALESCE(CDN.CLM_NCH_EDIT_DISP_CD,' '),2,' ')  AS  CLM_NCH_EDIT_DISP_CD  
		,RPAD(COALESCE(CDN.CLM_NCH_MDFY_BIC_CD,' '),1,' ')   AS  CLM_NCH_MDFY_BIC_CD  
		,RPAD(COALESCE(CDN.CLM_CWF_NUM,' '),8,' ')           AS  CLM_CWF_NUM  

		,RPAD(CDN.CLM_MDCR_BATCH_NUM,4,' ')                  AS CLM_MDCR_BATCH_NUM
		,RPAD(COALESCE(CDN.CLM_CWF_PLUS_4_ZIP_CD,' '),4,' ') AS CLM_CWF_PLUS_4_ZIP_CD 
			
		,RPAD(CDN.BENE_RACE_CD,2,' ')         AS BENE_RACE_CD
		,RPAD(CDN.CLM_CWF_BENE_MDCR_STUS_CD,2,' ')  AS CLM_CWF_BENE_MDCR_STUS_CD


		,RPAD(COALESCE(CDN.CLM_LAST_NAME,' '),60,' ')     AS CLM_LAST_NAME                    
		,RPAD(COALESCE(CDN.CLM_1ST_NAME,' '),35,' ')      AS CLM_1ST_NAME                  
		,RPAD(COALESCE(CDN.CLM_INTL_MDL_NAME,' '),1,' ')  AS CLM_INTL_MDL_NAME             

		,RPAD(CDN.CLM_BENE_CWF_LOC_CD,1,' ')          AS CLM_BENE_CWF_LOC_CD
		,RPAD(CDN.CLM_EXCPTD_NEXCPTD_CD,1,' ')        AS CLM_EXCPTD_NEXCPTD_CD
		,RPAD(CDN.CLM_PTNT_TRTMT_AUTHRZTN_NUM,18,' ') AS CLM_PTNT_TRTMT_AUTHRZTN_NUM
		,RPAD(CDN.CLM_PTNT_CNTL_NUM,80,' ')           AS CLM_PTNT_CNTL_NUM
		,RPAD(CDN.CLM_PTNT_MDCL_REC_NUM,80,' ')       AS CLM_PTNT_MDCL_REC_NUM
		,RPAD(CDN.CLM_PRO_CNTL_NUM,14,' ')            AS CLM_PRO_CNTL_NUM
			
		,RPAD(CDN.CLM_CARE_IMPRVMT_MODEL_1_CD,2,' ')  AS CLM_CARE_IMPRVMT_MODEL_1_CD
		,RPAD(CDN.CLM_CARE_IMPRVMT_MODEL_2_CD,2,' ')  AS CLM_CARE_IMPRVMT_MODEL_2_CD
		,RPAD(CDN.CLM_CARE_IMPRVMT_MODEL_3_CD,2,' ')  AS CLM_CARE_IMPRVMT_MODEL_3_CD
		,RPAD(CDN.CLM_CARE_IMPRVMT_MODEL_4_CD,2,' ')  AS CLM_CARE_IMPRVMT_MODEL_4_CD
	 
		,RPAD(CDN.CLM_PTNT_RLTNSHP_CD,2,' ')          AS CLM_PTNT_RLTNSHP_CD
		,RPAD(CDN.CLM_FPS_RSN_CD,3,' ')               AS CLM_FPS_RSN_CD
		,RPAD(CDN.CLM_FPS_RMRK_CD,5,' ')              AS CLM_FPS_RMRK_CD
		,RPAD(CDN.CLM_MASS_ADJSTMT_TYPE_CD,1,' ')     AS CLM_MASS_ADJSTMT_TYPE_CD
		
		,RPAD(COALESCE(CDN.CLM_RSDL_PYMT_IND_CD,' '),1,' ')         AS CLM_RSDL_PYMT_IND_CD
		,RPAD(COALESCE(CDN.CLM_ACO_ID_NUM,' '),10)                  AS CLM_ACO_ID_NUM
		,RPAD(COALESCE(CDN.CLM_SBMTD_BENE_ID_TYPE_CD,' '),1,' ')    AS CLM_SBMTD_BENE_ID_TYPE_CD

		,RPAD(COALESCE(CDN.CLM_DEMO_ETC_ADJSTMT_CD,' '),1,' ')  AS CLM_DEMO_ETC_ADJSTMT_CD

		--- MCO_CNTRCT_NUM**********
		,RPAD(CASE WHEN CDN.CLM_MCO_1ST_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_1ST_CNTRCT_NUM
		,RPAD(CASE WHEN CDN.CLM_MCO_2ND_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_2ND_CNTRCT_NUM
		
		,RPAD(COALESCE(CDN.CLM_MCO_OPTN_CD,' '),1,' ')       AS  CLM_MCO_OPTN_CD   
		,RPAD(COALESCE(CDN.CLM_MCO_1ST_OPTN_CD,' '),1,' ')   AS  CLM_MCO_1ST_OPTN_CD   
		,RPAD(COALESCE(CDN.CLM_MCO_2ND_OPTN_CD,' '),1,' ')   AS  CLM_MCO_2ND_OPTN_CD   

		,CASE WHEN CDN.CLM_MCO_1ST_PRD_BGN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDN.CLM_MCO_1ST_PRD_BGN_DT,'YYYYMMDD') END AS CLM_MCO_1ST_PRD_BGN_DT
		,CASE WHEN CDN.CLM_MCO_2ND_PRD_BGN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDN.CLM_MCO_2ND_PRD_BGN_DT,'YYYYMMDD') END AS CLM_MCO_2ND_PRD_BGN_DT

		,CASE WHEN CDN.CLM_MCO_1ST_PRD_END_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDN.CLM_MCO_1ST_PRD_END_DT,'YYYYMMDD') END AS CLM_MCO_1ST_PRD_END_DT
		,CASE WHEN CDN.CLM_MCO_2ND_PRD_END_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDN.CLM_MCO_2ND_PRD_END_DT,'YYYYMMDD') END AS CLM_MCO_2ND_PRD_END_DT

		,RPAD(CASE WHEN CDN.CLM_MCO_1ST_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_1ST_HLTH_PLAN_ID
		,RPAD(CASE WHEN CDN.CLM_MCO_2ND_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_2ND_HLTH_PLAN_ID

		,RPAD(COALESCE(CDN.CLM_DEMO_1ST_NUM,' '),2,' ')  AS  CLM_DEMO_1ST_NUM 
		,RPAD(COALESCE(CDN.CLM_DEMO_2ND_NUM,' '),2,' ')  AS  CLM_DEMO_2ND_NUM 
		,RPAD(COALESCE(CDN.CLM_DEMO_3RD_NUM,' '),2,' ')  AS  CLM_DEMO_3RD_NUM 
		,RPAD(COALESCE(CDN.CLM_DEMO_4TH_NUM,' '),2,' ')  AS  CLM_DEMO_4TH_NUM 
		,RPAD(COALESCE(CDN.CLM_DEMO_5TH_NUM,' '),2,' ')  AS  CLM_DEMO_5TH_NUM 

		,RPAD(COALESCE(CDN.CLM_DEMO_INFO_1_DESC,' '),15,' ')  AS  CLM_DEMO_INFO_1_DESC 
		,RPAD(COALESCE(CDN.CLM_DEMO_INFO_2_DESC,' '),15,' ')  AS  CLM_DEMO_INFO_2_DESC 
		,RPAD(COALESCE(CDN.CLM_DEMO_INFO_3_DESC,' '),15,' ')  AS  CLM_DEMO_INFO_3_DESC 
		,RPAD(COALESCE(CDN.CLM_DEMO_INFO_4_DESC,' '),15,' ')  AS  CLM_DEMO_INFO_4_DESC 
		,RPAD(COALESCE(CDN.CLM_DEMO_INFO_5_DESC,' '),15,' ')  AS  CLM_DEMO_INFO_5_DESC 

		,RPAD(COALESCE(CDN.CLM_CEC_TLHLTH_SW,' '),1,' ')          AS  CLM_CEC_TLHLTH_SW 
		,RPAD(COALESCE(CDN.CLM_ACO_CARE_MGMT_HCBS_SW,' '),1,' ')  AS  CLM_ACO_CARE_MGMT_HCBS_SW
		----,RPAD(COALESCE(CDN.CLM_NGACO_PBPMT_SW,' '),1,' ')         AS  CLM_NGACO_PBPMT_SW  

		,RPAD(COALESCE(CDN.CLM_BNFT_ENHNCMT_1_CD,' '),2,' ')  AS  CLM_BNFT_ENHNCMT_1_CD
		,RPAD(COALESCE(CDN.CLM_BNFT_ENHNCMT_2_CD,' '),2,' ')  AS  CLM_BNFT_ENHNCMT_2_CD
		,RPAD(COALESCE(CDN.CLM_BNFT_ENHNCMT_3_CD,' '),2,' ')  AS  CLM_BNFT_ENHNCMT_3_CD
		,RPAD(COALESCE(CDN.CLM_BNFT_ENHNCMT_4_CD,' '),2,' ')  AS  CLM_BNFT_ENHNCMT_4_CD
		,RPAD(COALESCE(CDN.CLM_BNFT_ENHNCMT_5_CD,' '),2,' ')  AS  CLM_BNFT_ENHNCMT_5_CD

		,RPAD(COALESCE(CDN.CLM_NGACO_TLHLTH_SW,' '),1,' ')        AS  CLM_NGACO_TLHLTH_SW  
		,RPAD(COALESCE(CDN.CLM_NGACO_PDSCHRG_HCBS_SW,' '),1,' ')  AS  CLM_NGACO_PDSCHRG_HCBS_SW  
		,RPAD(COALESCE(CDN.CLM_NGACO_SNF_WVR_SW,' '),1,' ')       AS  CLM_NGACO_SNF_WVR_SW  
		,RPAD(COALESCE(CDN.CLM_NGACO_CPTATN_SW,' '),1,' ')        AS  CLM_NGACO_CPTATN_SW  

		,CASE WHEN CDS.CLM_FROM_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_FROM_DT,'YYYYMMDD') END AS CLM_FROM_DT
		,CASE WHEN CDS.CLM_THRU_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_THRU_DT,'YYYYMMDD') END AS CLM_THRU_DT
		
		,CASE WHEN CDS.CLM_NCH_WKLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_WKLY_PROC_DT,'YYYYMMDD') END AS CLM_NCH_WKLY_PROC_DT
		,CASE WHEN CDS.CLM_CWF_ACRTN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CWF_ACRTN_DT,'YYYYMMDD') END         AS CLM_CWF_ACRTN_DT
		
		,CASE WHEN CDS.CLM_NCH_DLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_DLY_PROC_DT,'YYYYMMDD') END AS CLM_NCH_DLY_PROC_DT
		,CASE WHEN CDS.CLM_SUBMSN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SUBMSN_DT,'YYYYMMDD') END             AS CLM_SUBMSN_DT
		
		,CASE WHEN CDS.CLM_SCHLD_PMT_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SCHLD_PMT_DT,'YYYYMMDD') END           AS CLM_SCHLD_PMT_DT
		,CASE WHEN CDS.CLM_TRNSMSN_TO_CMS_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_TRNSMSN_TO_CMS_DT,'YYYYMMDD') END AS CLM_TRNSMSN_TO_CMS_DT

		,CASE WHEN CDS.CLM_CMS_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CMS_PROC_DT,'YYYYMMDD') END AS CLM_CMS_PROC_DT
		,CASE WHEN CDS.CLM_PRO_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_PRO_PROC_DT,'YYYYMMDD') END AS CLM_PRO_PROC_DT


        ,TO_CHAR(COALESCE(CEGS.CLM_EDIT_SGNTR_MBR_CNT,0),'FM9999')  AS CLM_EDIT_SGNTR_MBR_CNT
		
		,RPAD(COALESCE(CI.CLM_TRANS_CD,' '),1,' ')             AS CLM_TRANS_CD
		,RPAD(COALESCE(CI.CLM_BILL_FAC_TYPE_CD,' '),1,' ')     AS CLM_BILL_FAC_TYPE_CD
		,RPAD(COALESCE(CI.CLM_BILL_CLSFCTN_CD,' '),1,' ')      AS CLM_BILL_CLSFCTN_CD
		,RPAD(COALESCE(CI.CLM_BILL_FREQ_CD,' '),1,' ')         AS CLM_BILL_FREQ_CD
		,RPAD(COALESCE(CI.CLM_MQA_PTCH_CD,' '),1,' ')          AS CLM_MQA_PTCH_CD
		,RPAD(COALESCE(CI.CLM_MDCR_NPMT_RSN_CD,' '),2,' ')     AS CLM_MDCR_NPMT_RSN_CD

		-- S9(09).99
		,TO_CHAR(CI.CLM_MDCR_INSTNL_PRMRY_PYR_AMT,'S000000000.00')     AS CLM_MDCR_INSTNL_PRMRY_PYR_AMT

		,RPAD(REPLACE(COALESCE(CI.CLM_NCH_PRMRY_PYR_CD,''),'~',''),1,' ') AS CLM_NCH_PRMRY_PYR_CD
		
		,RPAD(COALESCE(CI.CLM_RQST_CNCL_RSN_CD,' '),1,' ')        AS CLM_RQST_CNCL_RSN_CD
		,RPAD(COALESCE(CI.CLM_FI_ACTN_CD,' '),1,' ')              AS CLM_FI_ACTN_CD
		,RPAD(COALESCE(CI.CLM_MDCD_INSRR_ID,' '),20,' ')          AS CLM_MDCD_INSRR_ID  

		,RPAD(COALESCE(CI.CLM_MDCD_INFO_CD,' '),4,' ')            AS CLM_MDCD_INFO_CD
		,RPAD(COALESCE(CI.CLM_MDCR_INSTNL_MCO_PD_SW,' '),1,' ')   AS CLM_MDCR_INSTNL_MCO_PD_SW
		,RPAD(COALESCE(CI.BENE_PTNT_STUS_CD,' '),2,' ')           AS BENE_PTNT_STUS_CD
		,RPAD(COALESCE(CI.CLM_PPS_IND_CD,' '),1,' ')              AS CLM_PPS_IND_CD
		
		-- S9(09).99
		,TO_CHAR(CI.CLM_MDCR_INSTNL_TOT_CHRG_AMT,'S000000000.00') AS CLM_MDCR_INSTNL_TOT_CHRG_AMT
		
		,RPAD(COALESCE(CI.CLM_PRCR_RTRN_CD,' '),2,' ')            AS  CLM_PRCR_RTRN_CD
		,RPAD(COALESCE(CI.CLM_MDCR_INSTNL_BUSNS_SGMT_CD,' '),4,' ')    AS  CLM_MDCR_INSTNL_BUSNS_SGMT_CD
		,RPAD(COALESCE(CI.CLM_INSTNL_WC_IND,' '),1,' ')           AS CLM_INSTNL_WC_IND

		,RPAD(COALESCE(CI.CLM_OP_SRVC_TYPE_CD,' '),1,' ')         AS  CLM_OP_SRVC_TYPE_CD
		,RPAD(COALESCE(CI.CLM_OP_RFRL_CD,' '),1,' ')              AS  CLM_OP_RFRL_CD

		-- S9(09).99
		,TO_CHAR(COALESCE(CI.CLM_INSTNL_PRFNL_AMT,0),'S000000000.00')         AS CLM_INSTNL_PRFNL_AMT
		-- S9(09).99
		,TO_CHAR(COALESCE(CI.CLM_MDCR_OP_DDCTBL_AMT,0),'S000000000.00')       AS CLM_MDCR_OP_DDCTBL_AMT
		-- S9(09).99
		,TO_CHAR(COALESCE(CI.CLM_MDCR_INSTNL_BENE_PD_AMT,0),'S000000000.00')  AS CLM_MDCR_INSTNL_BENE_PD_AMT

		,RPAD(COALESCE(CI.CLM_OP_TRANS_TYPE_CD,' '),1,' ')        AS  CLM_OP_TRANS_TYPE_CD
		,RPAD(COALESCE(CI.CLM_ESRD_REIMBRSMT_CD,' '),1,' ')       AS  CLM_ESRD_REIMBRSMT_CD
		-- S9(01).9999
		,TO_CHAR(COALESCE(CI.CLM_GAF_NUM,0),'S0.0000')          AS CLM_GAF_NUM

/*
		,RPAD(COALESCE(TO_CHAR(CL.CLM_FROM_DT, 'YYYYMMDD'),''),8,' ') AS CLM_FROM_DT
		,TO_CHAR(COALESCE(CL.CLNDR_CY_NUM,0),'FM0000')                AS CLNDR_CY_NUM 
		,RPAD(COALESCE(CL.CLM_FAC_PRVDR_OSCAR_NUM,' '),6,' ')         AS CLM_FAC_PRVDR_OSCAR_NUM 
		,RPAD(COALESCE(CL.CLM_FAC_PRVDR_OSCAR_STATE_CD,' '),2,' ')    AS CLM_FAC_PRVDR_OSCAR_STATE_CD
		,RPAD(COALESCE(CL.CLM_FAC_PRVDR_OSCAR_FAC_CD,' '),3,' ')      AS CLM_FAC_PRVDR_OSCAR_FAC_CD

		,RPAD(COALESCE(CL.CLM_FAC_PRVDR_OSCAR_EMER_IND,' '),1,' ')    AS CLM_FAC_PRVDR_OSCAR_EMER_IND
		,RPAD(COALESCE(CL.CLM_CNTRCTR_NUM,' '),5,' ')                 AS CLM_CNTRCTR_NUM
		,RPAD(COALESCE(CL.PRVDR_FAC_PRVDR_NPI_NUM,' '),10,' ')        AS PRVDR_FAC_PRVDR_NPI_NUM
		,RPAD(COALESCE(CL.CLM_FAC_PRVDR_NPI_NUM,' '),10,' ')          AS CLM_FAC_PRVDR_NPI_NUM

		,RPAD(COALESCE(CL.CLM_LINE_REV_CTR_CD,' '),4,' ')             AS CLM_LINE_REV_CTR_CD

		,RPAD(COALESCE(TO_CHAR(CL.CLM_LINE_FROM_DT, 'YYYYMMDD'),''),8,' ') AS CLM_LINE_FROM_DT
		,RPAD(COALESCE(TO_CHAR(CL.CLM_LINE_THRU_DT, 'YYYYMMDD'),''),8,' ') AS CLM_LINE_THRU_DT

		,RPAD(REPLACE(COALESCE(CL.CLM_LINE_HCPCS_CD,''),'~',''),5,' ') AS CLM_LINE_HCPCS_CD
		,RPAD(REPLACE(COALESCE(CL.HCPCS_1_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_1_MDFR_CD
		,RPAD(REPLACE(COALESCE(CL.HCPCS_2_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_2_MDFR_CD
		,RPAD(REPLACE(COALESCE(CL.HCPCS_3_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_3_MDFR_CD
		,RPAD(REPLACE(COALESCE(CL.HCPCS_4_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_4_MDFR_CD
		,RPAD(REPLACE(COALESCE(CL.HCPCS_5_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_5_MDFR_CD

		,RPAD(COALESCE(CL.CLM_LINE_IDE_NUM,''),20,' ')                 AS CLM_LINE_IDE_NUM
		,RPAD(COALESCE(CL.CLM_LINE_NDC_CD,''),11,' ')                  AS CLM_LINE_NDC_CD
		,RPAD(COALESCE(CL.CLM_LINE_NDC_QTY_QLFYR_CD,''),2,' ')         AS CLM_LINE_NDC_QTY_QLFYR_CD

		-- S9(10).999
		,TO_CHAR(COALESCE(CL.CLM_LINE_NDC_QTY,0),'S0000000000.000')    AS CLM_LINE_NDC_QTY 
		-- S9(14).9999
		,TO_CHAR(COALESCE(CL.CLM_LINE_SRVC_UNIT_QTY,0),'S00000000000000.0000')     AS CLM_LINE_SRVC_UNIT_QTY
		-- S9(09).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_BLOOD_DDCTBL_AMT,0),'S000000000.00')         AS CLM_LINE_BLOOD_DDCTBL_AMT
		-- S9(09).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_MDCR_DDCTBL_AMT,0),'S000000000.00')          AS CLM_LINE_MDCR_DDCTBL_AMT
		-- S9(09).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_PRVDR_PMT_AMT,0),'S000000000.00')            AS CLM_LINE_PRVDR_PMT_AMT
		-- S9(13).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_PD_AMT,0),'S0000000000000.00')          AS CLM_LINE_BENE_PD_AMT
		-- S9(09).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_PMT_AMT,0),'S000000000.00')             AS CLM_LINE_BENE_PMT_AMT
		-- S9(07).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_CVRD_PD_AMT,0),'S0000000.00')                AS CLM_LINE_CVRD_PD_AMT	
        -- S9(13).99  
		,TO_CHAR(COALESCE(CL.CLM_LINE_SBMT_CHRG_AMT,0),'S0000000000000.00')        AS CLM_LINE_SBMT_CHRG_AMT	
		-- S9(09).99
		,TO_CHAR(COALESCE(CL.CLM_LINE_NCVRD_CHRG_AMT,0),'S000000000.00')           AS CLM_LINE_NCVRD_CHRG_AMT	

		,RPAD(COALESCE(CL.CLM_CNSLDTD_BLG_CD,''),1,' ')              AS CLM_CNSLDTD_BLG_CD
		,RPAD(COALESCE(CL.PRVDR_RNDRNG_PRVDR_NPI_NUM,''),10,' ')     AS PRVDR_RNDRNG_PRVDR_NPI_NUM
		,RPAD(COALESCE(CL.CLM_RNDRG_PRVDR_NAME,' '),60,' ')          AS CLM_RNDRG_PRVDR_NAME

		,RPAD(COALESCE(CL.CLM_LINE_DCMTN_CD,' '),2,' ')              AS CLM_LINE_DCMTN_CD
		,RPAD(COALESCE(CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,' '),2,' ')  AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD
		,RPAD(COALESCE(CL.CLM_LINE_FPS_MODEL_NUM,' '),2,' ')         AS CLM_LINE_FPS_MODEL_NUM
		,RPAD(COALESCE(CL.CLM_LINE_FPS_MSN_1_CD,' '),5,' ')          AS CLM_LINE_FPS_MSN_1_CD
		,RPAD(COALESCE(CL.CLM_LINE_FPS_MSN_2_CD,' '),5,' ')          AS CLM_LINE_FPS_MSN_2_CD

		,RPAD(COALESCE(CL.CLM_LINE_PMD_UNIQ_TRKNG_NUM,' '),14,' ')   AS CLM_LINE_PMD_UNIQ_TRKNG_NUM
		,RPAD(COALESCE(CL.CLM_LINE_FFS_IND,' '),1,' ')               AS CLM_LINE_FFS_IND

		-- 9(13)
		,TO_CHAR(COALESCE(CL.CLM_UNIQ_ID,0),'FM0000000000000')        AS CLM_UNIQ_ID
		-- 9(18)
		,TO_CHAR(COALESCE(CL.META_LST_UPDT_SK,0),'FM000000000000000000')        AS META_LST_UPDT_SK
		-- 9(18)
		,TO_CHAR(COALESCE(CL.META_LST_UPDT_SRC_SK,0),'FM000000000000000000')    AS META_LST_UPDT_SRC_SK

		,RPAD(COALESCE(CLDN.CLM_LINE_THRPY_CAP_IND_1_CD,' '),1,' ')    AS CLM_LINE_THRPY_CAP_IND_1_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_THRPY_CAP_IND_2_CD,' '),1,' ')    AS CLM_LINE_THRPY_CAP_IND_2_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_THRPY_CAP_IND_3_CD,' '),1,' ')    AS CLM_LINE_THRPY_CAP_IND_3_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_THRPY_CAP_IND_4_CD,' '),1,' ')    AS CLM_LINE_THRPY_CAP_IND_4_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_THRPY_CAP_IND_5_CD,' '),1,' ')    AS CLM_LINE_THRPY_CAP_IND_5_CD

		,RPAD(COALESCE(CLDN.CLM_LINE_FPS_RSN_CD,' '),3,' ')            AS CLM_LINE_FPS_RSN_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_FPS_RMRK_CD,' '),5,' ')           AS CLM_LINE_FPS_RMRK_CD
		,RPAD(COALESCE(CLDN.CLM_LINE_PA_IND_CD,' '),4,' ')             AS CLM_LINE_PA_IND_CD
		,RPAD(COALESCE(CLDN.CLM_PA_RP_EXCLSN_CD,' '),1,' ')            AS CLM_PA_RP_EXCLSN_CD	

		,RPAD(COALESCE(TO_CHAR(CLI.CLM_LINE_INSTNL_REV_CTR_DT, 'YYYYMMDD'),''),8,' ') AS CLM_LINE_INSTNL_REV_CTR_DT

		,RPAD(COALESCE(CLI.CLM_REV_APC_HIPPS_CD,' '),5,' ')    AS CLM_REV_APC_HIPPS_CD
		,RPAD(COALESCE(CLI.CLM_REV_PMT_MTHD_CD,' '),2,' ')     AS CLM_REV_PMT_MTHD_CD
		,RPAD(COALESCE(CLI.CLM_REV_DSCNT_IND_CD,' '),1,' ')    AS CLM_REV_DSCNT_IND_CD
		,RPAD(COALESCE(CLI.CLM_REV_PACKG_IND_CD,' '),1,' ')    AS CLM_REV_PACKG_IND_CD
		,RPAD(COALESCE(CLI.CLM_REV_PRICNG_IND_CD,' '),1,' ')   AS CLM_REV_PRICNG_IND_CD
		,RPAD(COALESCE(CLI.CLM_OTAF_ONE_IND_CD,' '),1,' ')     AS CLM_OTAF_ONE_IND_CD

		-- S9(9).99 (For all 5 fields)
		,TO_CHAR(COALESCE(CLI.CLM_LINE_INSTNL_RATE_AMT,0),'S000000000.00')    AS CLM_LINE_INSTNL_RATE_AMT
		,TO_CHAR(COALESCE(CLI.CLM_LINE_INSTNL_ADJSTD_AMT,0),'S000000000.00')         AS CLM_LINE_INSTNL_ADJSTD_AMT
		,TO_CHAR(COALESCE(CLI.CLM_LINE_INSTNL_RDCD_AMT,0),'S000000000.00')           AS CLM_LINE_INSTNL_RDCD_AMT
		,TO_CHAR(COALESCE(CLI.CLM_LINE_INSTNL_MSP1_PD_AMT,0),'S000000000.00')        AS CLM_LINE_INSTNL_MSP1_PD_AMT
		,TO_CHAR(COALESCE(CLI.CLM_LINE_INSTNL_MSP2_PD_AMT,0),'S000000000.00')        AS CLM_LINE_INSTNL_MSP2_PD_AMT

		,RPAD(COALESCE(CLI.CLM_DDCTBL_COINSRNC_CD,' '),1,' ')           AS CLM_DDCTBL_COINSRNC_CD
		,RPAD(COALESCE(CLI.CLM_REV_CNTR_STUS_CD,' '),2,' ')             AS CLM_REV_CNTR_STUS_CD
		,RPAD(COALESCE(CLI.CLM_LINE_INSTNL_DUP_CLM_CHK_CD,' '),1,' ')   AS CLM_LINE_INSTNL_DUP_CLM_CHK_CD
		,RPAD(COALESCE(CLI.CLM_LINE_INSTNL_APC_BUFR_CD,' '),2,' ')      AS CLM_LINE_INSTNL_APC_BUFR_CD

		-- S9(09).99
		,TO_CHAR(COALESCE(CLI.CLM_LINE_ADD_ON_PYMT_AMT,0),'S000000000.00')      AS CLM_LINE_ADD_ON_PYMT_AMT
		-- S9(07).9999
		,TO_CHAR(COALESCE(CLI.CLM_REV_CNTR_TDAPA_AMT,0),'S0000000.0000')        AS CLM_REV_CNTR_TDAPA_AMT

*/



		--*************************************************************
		--* CLM_OCRNC_SPAN ARRAY
		--*************************************************************
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_1,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_1
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_2,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_2
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_3,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_3
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_4,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_4
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_5,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_5
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_6,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_6
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_7,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_7
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_8,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_8
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_9,' '),2,' ')      AS CLM_OCRNC_SPAN_CD_9
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_10,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_10

		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_11,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_11
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_12,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_12
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_13,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_13
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_14,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_14
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_15,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_15
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_16,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_16
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_17,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_17
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_18,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_18
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_19,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_19
		,RPAD(COALESCE(COSM.CLM_OCRNC_SPAN_CD_20,' '),2,' ')     AS CLM_OCRNC_SPAN_CD_20
	
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_1, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_1
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_2, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_2
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_3, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_3
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_4, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_4
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_5, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_5
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_6, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_6
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_7, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_7
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_8, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_8
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_9, '10010101')   AS CLM_OCRNC_SPAN_FROM_DT_9
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_10, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_10

		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_11, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_11
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_12, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_12
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_13, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_13
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_14, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_14
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_15, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_15
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_16, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_16
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_17, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_17
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_18, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_18
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_19, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_19
		,COALESCE(COSM.CLM_OCRNC_SPAN_FROM_DT_20, '10010101')  AS CLM_OCRNC_SPAN_FROM_DT_20


		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_1, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_1
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_2, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_2
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_3, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_3
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_4, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_4
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_5, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_5
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_6, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_6
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_7, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_7
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_8, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_8
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_9, '10010101')   AS CLM_OCRNC_SPAN_THRU_DT_9
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_10, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_10

		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_11, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_11
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_12, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_12
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_13, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_13
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_14, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_14
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_15, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_15
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_16, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_16
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_17, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_17
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_18, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_18
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_19, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_19
		,COALESCE(COSM.CLM_OCRNC_SPAN_THRU_DT_20, '10010101')  AS CLM_OCRNC_SPAN_THRU_DT_20

		
		--*************************************************************
		--* DGNS and PRCDR ARRAY
		--*************************************************************		
/*
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_1
        ,PROD.CLM_DGNS_CD_1
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_2
        ,PROD.CLM_DGNS_CD_2
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_3
        ,PROD.CLM_DGNS_CD_3
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_4
        ,PROD.CLM_DGNS_CD_4
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_5
        ,PROD.CLM_DGNS_CD_5
        ,PROD.CLM_DGNS_PRCDR_ICD_IND_6
        ,PROD.CLM_DGNS_CD_6    
        ,PROD.CLM_PRCDR_PRFRM_DT


	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND
	,RPAD(CASE WHEN PROD_MT.CLM_PRNCPL_DGNS_CD = '~'     THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRNCPL_DGNS_CD,' ') END,7,' ')     AS CLM_PRNCPL_DGNS_CD

	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
    ,RPAD(COALESCE(CLM_DGNS_E_CD,' '),2,' ')  AS CLM_DGNS_E_CD  





	,TO_CHAR(PROD_MT.CLM_DGNS_TOT_OCRNC_CNT,'FM00')   AS CLM_DGNS_TOT_OCRNC_CNT
	,TO_CHAR(PROD_MT.CLM_PRCDR_TOT_OCRNC_CNT,'FM00')  AS CLM_PRCDR_TOT_OCRNC_CNT

	--- DGNS_R_CD  **********
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ')   AS CLM_DGNS_PRCDR_ICD_IND
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD   = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD,' ')   END,7,' ') AS CLM_DGNS_RSN_FOR_VISIT_CD 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_2_RSN_FOR_VISIT_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_3_RSN_FOR_VISIT_CD 

	--- CLM-DGNS-D  ************
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_1_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_1_CD,' ')  END,7,' ')  AS CLM_DGNS_1_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_CD,' ')  END,7,' ')  AS CLM_DGNS_2_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_CD,' ')  END,7,' ')  AS CLM_DGNS_3_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_4_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_4_CD,' ')  END,7,' ')  AS CLM_DGNS_4_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_5_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_5_CD,' ')  END,7,' ')  AS CLM_DGNS_5_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_6_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_6_CD,' ')  END,7,' ')  AS CLM_DGNS_6_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_7_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_7_CD,' ')  END,7,' ')  AS CLM_DGNS_7_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_8_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_8_CD,' ')  END,7,' ')  AS CLM_DGNS_8_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_9_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_9_CD,' ')  END,7,' ')  AS CLM_DGNS_9_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_10_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_10_CD,' ') END,7,' ')  AS CLM_DGNS_10_CD

	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 

	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_1_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_1_CD,' ')  END,7,' ')  AS CLM_PRCDR_1_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_2_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_2_CD,' ')  END,7,' ')  AS CLM_PRCDR_2_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_3_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_3_CD,' ')  END,7,' ')  AS CLM_PRCDR_3_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_4_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_4_CD,' ')  END,7,' ')  AS CLM_PRCDR_4_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_5_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_5_CD,' ')  END,7,' ')  AS CLM_PRCDR_5_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_PRCDR_6_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRCDR_6_CD,' ')  END,7,' ')  AS CLM_PRCDR_6_CD	

    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_1_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_1_DT  
    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_2_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_2_DT  
    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_3_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_3_DT  
    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_4_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_4_DT  
    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_5_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_5_DT  
    ,COALESCE(TO_CHAR(PROD_MT.CLM_PRCDR_6_DT,'YYYYMMDD'),'10000101')    AS  CLM_PRCDR_6_DT  

*/



	--*************************************************************
    ,TO_CHAR(COALESCE(CPGS.CLM_PTCH_SGNTR_MBR_CNT,0),'FM000')           AS  CLM_PTCH_SGNTR_MBR_CNT 
 
    ,RPAD(COALESCE(CPGSM.CLM_PTCH_CD,''),2,' ')                         AS  CLM_PTCH_CD 
    ,COALESCE(TO_CHAR(CPGSM.CLM_PTCH_APPLY_DT,'YYYYMMDD'),'10000101')   AS  CLM_PTCH_APPLY_DT 

    ,TO_CHAR(COALESCE(CRCS.CLM_RLT_COND_SGNTR_MBR_CNT,0),'FM000')       AS  CLM_RLT_COND_SGNTR_MBR_CNT 

	--*************************************************************
	--* CRCSM ARRAY
	--*************************************************************
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_1,''),2,' ')   AS CLM_RLT_COND_CD_1
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_2,''),2,' ')   AS CLM_RLT_COND_CD_2
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_3,''),2,' ')   AS CLM_RLT_COND_CD_3
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_4,''),2,' ')   AS CLM_RLT_COND_CD_4
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_5,''),2,' ')   AS CLM_RLT_COND_CD_5
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_6,''),2,' ')   AS CLM_RLT_COND_CD_6
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_7,''),2,' ')   AS CLM_RLT_COND_CD_7
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_8,''),2,' ')   AS CLM_RLT_COND_CD_8
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_9,''),2,' ')   AS CLM_RLT_COND_CD_9
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_10,''),2,' ')  AS CLM_RLT_COND_CD_10

    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_11,''),2,' ')  AS CLM_RLT_COND_CD_11
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_12,''),2,' ')  AS CLM_RLT_COND_CD_12
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_13,''),2,' ')  AS CLM_RLT_COND_CD_13
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_14,''),2,' ')  AS CLM_RLT_COND_CD_14
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_15,''),2,' ')  AS CLM_RLT_COND_CD_15
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_16,''),2,' ')  AS CLM_RLT_COND_CD_16
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_17,''),2,' ')  AS CLM_RLT_COND_CD_17
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_18,''),2,' ')  AS CLM_RLT_COND_CD_18
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_19,''),2,' ')  AS CLM_RLT_COND_CD_19
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_20,''),2,' ')  AS CLM_RLT_COND_CD_20

    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_21,''),2,' ')  AS CLM_RLT_COND_CD_21
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_22,''),2,' ')  AS CLM_RLT_COND_CD_22
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_23,''),2,' ')  AS CLM_RLT_COND_CD_23
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_24,''),2,' ')  AS CLM_RLT_COND_CD_24
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_25,''),2,' ')  AS CLM_RLT_COND_CD_25
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_26,''),2,' ')  AS CLM_RLT_COND_CD_26
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_27,''),2,' ')  AS CLM_RLT_COND_CD_27
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_28,''),2,' ')  AS CLM_RLT_COND_CD_28
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_29,''),2,' ')  AS CLM_RLT_COND_CD_29
    ,RPAD(COALESCE(CRCSM.CLM_RLT_COND_CD_20,''),2,' ')  AS CLM_RLT_COND_CD_20

	--*************************************************************
	--* CROSM ARRAY
	--*************************************************************
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_1,''),2,' ')  AS CLM_RLT_OCRNC_CD_1
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_2,''),2,' ')  AS CLM_RLT_OCRNC_CD_2
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_3,''),2,' ')  AS CLM_RLT_OCRNC_CD_3
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_4,''),2,' ')  AS CLM_RLT_OCRNC_CD_4
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_5,''),2,' ')  AS CLM_RLT_OCRNC_CD_5
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_6,''),2,' ')  AS CLM_RLT_OCRNC_CD_6
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_7,''),2,' ')  AS CLM_RLT_OCRNC_CD_7
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_8,''),2,' ')  AS CLM_RLT_OCRNC_CD_8
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_9,''),2,' ')  AS CLM_RLT_OCRNC_CD_9
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_10,''),2,' ') AS CLM_RLT_OCRNC_CD_10

	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_11,''),2,' ') AS CLM_RLT_OCRNC_CD_11
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_12,''),2,' ') AS CLM_RLT_OCRNC_CD_12
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_13,''),2,' ') AS CLM_RLT_OCRNC_CD_13
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_14,''),2,' ') AS CLM_RLT_OCRNC_CD_14
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_15,''),2,' ') AS CLM_RLT_OCRNC_CD_15
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_16,''),2,' ') AS CLM_RLT_OCRNC_CD_16
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_17,''),2,' ') AS CLM_RLT_OCRNC_CD_17
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_18,''),2,' ') AS CLM_RLT_OCRNC_CD_18
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_19,''),2,' ') AS CLM_RLT_OCRNC_CD_19
	,RPAD(COALESCE(CROSM.CLM_RLT_OCRNC_CD_20,''),2,' ') AS CLM_RLT_OCRNC_CD_20

	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_1,'10000101')   AS CLM_RLT_OCRNC_DT_1
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_2,'10000101')   AS CLM_RLT_OCRNC_DT_2
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_3,'10000101')   AS CLM_RLT_OCRNC_DT_3
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_4,'10000101')   AS CLM_RLT_OCRNC_DT_4
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_5,'10000101')   AS CLM_RLT_OCRNC_DT_5
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_6,'10000101')   AS CLM_RLT_OCRNC_DT_6
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_7,'10000101')   AS CLM_RLT_OCRNC_DT_7
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_8,'10000101')   AS CLM_RLT_OCRNC_DT_8
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_9,'10000101')   AS CLM_RLT_OCRNC_DT_9
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_10,'10000101')  AS CLM_RLT_OCRNC_DT_10

	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_11,'10000101')  AS CLM_RLT_OCRNC_DT_11
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_12,'10000101')  AS CLM_RLT_OCRNC_DT_12
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_13,'10000101')  AS CLM_RLT_OCRNC_DT_13
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_14,'10000101')  AS CLM_RLT_OCRNC_DT_14
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_15,'10000101')  AS CLM_RLT_OCRNC_DT_15
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_16,'10000101')  AS CLM_RLT_OCRNC_DT_16
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_17,'10000101')  AS CLM_RLT_OCRNC_DT_17
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_18,'10000101')  AS CLM_RLT_OCRNC_DT_18
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_19,'10000101')  AS CLM_RLT_OCRNC_DT_19
	,COALESCE(CROSM.CLM_RLT_OCRNC_DT_20,'10000101')  AS CLM_RLT_OCRNC_DT_20
	
	--*************************************************************
	--* CLM_VAL ARRAY
	--*************************************************************
	,RPAD(COALESCE(VAL.CLM_VAL_CD_1,''),2,' ')   AS CLM_VAL_CD_1
	,RPAD(COALESCE(VAL.CLM_VAL_CD_2,''),2,' ')   AS CLM_VAL_CD_2
	,RPAD(COALESCE(VAL.CLM_VAL_CD_3,''),2,' ')   AS CLM_VAL_CD_3
	,RPAD(COALESCE(VAL.CLM_VAL_CD_4,''),2,' ')   AS CLM_VAL_CD_4
	,RPAD(COALESCE(VAL.CLM_VAL_CD_5,''),2,' ')   AS CLM_VAL_CD_5
	,RPAD(COALESCE(VAL.CLM_VAL_CD_6,''),2,' ')   AS CLM_VAL_CD_6
	,RPAD(COALESCE(VAL.CLM_VAL_CD_7,''),2,' ')   AS CLM_VAL_CD_7
	,RPAD(COALESCE(VAL.CLM_VAL_CD_8,''),2,' ')   AS CLM_VAL_CD_8
	,RPAD(COALESCE(VAL.CLM_VAL_CD_9,''),2,' ')   AS CLM_VAL_CD_9
	,RPAD(COALESCE(VAL.CLM_VAL_CD_10,''),2,' ')  AS CLM_VAL_CD_10

	,RPAD(COALESCE(VAL.CLM_VAL_CD_11,''),2,' ')  AS CLM_VAL_CD_11
	,RPAD(COALESCE(VAL.CLM_VAL_CD_12,''),2,' ')  AS CLM_VAL_CD_12
	,RPAD(COALESCE(VAL.CLM_VAL_CD_13,''),2,' ')  AS CLM_VAL_CD_13
	,RPAD(COALESCE(VAL.CLM_VAL_CD_14,''),2,' ')  AS CLM_VAL_CD_14
	,RPAD(COALESCE(VAL.CLM_VAL_CD_15,''),2,' ')  AS CLM_VAL_CD_15
	,RPAD(COALESCE(VAL.CLM_VAL_CD_16,''),2,' ')  AS CLM_VAL_CD_16
	,RPAD(COALESCE(VAL.CLM_VAL_CD_17,''),2,' ')  AS CLM_VAL_CD_17
	,RPAD(COALESCE(VAL.CLM_VAL_CD_18,''),2,' ')  AS CLM_VAL_CD_18
	,RPAD(COALESCE(VAL.CLM_VAL_CD_19,''),2,' ')  AS CLM_VAL_CD_19
	,RPAD(COALESCE(VAL.CLM_VAL_CD_20,''),2,' ')  AS CLM_VAL_CD_20

	,RPAD(COALESCE(VAL.CLM_VAL_CD_21,''),2,' ')  AS CLM_VAL_CD_21
	,RPAD(COALESCE(VAL.CLM_VAL_CD_22,''),2,' ')  AS CLM_VAL_CD_22
	,RPAD(COALESCE(VAL.CLM_VAL_CD_23,''),2,' ')  AS CLM_VAL_CD_23
	,RPAD(COALESCE(VAL.CLM_VAL_CD_24,''),2,' ')  AS CLM_VAL_CD_24
	,RPAD(COALESCE(VAL.CLM_VAL_CD_25,''),2,' ')  AS CLM_VAL_CD_25
	,RPAD(COALESCE(VAL.CLM_VAL_CD_26,''),2,' ')  AS CLM_VAL_CD_26
	,RPAD(COALESCE(VAL.CLM_VAL_CD_27,''),2,' ')  AS CLM_VAL_CD_27
	,RPAD(COALESCE(VAL.CLM_VAL_CD_28,''),2,' ')  AS CLM_VAL_CD_28
	,RPAD(COALESCE(VAL.CLM_VAL_CD_29,''),2,' ')  AS CLM_VAL_CD_29
	,RPAD(COALESCE(VAL.CLM_VAL_CD_30,''),2,' ')  AS CLM_VAL_CD_30

	,RPAD(COALESCE(VAL.CLM_VAL_CD_31,''),2,' ')  AS CLM_VAL_CD_31
	,RPAD(COALESCE(VAL.CLM_VAL_CD_32,''),2,' ')  AS CLM_VAL_CD_32
	,RPAD(COALESCE(VAL.CLM_VAL_CD_33,''),2,' ')  AS CLM_VAL_CD_33
	,RPAD(COALESCE(VAL.CLM_VAL_CD_34,''),2,' ')  AS CLM_VAL_CD_34
	,RPAD(COALESCE(VAL.CLM_VAL_CD_35,''),2,' ')  AS CLM_VAL_CD_35
	,RPAD(COALESCE(VAL.CLM_VAL_CD_36,''),2,' ')  AS CLM_VAL_CD_36

	
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_1,0),'S000000000.00')  AS CLM_VAL_AMT_1
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_2,0),'S000000000.00')  AS CLM_VAL_AMT_2
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_3,0),'S000000000.00')  AS CLM_VAL_AMT_3
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_4,0),'S000000000.00')  AS CLM_VAL_AMT_4
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_5,0),'S000000000.00')  AS CLM_VAL_AMT_5
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_6,0),'S000000000.00')  AS CLM_VAL_AMT_6
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_7,0),'S000000000.00')  AS CLM_VAL_AMT_7
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_8,0),'S000000000.00')  AS CLM_VAL_AMT_8
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_9,0),'S000000000.00')  AS CLM_VAL_AMT_9
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_10,0),'S000000000.00') AS CLM_VAL_AMT_10

	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_11,0),'S000000000.00') AS CLM_VAL_AMT_11
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_12,0),'S000000000.00') AS CLM_VAL_AMT_12
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_13,0),'S000000000.00') AS CLM_VAL_AMT_13
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_14,0),'S000000000.00') AS CLM_VAL_AMT_14
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_15,0),'S000000000.00') AS CLM_VAL_AMT_15
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_16,0),'S000000000.00') AS CLM_VAL_AMT_16
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_17,0),'S000000000.00') AS CLM_VAL_AMT_17
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_18,0),'S000000000.00') AS CLM_VAL_AMT_18
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_19,0),'S000000000.00') AS CLM_VAL_AMT_19
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_20,0),'S000000000.00') AS CLM_VAL_AMT_20

	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_21,0),'S000000000.00') AS CLM_VAL_AMT_21
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_22,0),'S000000000.00') AS CLM_VAL_AMT_22
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_23,0),'S000000000.00') AS CLM_VAL_AMT_23
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_24,0),'S000000000.00') AS CLM_VAL_AMT_24
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_25,0),'S000000000.00') AS CLM_VAL_AMT_25
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_26,0),'S000000000.00') AS CLM_VAL_AMT_26
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_27,0),'S000000000.00') AS CLM_VAL_AMT_27
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_28,0),'S000000000.00') AS CLM_VAL_AMT_28
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_29,0),'S000000000.00') AS CLM_VAL_AMT_29
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_30,0),'S000000000.00') AS CLM_VAL_AMT_30
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_31,0),'S000000000.00') AS CLM_VAL_AMT_31
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_32,0),'S000000000.00') AS CLM_VAL_AMT_32
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_33,0),'S000000000.00') AS CLM_VAL_AMT_33
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_34,0),'S000000000.00') AS CLM_VAL_AMT_34
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_35,0),'S000000000.00') AS CLM_VAL_AMT_35
	,TO_CHAR(COALESCE(VAL.CLM_VAL_AMT_36,0),'S000000000.00') AS CLM_VAL_AMT_36
	
	    
    FROM CLM_INFO C    
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) CDS
    ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_INSTNL CI
	ON  CI.GEO_BENE_SK     = C.GEO_BENE_SK
	AND CI.CLM_DT_SGNTR_SK = C.CLM_DT_SGNTR_SK
	AND CI.CLM_TYPE_CD     = C.CLM_TYPE_CD
	AND CI.CLM_NUM_SK      = C.CLM_NUM_SK
    
	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN CDN
	ON C.GEO_BENE_SK       = CDN.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CDN.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CDN.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CDN.CLM_NUM_SK

    /*
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD_MTRLZD PROD_MT
	ON  C.GEO_BENE_SK         = PROD_MT.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK     = PROD_MT.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD         = PROD_MT.CLM_TYPE_CD
	AND C.CLM_NUM_SK          = PROD_MT.CLM_NUM_SK

    INNER JOIN CLM_PROD_DGNS_INFO PROD
	ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK
*/
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR CPGS
	ON C.CLM_PTCH_GRP_SGNTR_SK = CPGS.CLM_PTCH_GRP_SGNTR_SK  

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR COSG      
	ON C.CLM_OCRNC_SGNTR_SK = COSG.CLM_OCRNC_SGNTR_SK    

    LEFT OUTER JOIN CLM_OCRNC_SGNTR_MBR_INFO COSM	
	ON C.CLM_OCRNC_SGNTR_SK = COSM.CLM_OCRNC_SGNTR_SK 
	
	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_COND_SGNTR CRCS
	ON C.CLM_RLT_COND_SGNTR_SK = CRCS.CLM_RLT_COND_SGNTR_SK   

    LEFT OUTER JOIN CLM_RLT_COND_SGNTR_MBR_INFO CRCSM
	ON CRCSM.CLM_RLT_COND_SGNTR_SK  = C.CLM_RLT_COND_SGNTR_SK
	
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR CROS
	ON C.CLM_RLT_OCRNC_SGNTR_SK = CROS.CLM_RLT_OCRNC_SGNTR_SK 

    LEFT OUTER JOIN CLM_RLT_OCRNC_SGNTR_MBR_INFO CROSM
    ON  C.CLM_RLT_OCRNC_SGNTR_SK  = CROSM.CLM_RLT_OCRNC_SGNTR_SK
	
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR CEGS
	ON C.CLM_EDIT_GRP_SGNTR_SK = CEGS.CLM_EDIT_GRP_SGNTR_SK
	
    -- This one is OK: 1-to-1 relationship with claim.
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR CPGSM
	ON CPGSM.CLM_PTCH_GRP_SGNTR_SK = C.CLM_PTCH_GRP_SGNTR_SK 	
   
    LEFT OUTER JOIN CLM_VAL_INFO VAL
	ON  C.GEO_BENE_SK        = VAL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK    = VAL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD        = VAL.CLM_TYPE_CD
	AND C.CLM_NUM_SK         = VAL.CLM_NUM_SK
    
    -- Zip code should be for what was active at time of claim  
    INNER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP5
    ON C.GEO_BENE_SK = ZIP5.GEO_SK
    
    INNER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_STATE_CD GST
    ON ZIP5.GEO_FIPS_STATE_CD = GST.GEO_FIPS_STATE_CD

    
    /*   
	
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
    ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
    AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
    AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
    AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
    AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_INSTNL CLI
    ON  CL.GEO_BENE_SK     = CLI.GEO_BENE_SK
    AND CL.CLM_DT_SGNTR_SK = CLI.CLM_DT_SGNTR_SK
    AND CL.CLM_TYPE_CD     = CLI.CLM_TYPE_CD
    AND CL.CLM_NUM_SK      = CLI.CLM_NUM_SK
    AND CL.CLM_LINE_NUM    = CLI.CLM_LINE_NUM

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ANSI_SGNTR CAS
	ON CAS.CLM_ANSI_SGNTR_SK  = CLI.CLM_ANSI_SGNTR_SK
	
	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_DCMTN CLDN
	ON CL.GEO_BENE_SK      = CLDN.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK = CLDN.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD     = CLDN.CLM_TYPE_CD
	AND CL.CLM_NUM_SK      = CLDN.CLM_NUM_SK
    AND CL.CLM_LINE_NUM    = CLDN.CLM_LINE_NUM




    */
    
    WHERE C.CLM_TYPE_CD IN ('40')
    AND C.CLM_FINL_ACTN_IND = 'Y'
	-- 2024-01-05 (first Friday of prior year);   2024-03-28 (last Friday of Qtr)
    AND CDS.CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2024-01-05','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
	AND YEAR(C.CLM_THRU_DT) in ('2024','2025')
    
    
    --WHERE CDS.CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2024-01-05','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
;

/*
SELECT CLM_OCRNC_SGNTR_SK, COUNT(*)
--SELECT CLM_OCRNC_SGNTR_SK, COUNT(*)
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR_MBR 
WHERE CLM_OCRNC_SGNTR_SQNC_NUM = 1
GROUP BY CLM_OCRNC_SGNTR_SK
HAVING COUNT(*) > 1
*/
--ORDER BY CLM_RLT_OCRNC_SGNTR_SQNC_NUM
--;

--SELECT GEO_BENE_SK,CLM_DT_SGNTR_SK,CLM_TYPE_CD,CLM_NUM_SK,COUNT(*)
--FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN
--GROUP BY GEO_BENE_SK,CLM_DT_SGNTR_SK,CLM_TYPE_CD,CLM_NUM_SK
--HAVING COUNT(*) > 1;

--CLM_EDIT_GRP_SGNTR_SK
--SELECT *
--FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR
--limit 5;

/*
SELECT CLM_EDIT_GRP_SGNTR_SK, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR_MBR
WHERE CLM_EDIT_GRP_SGNTR_SK = 250916
GROUP BY CLM_EDIT_GRP_SGNTR_SK
HAVING COUNT(*) > 1
--LIMIT 5;
*/

/*
SELECT CLM_PTCH_GRP_SGNTR_SK, COUNT(*)
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR
GROUP BY CLM_PTCH_GRP_SGNTR_SK
HAVING COUNT(*) > 0
;

--SELECT CLM_RLT_OCRNC_SGNTR_SK, CLM_RLT_OCRNC_SGNTR_SQNC_NUM, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR_MBR CROSM
--WHERE CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 0
WHERE CLM_RLT_OCRNC_SGNTR_SK = 5014441269
GROUP BY CLM_RLT_OCRNC_SGNTR_SK

SELECT CLM_PTCH_GRP_SGNTR_SK, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR
GROUP BY CLM_PTCH_GRP_SGNTR_SK 
HAVING COUNT(*) > 1


*/