
-- QTR ONLY SQL

WITH CLM_INFO AS (

    SELECT C.*
        -- What should the default date be in the results-set if its null in database
		,CASE WHEN CDS.CLM_FROM_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_FROM_DT,'YYYYMMDD') END AS CDS_CLM_FROM_DT
		,CASE WHEN CDS.CLM_THRU_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_THRU_DT,'YYYYMMDD') END AS CDS_CLM_THRU_DT
		
		,CASE WHEN CDS.CLM_NCH_WKLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_WKLY_PROC_DT,'YYYYMMDD') END AS CDS_CLM_NCH_WKLY_PROC_DT
		,CASE WHEN CDS.CLM_CWF_ACRTN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CWF_ACRTN_DT,'YYYYMMDD') END         AS CDS_CLM_CWF_ACRTN_DT
		
		,CASE WHEN CDS.CLM_NCH_DLY_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_NCH_DLY_PROC_DT,'YYYYMMDD') END   AS CDS_CLM_NCH_DLY_PROC_DT
		,CASE WHEN CDS.CLM_SUBMSN_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SUBMSN_DT,'YYYYMMDD') END               AS CDS_CLM_SUBMSN_DT
		
		,CASE WHEN CDS.CLM_SCHLD_PMT_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_SCHLD_PMT_DT,'YYYYMMDD') END           AS CDS_CLM_SCHLD_PMT_DT
		,CASE WHEN CDS.CLM_TRNSMSN_TO_CMS_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_TRNSMSN_TO_CMS_DT,'YYYYMMDD') END AS CDS_CLM_TRNSMSN_TO_CMS_DT

		,CASE WHEN CDS.CLM_CMS_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_CMS_PROC_DT,'YYYYMMDD') END AS CDS_CLM_CMS_PROC_DT
		,CASE WHEN CDS.CLM_PRO_PROC_DT IS NULL THEN '00000000' ELSE TO_CHAR(CDS.CLM_PRO_PROC_DT,'YYYYMMDD') END AS CDS_CLM_PRO_PROC_DT

	
    FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) C    
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) CDS
    ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK

    INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
    ON C.BENE_SK = B.BENE_SK
    
    WHERE C.CLM_TYPE_CD IN ('40')
      AND C.CLM_FINL_ACTN_IND = 'Y'
      -- 2024-01-05 (first Friday of prior year);   2024-03-28 (last Friday of Qtr)
      AND CDS.CLM_NCH_WKLY_PROC_DT BETWEEN TO_DATE('2025-01-01','YYYY-MM-DD') AND TO_DATE('2025-03-28','YYYY-MM-DD') 
      AND YEAR(C.CLM_THRU_DT) = '2025'
	  
)

,CLM_PROD_INFO  AS (

	SELECT  
		 C.GEO_BENE_SK
		,C.CLM_DT_SGNTR_SK
		,C.CLM_TYPE_CD
		,C.CLM_NUM_SK
        
 	    ,CASE WHEN PROD.CLM_PROD_TYPE_CD = '~'       THEN NULL ELSE PROD.CLM_PROD_TYPE_CD END       AS CLM_PROD_TYPE_CD 
        ,CASE WHEN PROD.CLM_DGNS_PRCDR_ICD_IND = '~' THEN NULL ELSE PROD.CLM_DGNS_PRCDR_ICD_IND END AS CLM_DGNS_PRCDR_ICD_IND 
		,CASE WHEN PROD.CLM_DGNS_CD = '~'            THEN NULL ELSE PROD.CLM_DGNS_CD END            AS CLM_DGNS_CD 
        ,CASE WHEN PROD.CLM_PRCDR_CD = '~'           THEN NULL ELSE PROD.CLM_PRCDR_CD END           AS CLM_PRCDR_CD
        ,PROD.CLM_PRCDR_PRFRM_DT
 		,PROD.CLM_VAL_SQNC_NUM	

    FROM CLM_INFO C 
	
	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD PROD
	ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK
    AND PROD.CLM_PROD_TYPE_CD = 'D'
        
)

,CLM_PROD_DGNS_INFO  AS (

    SELECT 
        GEO_BENE_SK
        ,CLM_DT_SGNTR_SK
        ,CLM_TYPE_CD
        ,CLM_NUM_SK
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_1
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_2
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_3
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_4
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_5
        ,COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6 THEN CLM_DGNS_PRCDR_ICD_IND ELSE NULL END),' ')  AS  CLM_DGNS_PRCDR_ICD_IND_6
        
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_1
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_2
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_3
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_4
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_5
        ,RPAD(COALESCE(MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6 THEN CLM_DGNS_CD ELSE NULL END),''),7,' ')  AS  CLM_DGNS_CD_6    

        ,MAX(CLM_PRCDR_PRFRM_DT)  AS CLM_PRCDR_PRFRM_DT
    
    FROM CLM_PROD_INFO

    GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK

)

    SELECT COUNT(*)
    
    FROM CLM_INFO C    
    
    --INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR AT(TIMESTAMP => 'Wed, 2 APR 2025 09:20:00 -0700'::timestamp_tz) CDS
    --ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK
    
    INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_INSTNL CI
	ON  CI.GEO_BENE_SK     = C.GEO_BENE_SK
	AND CI.CLM_DT_SGNTR_SK = C.CLM_DT_SGNTR_SK
	AND CI.CLM_TYPE_CD     = C.CLM_TYPE_CD
	AND CI.CLM_NUM_SK      = C.CLM_NUM_SK
    
	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN CDN
	ON C.GEO_BENE_SK       = CDN.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CDN.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CDN.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CDN.CLM_NUM_SK

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD_MTRLZD PROD_MT
	ON  C.GEO_BENE_SK         = PROD_MT.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK     = PROD_MT.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD         = PROD_MT.CLM_TYPE_CD
	AND C.CLM_NUM_SK          = PROD_MT.CLM_NUM_SK

    INNER JOIN CLM_PROD_DGNS_INFO PROD
	ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR CPGS
	ON C.CLM_PTCH_GRP_SGNTR_SK = CPGS.CLM_PTCH_GRP_SGNTR_SK  

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR COSG      
	ON C.CLM_OCRNC_SGNTR_SK = COSG.CLM_OCRNC_SGNTR_SK    

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_COND_SGNTR CRCS
	ON C.CLM_RLT_COND_SGNTR_SK = CRCS.CLM_RLT_COND_SGNTR_SK   

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR CROS
	ON C.CLM_RLT_OCRNC_SGNTR_SK = CROS.CLM_RLT_OCRNC_SGNTR_SK 

    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR CEGS
	ON C.CLM_EDIT_GRP_SGNTR_SK = CEGS.CLM_EDIT_GRP_SGNTR_SK

    -- This one is OK
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR_MBR COSM
	ON C.CLM_OCRNC_SGNTR_SK = COSM.CLM_OCRNC_SGNTR_SK      
	AND COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 1

    -- This one is OK
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR CPGSM
	ON CPGSM.CLM_PTCH_GRP_SGNTR_SK = C.CLM_PTCH_GRP_SGNTR_SK 	
    
    -- 28,481,656 rows returned instead of 28,480,394    
    --LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR_MBR CEGSM
	--ON C.CLM_EDIT_GRP_SGNTR_SK  =  CEGSM.CLM_EDIT_GRP_SGNTR_SK

    -- This one is OK.; SQNC_NUM = 0 returns 31,193,616 instead of 28,480,394
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_COND_SGNTR_MBR CRCSM
	ON CRCSM.CLM_RLT_COND_SGNTR_SK  = C.CLM_RLT_COND_SGNTR_SK
	AND CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 1 
   
    -- returns 50,553,656 instead of 28,480,394  
	--LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR_MBR CROSM
	--ON  C.CLM_RLT_OCRNC_SGNTR_SK  = CROSM.CLM_RLT_OCRNC_SGNTR_SK
	--AND CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 0

    -- This one is OK   
    LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_VAL VAL
	ON  C.GEO_BENE_SK        = VAL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK    = VAL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD        = VAL.CLM_TYPE_CD
	AND C.CLM_NUM_SK         = VAL.CLM_NUM_SK
	AND VAL.CLM_VAL_SQNC_NUM = 1
  

;

/*
SELECT CLM_OCRNC_SGNTR_SK, COUNT(*)
--SELECT CLM_OCRNC_SGNTR_SK, COUNT(*)
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_OCRNC_SGNTR_MBR 
WHERE CLM_OCRNC_SGNTR_SQNC_NUM = 1
GROUP BY CLM_OCRNC_SGNTR_SK
HAVING COUNT(*) > 1
*/
--ORDER BY CLM_RLT_OCRNC_SGNTR_SQNC_NUM
--;

--SELECT GEO_BENE_SK,CLM_DT_SGNTR_SK,CLM_TYPE_CD,CLM_NUM_SK,COUNT(*)
--FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN
--GROUP BY GEO_BENE_SK,CLM_DT_SGNTR_SK,CLM_TYPE_CD,CLM_NUM_SK
--HAVING COUNT(*) > 1;

--CLM_EDIT_GRP_SGNTR_SK
--SELECT *
--FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR
--limit 5;

/*
SELECT CLM_EDIT_GRP_SGNTR_SK, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_EDIT_GRP_SGNTR_MBR
WHERE CLM_EDIT_GRP_SGNTR_SK = 250916
GROUP BY CLM_EDIT_GRP_SGNTR_SK
HAVING COUNT(*) > 1
--LIMIT 5;
*/

/*
SELECT CLM_PTCH_GRP_SGNTR_SK, COUNT(*)
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR
GROUP BY CLM_PTCH_GRP_SGNTR_SK
HAVING COUNT(*) > 0
;

--SELECT CLM_RLT_OCRNC_SGNTR_SK, CLM_RLT_OCRNC_SGNTR_SQNC_NUM, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_RLT_OCRNC_SGNTR_MBR CROSM
--WHERE CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 0
WHERE CLM_RLT_OCRNC_SGNTR_SK = 5014441269
GROUP BY CLM_RLT_OCRNC_SGNTR_SK

SELECT CLM_PTCH_GRP_SGNTR_SK, COUNT(*)
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PTCH_GRP_SGNTR_MBR
GROUP BY CLM_PTCH_GRP_SGNTR_SK 
HAVING COUNT(*) > 1


*/