#!/usr/bin/env python
########################################################################################################
# Name:  DoD_NPI_extract.py
#
# Desc: DoD_NPI Extract - Load DoD finder file into IDR. Extract data from IDR that matches SSNs in FF.
#
# Modified:
#
# Paul Baranoski 2025-09-11 Created python code.
# Paul Baranoski 2026-02-05 Modify SQL to include non-matched rows.
########################################################################################################
import os
import sys
import datetime
from datetime import datetime
import sendEmail

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

# Use Timestamp generated by shell script so logs and output files will have timestamp
TMSTMP=os.getenv('TMSTMP')
ENVNAME=os.getenv('ENVNAME')


# boolean - Python Exception status
bPythonExceptionOccurred=False

########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Method to execute the extract SQL using Timestamp 
########################################################################################################
try:
   snowconvert_helpers.configure_log()
   con = snowconvert_helpers.log_on()   
   snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
   snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}""", con,exit_on_error = True)
   
   #**************************************
   #   Extract NYSPAP Bene Contract data  
   #**************************************   
   snowconvert_helpers.execute_sql_statement(f"""COPY INTO @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_DOD_NPI_STG/DOD_NPI_Ext_{TMSTMP}.txt.gz
                                                FROM (

            WITH MATCHES AS (

                SELECT  
                    FF.SSN_NUM,
                    RPAD(FF.EMP_ID,7,' ') AS EMP_ID,
                    ENMRTN.PRVDR_NPI_NUM, 
                    UPPER(TO_CHAR(ENMRTN.PRVDR_ENMRTN_DT, 'DDMONYYYY')) AS ENMRTN_DT, 
                    CASE  WHEN  ENMRTN.PRVDR_DEACTVTN_DT  IS NULL  THEN  'A' ELSE 'I' END  AS  NPI_STUS_CD        
                FROM IDRC_{ENVNAME}.CMS_DIM_PRVDR_{ENVNAME}.PRVDR_ENMRTN ENMRTN 

                INNER JOIN BIA_{ENVNAME}.CMS_TARGET_XTR_{ENVNAME}.DOD_NPI_YEAR_FF FF
                ON ENMRTN.PRVDR_SSN_NUM = FF.SSN_NUM 

                WHERE PRVDR_ENT_TYPE_CD = '1'  ------individual NPI

                --Latest version of record identified by IDR_LTST_TRANS_FLG ='Y' and IDR_TRANS_OBSLT_TS typically with ‘9999-12-31’
                AND IDR_LTST_TRANS_FLG  = 'Y' 
                AND CURRENT_DATE < CAST(IDR_TRANS_OBSLT_TS AS DATE)      
                

            )

            SELECT RPAD(FF.EMP_ID,7,' ') AS EMP_ID  
                  ,RPAD(COALESCE(MATCH.PRVDR_NPI_NUM,''),10) AS PRVDR_NPI_NUM
                  ,RPAD(COALESCE(MATCH.ENMRTN_DT,''),9)      AS ENMRTN_DT 
                  ,RPAD(COALESCE(NPI_STUS_CD,''),1)          AS NPI_STUS_CD	    	   
            FROM MATCHES MATCH

            RIGHT OUTER JOIN BIA_{ENVNAME}.CMS_TARGET_XTR_{ENVNAME}.DOD_NPI_YEAR_FF FF
            ON MATCH.SSN_NUM = FF.SSN_NUM 

            ORDER BY FF.EMP_ID

 
 )
                        FILE_FORMAT = (TYPE = CSV field_delimiter = none  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
                        SINGLE = TRUE  max_file_size=5368709120  """, con, exit_on_error=True)


   
   #**************************************
   # End Application
   #**************************************    
   snowconvert_helpers.quit_application()
   
except Exception as e:
   print(e)
   
   # Let shell script know that python code failed.
   bPythonExceptionOccurred=True   
   
finally:
   if con is not None:
      con.close()

   # Let shell script know that python code failed.      
   if bPythonExceptionOccurred == True:
      sys.exit(12) 
   else:   
      snowconvert_helpers.quit_application()

