WITH FF_NPI_NUMS AS (
	 
	SELECT '1831282896' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1497729313' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1518296839' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1689720666' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1487602900' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1396772737' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1801883533' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1841375284' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1730252289' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1841322104' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1043292477' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1508915216' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1578545513' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1841252145' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1922174234' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1831132026' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1215000757' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1922099910' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1366620833' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1467431320' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1023183001' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1255308417' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1952444846' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1437198033' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1104042357' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1336116789' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1881782373' AS NPI_NUM FROM DUAL
	 UNION
	SELECT '1053360420' AS NPI_NUM FROM DUAL

)

	SELECT 
    
			'START' AS HDR

			,CASE WHEN C.CLM_PTNT_BIRTH_DT IS NULL         THEN '0000'
				   WHEN C.CLM_PTNT_BIRTH_DT = '0001-01-01' THEN '0000'
				   WHEN C.CLM_PTNT_BIRTH_DT = '1000-01-01' THEN '0000'
				   ELSE to_char(C.CLM_PTNT_BIRTH_DT,'YYYY') 
			 END            AS  CLM_PTNT_BIRTH_DT

			-- is this field in MF file '01' or ' 1' or '1 '
			,TO_CHAR(CLR.CLM_LINE_RX_FILL_NUM,'FM00')       AS  CLM_LINE_RX_FILL_NUM

			,CASE WHEN C.CLM_PD_DT         IS NULL         THEN '00000000'
				  WHEN C.CLM_PD_DT        = '0001-01-01'   THEN '00000000'
				  WHEN C.CLM_PD_DT        = '1000-01-01'   THEN '00000000'
				  ELSE TO_CHAR(C.CLM_PD_DT,'YYYYMMDD')
			 END            AS  CLM_PD_DT
	   

			,RPAD(TRIM(C.CLM_PRSBNG_PRVDR_GNRC_ID_NUM),35,' ')  AS  PRTY_PRVDR_PHYSN_PRSCRB_ID	

			,RPAD(C.PRVDR_PRSBNG_ID_QLFYR_CD,2,' ')          AS  PRVDR_PRSBNG_ID_QLFYR_CD
			,RPAD(TRIM(C.CLM_SRVC_PRVDR_GNRC_ID_NUM),15,' ') AS  CLM_SRVC_PRVDR_GNRC_ID_NUM			

			,RPAD(C.PRVDR_SRVC_ID_QLFYR_CD,2,' ')            AS  PRTY_GNRC_ID_QLFYR
			
			,RPAD(COALESCE(C.CLM_OTHR_PRVDR_GNRC_ID_NUM,' '),15,' ') AS CLM_OTHR_PRVDR_GNRC_ID_NUM

			,RPAD(COALESCE(C.PRVDR_OTHR_ID_QLFYR_CD,' '),2,' ')      AS  PRVDR_OTHR_ID_QLFYR_CD

			,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')  AS CLM_FROM_DT 
			,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')  AS CLM_THRU_DT  

			,TO_CHAR(CLR.CLM_LINE_DAYS_SUPLY_QTY,'FM000')    AS  CLM_LINE_DAYS_SUPLY_QTY
			,RPAD(CLR.CLM_DSPNSNG_STUS_CD,1,' ')             AS  CLM_DSPNSNG_STUS_CD

			,RPAD(CL.CLM_LINE_NDC_CD,11,' ')                 AS  PROD_NDC_CODE
			,TO_CHAR(CL.CLM_LINE_NDC_QTY,'S000000000000000.000')    AS  CLM_LINE_NDC_QTY

			--,BENE_ID	?
			-- ##BLBTN PRVDR
			--,RPAD(REPLACE(PRVDR.PRVDR_NCPDP_ID,'~',''),5,' ')   AS  PRVDR_NCPDP_ID 

			--,PRVDR_NCPDP_LGL_BUSNS_NAME
			--,PRVDR_NCPDP_LINE_1_ADR
			--,PRVDR_NCPDP_LINE_2_ADR

			-- PRVDR or Pharmacy
--			,RPAD(COALESCE(PRVDR.GEO_PRVDR_PRCTC_SK,' '),5,' ')     AS CLM_BLG_PRVDR_ZIP5_CD			
			--,RPAD(COALESCE(FIPS.GEO_USPS_STATE_CD,''),2,' ') AS DRVD_PSTL_STATE_CD	

            -- No Race Cd found for Part D Claims    
			--,RPAD(BENE.BENE_RACE_CD,2,' ')       AS BENE_RACE_CD
	
			--,COALESCE(BENE_RACE_SRC_CD,' ')  AS BENE_RACE_SRC_CD 
			--PRVDR_NCPDP_DSPNSR_TYPE_CD AS PRVDR_NCPDP_DSPNSR_TYPE_CD			
			--PRVDR_NCPDP_TXNMY_CD 
			
			,'END' AS END_MARKER
 

	FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR CDS
	ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK
	  --AND CDS.META_SRC_SK = 1

	INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
    ON C.BENE_SK = B.BENE_SK
	   
	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
	ON C.CLM_NUM_SK       = CL.CLM_NUM_SK
	AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
	AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
	AND C.GEO_BENE_SK     = CL.GEO_BENE_SK
	AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_RX CLR
	ON CL.CLM_NUM_SK       = CLR.CLM_NUM_SK
	AND CL.CLM_TYPE_CD     = CLR.CLM_TYPE_CD
	AND CL.CLM_DT_SGNTR_SK = CLR.CLM_DT_SGNTR_SK
	AND CL.GEO_BENE_SK     = CLR.GEO_BENE_SK
	AND CL.CLM_LINE_NUM    = CLR.CLM_LINE_NUM



	--INNER JOIN IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR  PRVDR
	--ON C.CLM_BLG_PRVDR_NPI_NUM = PRVDR.PRVDR_NPI_NUM
			
	--LEFT OUTER JOIN IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR_NCPDP NCPDP
	--ON PRVDR.PRVDR_NCPDP_ID = NCPDP.PRVDR_NCPDP_ID   
	   
	   
	WHERE C.CLM_TYPE_CD IN (1,2,4)
    --WHERE C.CLM_TYPE_CD BETWEEN 1 AND 64
	  --AND CDS.META_SRC_SK = 1
	  --AND C.META_SRC_SK = 1
	--AND CDS.CLM_EDW_PROC_DT BETWEEN TO_DATE('2020-01-01','YYYY-MM-DD') AND TO_DATE('2020-12-31','YYYY-MM-DD') 
    AND C.CLM_FROM_DT BETWEEN TO_DATE('2013-01-01','YYYY-MM-DD') AND TO_DATE('2020-12-31','YYYY-MM-DD')

	AND (
		   C.CLM_ATNDG_PRVDR_NPI_NUM    IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.PRVDR_ATNDG_PRVDR_NPI_NUM  IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.CLM_BLG_PRVDR_NPI_NUM      IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.PRVDR_BLG_PRVDR_NPI_NUM    IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.CLM_OPRTG_PRVDR_NPI_NUM    IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.PRVDR_OPRTG_PRVDR_NPI_NUM  IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.CLM_OTHR_PRVDR_NPI_NUM     IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.PRVDR_OTHR_PRVDR_NPI_NUM   IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.CLM_FAC_PRVDR_NPI_NUM      IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR CL.PRVDR_FAC_PRVDR_NPI_NUM   IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.CLM_SRVC_PRVDR_NPI_NUM     IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.PRVDR_SRVC_PRVDR_NPI_NUM   IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.PRVDR_RFRG_PRVDR_NPI_NUM   IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR C.CLM_RFRG_PRVDR_NPI_NUM     IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR C.PRVDR_CPO_FAC_NPI_NUM      IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR CL.CLM_RNDRG_PRVDR_NPI_NUM    IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR CL.PRVDR_RNDRNG_PRVDR_NPI_NUM IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )

		OR CL.CLM_RNDRG_PRVDR_GRP_NPI_NUM     IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
		OR CL.PRVDR_RNDRNG_PRVDR_GRP_NPI_NUM  IN (SELECT FF_NPI_NUMS.NPI_NUM FROM FF_NPI_NUMS )
	 )                    	
     