-- Modify SQL to get BENE_BRTH_DT from BENE table instead of CLM table.

--COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ103b_WALMART_PTD_Y2014_20251002.120000.txt.gz FROM (


SELECT 

	'START' AS HDR

	,CASE WHEN BENE.BENE_BRTH_DT IS NULL    THEN '0000'
	  WHEN BENE.BENE_BRTH_DT = '0001-01-01' THEN '0000'
	  WHEN BENE.BENE_BRTH_DT = '1000-01-01' THEN '0000'
	  ELSE TO_CHAR(BENE.BENE_BRTH_DT,'YYYY') 
	END   AS PTNT_DATE_OF_BIRTH

    -- Format 9(9)
    ,TO_CHAR(CLR.CLM_LINE_RX_FILL_NUM,'FM000000000')       AS  CLM_LINE_RX_FILL_NUM

    ,CASE WHEN C.CLM_PD_DT         IS NULL         THEN '00000000'
          WHEN C.CLM_PD_DT        = '0001-01-01'   THEN '00000000'
          WHEN C.CLM_PD_DT        = '1000-01-01'   THEN '00000000'
          ELSE TO_CHAR(C.CLM_PD_DT,'YYYYMMDD')
     END            AS  CLM_PD_DT


    ,RPAD(TRIM(C.CLM_PRSBNG_PRVDR_GNRC_ID_NUM),35,' ')  AS  PRTY_PRVDR_PHYSN_PRSCRB_ID	

    ,RPAD(C.PRVDR_PRSBNG_ID_QLFYR_CD,2,' ')          AS  PRVDR_PRSBNG_ID_QLFYR_CD
    ,RPAD(TRIM(C.CLM_SRVC_PRVDR_GNRC_ID_NUM),20,' ') AS  CLM_SRVC_PRVDR_GNRC_ID_NUM			

    ,RPAD(C.PRVDR_SRVC_ID_QLFYR_CD,2,' ')            AS  PRTY_GNRC_ID_QLFYR
    
    ,RPAD(COALESCE(C.CLM_OTHR_PRVDR_GNRC_ID_NUM,' '),20,' ') AS CLM_OTHR_PRVDR_GNRC_ID_NUM

    ,RPAD(COALESCE(C.PRVDR_OTHR_ID_QLFYR_CD,' '),2,' ')      AS  PRVDR_OTHR_ID_QLFYR_CD

    ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')  AS CLM_FROM_DT 
    ,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')  AS CLM_THRU_DT  

    ,TO_CHAR(CLR.CLM_LINE_DAYS_SUPLY_QTY,'FM000000000')     AS  CLM_LINE_DAYS_SUPLY_QTY
    ,RPAD(CLR.CLM_DSPNSNG_STUS_CD,1,' ')                    AS  CLM_DSPNSNG_STUS_CD

    ,RPAD(CL.CLM_LINE_NDC_CD,11,' ')                        AS  PROD_NDC_CODE
	-- Format S9(15).999
    ,TO_CHAR(CL.CLM_LINE_NDC_QTY,'S000000000000000.000')    AS  CLM_LINE_NDC_QTY

	,TO_CHAR(DENSE_RANK() OVER (ORDER BY BENE.BENE_SK),'FM000000000') AS DI_BENE_SK
   
    ,RPAD(REPLACE(P.PRVDR_NCPDP_ID,'~',''),5,' ')           AS  PRVDR_NCPDP_ID 
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LGL_BUSNS_NAME,''),60,' ') AS  PRVDR_NCPDP_LGL_BUSNS_NAME  
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LINE_1_ADR,''),55,' ')     AS  PRVDR_NCPDP_LINE_1_ADR    
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LINE_2_ADR,''),55,' ')     AS  PRVDR_NCPDP_LINE_2_ADR 

	,TO_CHAR(COALESCE(NPI.GEO_PRVDR_PRCTC_SK,0),'FM00000')  AS  GEO_PRVDR_PRCTC_SK

    ,RPAD(COALESCE(ST1.GEO_USPS_STATE_CD,''),2,' ')         AS  GEO_USPS_STATE_CD  
	
    ,RPAD(REPLACE(COALESCE(BENE.BENE_RACE_CD,''),'~',''),2,' ')           AS  BENE_RACE_CD
    ,RPAD(REPLACE(COALESCE(BENE.BENE_RACE_SRC_CD,' '),'~',''),1,' ')      AS  BENE_RACE_SRC_CD 

    ,RPAD(COALESCE(TXNMY.PRVDR_NCPDP_DSPNSR_TYPE_CD,''),2,' ')  AS  PRVDR_NCPDP_DSPNSR_TYPE_CD  
    ,RPAD(COALESCE(TXNMY.PRVDR_NCPDP_TXNMY_CD,''),10,' ')       AS  PRVDR_NCPDP_TXNMY_CD     
    
    ,'END' AS END_MARKER

--68,913,208
--SELECT COUNT(*) 

FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM C 

--INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
--ON C.BENE_SK = B.BENE_SK

INNER JOIN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_BENE BENE
ON C.BENE_SK = BENE.BENE_SK
				   
INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
ON  C.GEO_BENE_SK      = CL.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CL.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CL.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CL.CLM_NUM_SK
AND C.CLM_FROM_DT      = CL.CLM_FROM_DT

-- Join on first 9 bytes of NDC high-level code
INNER JOIN BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NDC_FF NDC_FF
ON SUBSTR(NDC_FF.NDC_CD,1,9) = SUBSTR(CL.CLM_LINE_NDC_CD,1,9)


INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_RX CLR
ON  C.GEO_BENE_SK      = CLR.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CLR.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CLR.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CLR.CLM_NUM_SK

INNER JOIN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP P
ON 
    CASE C.PRVDR_SRVC_ID_QLFYR_CD
         WHEN  '07' THEN C.CLM_SRVC_PRVDR_GNRC_ID_NUM
         WHEN  '01' THEN
                CASE C.PRVDR_OTHR_ID_QLFYR_CD
                     WHEN  '07' THEN C.CLM_OTHR_PRVDR_GNRC_ID_NUM
                      ELSE '         '
                 END  
          ELSE '         '
  END
      --PRVDR_NCPDP_ID_FNL
      = P.PRVDR_NCPDP_ID
    
INNER JOIN IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR NPI
ON 
    CASE C.PRVDR_SRVC_ID_QLFYR_CD
     WHEN  '01' THEN C.CLM_SRVC_PRVDR_GNRC_ID_NUM
     WHEN  '07' THEN
            CASE C.PRVDR_OTHR_ID_QLFYR_CD
                 WHEN  '01' THEN C.CLM_OTHR_PRVDR_GNRC_ID_NUM
                  ELSE '         '
             END  
      ELSE '         '
    END
      --PRVDR_NPI_FNL 
      = NPI.PRVDR_NPI_NUM

INNER JOIN BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NPI_FF NPI_FF
ON NPI.PRVDR_NPI_NUM = NPI_FF.NPI_NUM

LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP1
ON NPI.GEO_PRVDR_PRCTC_SK = ZIP1.GEO_SK

LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD FIPS1
ON FIPS1.GEO_FIPS_CNTY_CD   = ZIP1.GEO_FIPS_CNTY_CD
AND FIPS1.GEO_FIPS_STATE_CD = ZIP1.GEO_FIPS_STATE_CD 
 
LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_STATE_CD ST1
ON FIPS1.GEO_FIPS_STATE_CD = ST1.GEO_FIPS_STATE_CD
  
LEFT OUTER JOIN     IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR_NCPDP_DSPNSR TXNMY
ON TXNMY.PRVDR_NCPDP_ID = P.PRVDR_NCPDP_ID

WHERE C.CLM_TYPE_CD in (1,2,4) 
-- June 26, 2013 to December 22, 2020
AND C.CLM_FROM_DT BETWEEN TO_DATE('2013-06-26','YYYY-MM-DD') AND TO_DATE('2020-12-22','YYYY-MM-DD')
AND C.CLM_FINL_ACTN_IND = 'Y' 
AND ST1.GEO_USPS_STATE_CD IN ('AZ','IL','LA','MI','MN','NJ','NC','OH','OR','TN','UT','WI')

ORDER BY bene.Bene_sk

--)

	--	   FILE_FORMAT = (TYPE = CSV field_delimiter = "|"  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
		--	SINGLE=TRUE  max_file_size=5368709120 


--*******************************************************************************************************
/*
create or replace TABLE BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NPI_FF (
	NPI_NUM VARCHAR(10) NOT NULL,
	ENUM_DT DATE,
	PRVDR_ORG_NAME VARCHAR(40),
    STREET_ADDR VARCHAR(40),
    CITY      VARCHAR(30),
    ST_ABREV  VARCHAR(2),
    ZIP9_CD VARCHAR(9),
    PHONE_NUM VARCHAR(10),
    NPI_DEACTIVE_DT DATE
);

COPY INTO BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NPI_FF
	(NPI_NUM, ENUM_DT, PRVDR_ORG_NAME, STREET_ADDR, CITY, ST_ABREV, ZIP9_CD, PHONE_NUM, NPI_DEACTIVE_DT )
	FROM (SELECT f.$1 AS NPI_NUM, TO_DATE(f.$2,'MM/DD/YYYY') AS ENUM_DT, f.$3 AS PRVDR_ORG_NAME,
                 f.$4 AS  STREET_ADDR, f.$5 AS CITY, f.$6 AS ST_ABREV, f.$7 AS ZIP9_CD,
                 f.$8 AS  PHONE_NUM, f.$9 AS NPI_DEACTIVE_DT
          FROM @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_FF_STG/DOJ_REQ103b_NPI_LIST.csv f)
	      FORCE=TRUE FILE_FORMAT = (TYPE = CSV  FIELD_DELIMITER=','  SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY = '"'); 


create or replace TABLE BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NDC_FF (
	NDC_CD VARCHAR(11),
	DRUG_CLASS VARCHAR(20),
	DRUG_BASE VARCHAR(20)
);

COPY INTO BIA_PRD.CMS_TARGET_XTR_PRD.REQ103b_WALMART_NDC_FF
	(NDC_CD, DRUG_CLASS, DRUG_BASE)
	FROM (SELECT f.$1 AS NDC_CD, f.$2 AS DRUG_CLASS, f.$3 AS DRUG_BASE  
          FROM @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_FF_STG/DOJ_REQ103b_NDC_LIST.csv f)
	      FORCE=TRUE FILE_FORMAT = (TYPE = CSV  FIELD_DELIMITER=',' SKIP_HEADER=1); 

*/
