--SELECT COUNT(*) FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF WHERE NPI_NUM = '1528225588';

COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_TOUHY_MICHAEL_CARTER_MA_2016.txt.gz
 FROM (

    WITH CLM_ENC_CLMS AS (

        SELECT  DISTINCT
 		         C.GEO_BENE_SK
                ,C.CLM_DT_SGNTR_SK
                ,C.CLM_TYPE_CD
                ,C.CLM_NUM_SK
                ,C.CLM_RLT_COND_SGNTR_SK
                ,C.CLM_RLT_OCRNC_SGNTR_SK
                ,C.CLM_OCRNC_SGNTR_SK
              
        FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C

        INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ENCTR CE
        ON  C.GEO_BENE_SK     = CE.GEO_BENE_SK
        AND C.CLM_DT_SGNTR_SK = CE.CLM_DT_SGNTR_SK
        AND C.CLM_TYPE_CD     = CE.CLM_TYPE_CD
        AND C.CLM_NUM_SK      = CE.CLM_NUM_SK

		-- Claim Line joins
		INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
		ON  C.GEO_BENE_SK      = CL.GEO_BENE_SK
		AND C.CLM_DT_SGNTR_SK  = CL.CLM_DT_SGNTR_SK
		AND C.CLM_TYPE_CD      = CL.CLM_TYPE_CD
		AND C.CLM_NUM_SK       = CL.CLM_NUM_SK
		AND C.CLM_FROM_DT      = CL.CLM_FROM_DT
	
		WHERE C.CLM_TYPE_CD IN (4011,4012,4013,4018,4041)
        AND   C.CLM_FINL_ACTN_IND = 'Y'
		AND   CL.CLM_LINE_FINL_ACTN_IND = 'Y'
        --AND   CE.CLM_EDPS_STUS_CD = 'A'
		AND   C.CLM_FROM_DT BETWEEN to_date('2016-01-01','YYYY-MM-DD') AND to_date('2016-12-31','YYYY-MM-DD')
		
		AND (
		         C.CLM_ATNDG_PRVDR_NPI_NUM  IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR C.CLM_BLG_PRVDR_NPI_NUM    IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR C.CLM_OPRTG_PRVDR_NPI_NUM  IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR C.CLM_OTHR_PRVDR_NPI_NUM   IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR C.CLM_RNDRG_PRVDR_NPI_NUM  IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR C.CLM_RFRG_PRVDR_NPI_NUM   IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			  OR CL.CLM_RNDRG_PRVDR_NPI_NUM IN (SELECT FF.NPI_NUM FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_TOUHY_NPI_FF FF )
			)  

    )

   ,TMP_ADR AS (

			SELECT
				 C.GEO_BENE_SK
				,C.CLM_DT_SGNTR_SK
				,C.CLM_TYPE_CD
				
				,C.CLM_NUM_SK

				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD = 'P' AND CA.CLM_ADR_SBTYP_CD = 'BP' 
						  THEN CA.CLM_ADR_LINE_1_TXT ELSE NULL END)          AS CLM_BPRVDR_ADR_LINE_1_TXT
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'  
								   THEN CA.CLM_ADR_LINE_2_TXT ELSE NULL END) AS CLM_BPRVDR_ADR_LINE_2_TXT
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD = 'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
								   THEN CA.CLM_ADR_LINE_3_TXT ELSE NULL END) AS CLM_BPRVDR_ADR_LINE_3_TXT
								   
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
								   THEN CA.CLM_CITY_NAME ELSE NULL END)      AS CLM_BPRVDR_CITY_NAME
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
								   THEN	CA.CLM_USPS_STATE_CD ELSE NULL END)  AS CLM_BPRVDR_USPS_STATE_CD
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
								   THEN CA.GEO_ZIP5_CD ELSE NULL END)        AS BPRVDR_GEO_ZIP5_CD
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
								   THEN REPLACE(CA.GEO_ZIP4_CD,'~',' ') ELSE NULL END)    AS BPRVDR_GEO_ZIP4_CD

				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN CA.CLM_ADR_LINE_1_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_1_TXT
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN CA.CLM_ADR_LINE_2_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_2_TXT
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'    
								   THEN CA.CLM_ADR_LINE_3_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_3_TXT
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN CA.CLM_CITY_NAME ELSE NULL END)       AS CLM_SUBSCR_CITY_NAME
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN CA.CLM_USPS_STATE_CD ELSE NULL END)   AS CLM_SUBSCR_USPS_STATE_CD
								   
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN CA.GEO_ZIP5_CD ELSE NULL END)         AS SUBSCR_GEO_ZIP5_CD
				,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
								   THEN REPLACE(CA.GEO_ZIP4_CD,'~',' ') ELSE NULL END)         AS SUBSCR_GEO_ZIP4_CD


			FROM CLM_ENC_CLMS C                             

			INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ADR CA
			ON  C.GEO_BENE_SK     = CA.GEO_BENE_SK
			AND C.CLM_DT_SGNTR_SK = CA.CLM_DT_SGNTR_SK
			AND C.CLM_TYPE_CD     = CA.CLM_TYPE_CD
			AND C.CLM_NUM_SK      = CA.CLM_NUM_SK
			AND CA.CLM_ADR_SQNC_NUM = 1         
			 
			GROUP BY C.GEO_BENE_SK, C.CLM_DT_SGNTR_SK, C.CLM_TYPE_CD, C.CLM_NUM_SK  
	 

)                 

--,CLM_BENE_INFO AS (

               
  SELECT 
	   'START'
	  ,LPAD(CL.CLM_TYPE_CD,5,'0')          AS CLM_TYPE_CD
	  ,RPAD(COALESCE(C.CLM_HIC_NUM,' '),12,' ')  AS BENE_HICN
	  ,RPAD(REPLACE(COALESCE(GFCC.GEO_SSA_STATE_CD,''),'~',''),2,' ')  AS SSA_STATE_CD
	  ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
	  ,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')          AS CLM_THRU_DT
	  ,CASE WHEN CED.CLM_EDPS_CREATN_DT IS NULL THEN '10000101' ELSE                        to_char(CED.CLM_EDPS_CREATN_DT,'YYYYMMDD') END AS CLM_EDPS_CREATN_DT
	  ,RPAD(C.CLM_CNTL_NUM,40,' ')                   AS CLAIM_CONTROL_NBR
	  ,RPAD(COALESCE(C.CLM_ORIG_CNTL_NUM,''),40,' ') AS ORIG_CLAIM_CONTROL_NBR
	  ,CASE WHEN CED.CLM_EDPS_LD_DT IS NULL THEN '10000101' ELSE to_char(CED.CLM_EDPS_LD_DT,'YYYYMMDD') END AS CLM_EDPS_LD_DT
	  ,RPAD(C.CLM_BILL_FAC_TYPE_CD,1,' ') AS CLM_BILL_FAC_TYPE_CD
	  ,RPAD(C.CLM_BILL_CLSFCTN_CD,1,' ')  AS CLM_BILL_CLSFCTN_CD
	  ,RPAD(C.CLM_BILL_FREQ_CD,1,' ')     AS CLM_BILL_FREQ_CD
	  ,RPAD(CASE WHEN GFCC.GEO_SSA_CNTY_CD = '~' THEN ' ' ELSE COALESCE(GFCC.GEO_SSA_CNTY_CD,' ')                           END,3,' ')  AS  SSA_CNTY_CD
	  ,CASE WHEN DT.CLM_SUBMSN_DT IS NULL THEN '10000101' ELSE to_char(DT.CLM_SUBMSN_DT,'YYYYMMDD') END       AS CLM_SUBMSN_DT
	  ,RPAD(CE.CLM_CNTRCT_NUM,5,' ') AS  CLM_CNTRCT_NUM
	  ,RPAD(CASE WHEN ZIP5.GEO_ZIP5_CD ='~' THEN ' ' ELSE COALESCE(ZIP5.GEO_ZIP5_CD,' ') END,5,' ')  ||
	   RPAD(CASE WHEN ZIP9.GEO_ZIP4_CD ='~' THEN ' ' ELSE COALESCE(ZIP9.GEO_ZIP4_CD,' ') END,4,' ')	AS GEO_ZIP9_CD
	  ,RPAD(CASE WHEN C.BENE_SEX_CD   = '~' THEN ' '  ELSE C.BENE_SEX_CD END,1,' ')   AS BENE_SEX_CD 
	  ,RPAD(CASE WHEN COALESCE(BF.BENE_RACE_CD,' ') = '~' THEN ' '  ELSE COALESCE(BF.BENE_RACE_CD,' ') END,2,' ') AS BENE_RACE_CD
	  ,CASE WHEN C.CLM_PTNT_BIRTH_DT IS NULL THEN REPEAT(8,' ') ELSE to_char(C.CLM_PTNT_BIRTH_DT,'YYYYMMDD') END AS CLM_PTNT_BIRTH_DT
	  ,RPAD(COALESCE(BF.BENE_MDCR_STUS_CD,' '),2,' ')   AS BENE_MDCR_STUS_CD
	  ,RPAD(CDN.CLM_LAST_NAME,60,' ')     AS CLM_LAST_NAME
	  ,RPAD(CDN.CLM_1ST_NAME,35,' ')      AS CLM_1ST_NAME
	  ,RPAD(COALESCE(CDN.CLM_INTL_MDL_NAME,' '),1,' ') AS CLM_INTL_MDL_NAME
	  ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND
	  ,RPAD(CASE WHEN PROD_MT.CLM_PRNCPL_DGNS_CD = '~'     THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRNCPL_DGNS_CD,' ') END,7,' ')     AS CLM_PRNCPL_DGNS_CD
	  ,TO_CHAR(CASE WHEN CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P' THEN CEOPD.CLM_ENCTR_OTHR_PYR_PD_AMT ELSE 0 END,'0000000000000.00S') 
AS  CLM_ENCTR_OTHR_PYR_PD_AMT

	 ,RPAD(CASE WHEN C.CLM_BLG_PRVDR_NPI_NUM = '~'      THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_NPI_NUM,' ')     END,10,' ')  AS  CLM_BLG_PRVDR_NPI_NUM 
	 ,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_NPI_NUM = '~'    THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_NPI_NUM,' ')   END,10,' ')  AS  CLM_ATNDG_PRVDR_NPI_NUM 
	 ,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_LAST_NAME = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_ATNDG_PRVDR_LAST_NAME 
	 ,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_ATNDG_PRVDR_1ST_NAME 
	 ,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_ATNDG_PRVDR_MDL_NAME 
	 ,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_NPI_NUM  = '~'   THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_NPI_NUM,' ')   END,10,' ')  AS  CLM_OPRTG_PRVDR_NPI_NUM 
	 ,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_LAST_NAME  = '~' THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_OPRTG_PRVDR_LAST_NAME 
	 ,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_OPRTG_PRVDR_1ST_NAME 
	 ,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_OPRTG_PRVDR_MDL_NAME 
	 ,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_NPI_NUM  = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_NPI_NUM,' ')    END,10,' ')  AS  CLM_OTHR_PRVDR_NPI_NUM 
	 ,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_LAST_NAME = '~'   THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_LAST_NAME,' ')  END,60,' ')  AS  CLM_OTHR_PRVDR_LAST_NAME 
	 ,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_1ST_NAME = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_1ST_NAME,' ')   END,35,' ')  AS  CLM_OTHR_PRVDR_1ST_NAME 
	 ,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_MDL_NAME = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_MDL_NAME,' ')   END,25,' ')  AS  CLM_OTHR_PRVDR_MDL_NAME
	 ,RPAD(CDN.CLM_PTNT_CNTL_NUM,80,' ')      AS CLM_PTNT_CNTL_NUM
	,RPAD(COALESCE(CDN.CLM_PTNT_MDCL_REC_NUM,' '),80,' ')  AS CLM_PTNT_MDCL_REC_NUM

    ,RPAD(CI.BENE_PTNT_STUS_CD,2,' ')        AS BENE_PTNT_STUS_CD 

	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_E_CD          = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_E_CD,' ') END,7,' ')          AS CLM_DGNS_E_CD 

	-- WARNING!! FORMAT '9(13)V9(2)S' (CHAR (15)
	,TO_CHAR(COALESCE(C.CLM_SBMT_CHRG_AMT,0),'0000000000000.00S')  AS CLM_SBMT_CHRG_AMT 
	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_ZIP5_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_ZIP5_CD,' ') END,5,' ')  ||
         RPAD(CASE WHEN C.CLM_BLG_PRVDR_ZIP4_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_ZIP4_CD,' ') END,4,' ') AS CLM_BLG_PRVDR_ZIP9_D		

	,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_NPI_NUM,' ') END,10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM

	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_LAST_NAME,' '),60,' ') AS CLM_RNDRG_PRVDR_LAST_NAME
	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_1ST_NAME,' '),35,' ')  AS CLM_RNDRG_PRVDR_1ST_NAME
	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_MDL_NAME,' '),25,' ')  AS CLM_RNDRG_PRVDR_MDL_NAME	

	,TO_CHAR(PROD_MT.CLM_DGNS_TOT_OCRNC_CNT,'FM00')   AS CLM_DGNS_TOT_OCRNC_CNT
	,CASE WHEN DT.CLM_DSCHRG_DT IS NULL THEN '10000101' ELSE TO_CHAR(DT.CLM_DSCHRG_DT,'YYYYMMDD') END  AS CLM_DSCHRG_DT
	,CASE WHEN DT.CLM_ACTV_CARE_FROM_DT IS NULL THEN '10000101' ELSE TO_CHAR(DT.CLM_ACTV_CARE_FROM_DT,'YYYYMMDD') END  AS CLM_ACTV_CARE_FROM_DT
	

	,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_NPI_NUM,' ') END,10,' ') AS CLM_RFRG_PRVDR_NPI_NUM
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_LAST_NAME,' '),60,' ') AS CLM_RFRG_PRVDR_LAST_NAME
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_1ST_NAME,' '),35,' ')  AS CLM_RFRG_PRVDR_1ST_NAME
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_MDL_NAME,' '),25,' ')  AS CLM_RFRG_PRVDR_MDL_NAME	



	--- DGNS_R_CD  **********
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ')   AS CLM_DGNS_PRCDR_ICD_IND
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD   = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD,' ')   END,7,' ') AS CLM_DGNS_RSN_FOR_VISIT_CD 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_2_RSN_FOR_VISIT_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_3_RSN_FOR_VISIT_CD 
 
	

	--- MCO_CNTRCT_NUM**********
	,RPAD(CASE WHEN CDN.CLM_MCO_1ST_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_1ST_CNTRCT_NUM
	,RPAD(CASE WHEN CDN.CLM_MCO_2ND_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_2ND_CNTRCT_NUM
	,RPAD(CASE WHEN CDN.CLM_MCO_1ST_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_1ST_HLTH_PLAN_ID
	,RPAD(CASE WHEN CDN.CLM_MCO_2ND_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_2ND_HLTH_PLAN_ID

	--- CLM-DGNS-D  ************
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_1_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_1_CD,' ')  END,7,' ')  AS CLM_DGNS_1_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_CD,' ')  END,7,' ')  AS CLM_DGNS_2_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_CD,' ')  END,7,' ')  AS CLM_DGNS_3_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_4_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_4_CD,' ')  END,7,' ')  AS CLM_DGNS_4_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_5_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_5_CD,' ')  END,7,' ')  AS CLM_DGNS_5_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_6_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_6_CD,' ')  END,7,' ')  AS CLM_DGNS_6_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_7_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_7_CD,' ')  END,7,' ')  AS CLM_DGNS_7_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_8_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_8_CD,' ')  END,7,' ')  AS CLM_DGNS_8_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_9_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_9_CD,' ')  END,7,' ')  AS CLM_DGNS_9_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_10_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_10_CD,' ') END,7,' ')  AS CLM_DGNS_10_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_11_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_11_CD,' ') END,7,' ')  AS CLM_DGNS_11_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_12_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_12_CD,' ') END,7,' ')  AS CLM_DGNS_12_CD
    ,TO_CHAR(CL.CLM_LINE_NUM,'FM0000000000')       AS CLM_LINE_NUM
    ,RPAD(CL.CLM_LINE_REV_CTR_CD,10,' ') as CLM_LINE_REV_CTR_CD
	,CASE WHEN CL.CLM_LINE_FROM_DT IS NULL THEN '10000101' ELSE TO_CHAR(CL.CLM_LINE_FROM_DT,'YYYYMMDD') END  AS  CLM_LINE_FROM_DT

	,RPAD(CASE WHEN CL.CLM_LINE_HCPCS_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_LINE_HCPCS_CD,' ')  END,5,' ') AS CLM_LINE_HCPCS_CD
	
	,RPAD(CASE WHEN CL.HCPCS_1_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_1_MDFR_CD,' ')	END,2,' ') AS HCPCS_1_MDFR_CD	
	,RPAD(CASE WHEN CL.HCPCS_2_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_2_MDFR_CD,' ')	END,2,' ') AS HCPCS_2_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_3_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_3_MDFR_CD,' ')	END,2,' ') AS HCPCS_3_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_4_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_4_MDFR_CD,' ')	END,2,' ') AS HCPCS_4_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_5_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_5_MDFR_CD,' ')	END,2,' ') AS HCPCS_5_MDFR_CD

    	,RPAD(CASE WHEN CL.CLM_LINE_NDC_CD ='~' THEN ' ' ELSE CL.CLM_LINE_NDC_CD END,11,' ')  AS CLM_LINE_NDC_CD
	,RPAD(CASE WHEN CL.CLM_LINE_NDC_QTY_QLFYR_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_LINE_NDC_QTY_QLFYR_CD,' ') END,2,' ') AS  CLM_LINE_NDC_QTY_QLFYR_CD

	-- WARNING !!  (FORMAT '9(14)V9(4)S') CHAR(18) Truncation of SIGN
	,TO_CHAR(COALESCE(CL.CLM_LINE_NDC_QTY,0),'0000000000000.0000S')  AS CLM_LINE_NDC_QTY 
	-- WARNING !!  (FORMAT '9(14)V9(4)S') CHAR(18) Truncation of SIGN
	,TO_CHAR(COALESCE(CL.CLM_LINE_SRVC_UNIT_QTY,0),'0000000000000.0000S')  AS CLM_LINE_SRVC_UNIT_QTY 

	-- WARNING !!  (FORMAT '9(13)V9(2)S') (CHAR(15)) TRUNCATION OF SIGN 
	,TO_CHAR(CASE WHEN CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P'  THEN COALESCE(CLEOPD.CLM_LINE_OTHR_PYR_PD_AMT,0)  ELSE 0 END,'0000000000000.00S')  AS CLM_LINE_OTHR_PYR_PD_AMT
	-- WARNING !! (FORMAT '9(13)V9(2)S') (CHAR(15)) 
	,TO_CHAR(COALESCE(CL.CLM_LINE_SBMT_CHRG_AMT,0),'0000000000000.00S') AS CLM_LINE_SBMT_CHRG_AMT 

	,RPAD(CASE WHEN CL.CLM_RNDRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,' ') END,10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM
	,RPAD(CASE WHEN CL.CLM_RNDRG_PRVDR_NAME = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_PRVDR_NAME,' ') END,120,' ')  AS CLM_RNDRG_PRVDR_NAME
	,RPAD(CASE WHEN CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,' ') END,2,' ') AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD

	,CASE WHEN CL.CLM_LINE_THRU_DT IS NULL THEN '10000101' ELSE TO_CHAR(CL.CLM_LINE_THRU_DT,'YYYYMMDD') END  AS  CLM_LINE_THRU_DT

    ,RPAD(CASE WHEN C.CLM_SBMTR_CNTRCT_NUM = BF.CNTRCT_PTC_NUM THEN BF.CNTRCT_PBP_PTC_NUM ELSE ' ' END,3,' ')  AS CNTRCT_PBP_PTC_NUM
	,RPAD(CASE WHEN CED.CLM_CNTRCT_TYPE_CD = '~' THEN ' ' ELSE COALESCE(CED.CLM_CNTRCT_TYPE_CD,' ') END,2,' ') AS CLM_CNTRCT_TYPE_CD
	,RPAD(CASE WHEN CLED.CLM_LINE_CNTRCT_TYPE_CD = '~' THEN ' ' ELSE COALESCE(CLED.CLM_LINE_CNTRCT_TYPE_CD,' ') END,2,' ')  AS CLM_LINE_CNTRCT_TYPE_CD
	,CASE WHEN CED.CLM_CHRT_RVW_SW = '~' THEN ' ' ELSE COALESCE(CED.CLM_CHRT_RVW_SW,' ') END AS CLM_CHRT_RVW_SW 

    	-- FORMAT '9(18)')
	--,TO_CHAR(BENE.BENE_SK,'FM000000000000000000')  AS BENE_SK
	,C.CLM_FINL_ACTN_IND
	,CL.CLM_LINE_FINL_ACTN_IND
	,C.CLM_LTST_CLM_IND
	,CL.CLM_LINE_LTST_CLM_IND
	,RPAD(CLE.CLM_LINE_ENCTR_STUS_CD,20,' ')
	
	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_TXNMY_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_TXNMY_CD,' ') END,50,' ') AS CLM_BLG_PRVDR_TXNMY_CD
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_TXNMY_CD ='~' THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_TXNMY_CD,' ') END,10,' ') AS CLM_ATNDG_PRVDR_TXNMY_CD
	,RPAD(CE.CLM_EDPS_STUS_CD,20,' ')
	,CASE WHEN C.CLM_OBSLT_DT IS NULL THEN REPEAT(8,' ') ELSE TO_CHAR(C.CLM_OBSLT_DT,'YYYYMMDD') END  AS  CLM_OBSLT_DT

    	-- WARNING!! (FORMAT '9(13)V9(2)S') (CHAR(15)) Truncation of sign
	,TO_CHAR(COALESCE(CED.CLM_CNTRCT_AMT,0),'0000000000000.00S')  AS  CLM_CNTRCT_AMT

    	-- WARNING!! (FORMAT '9(13)V9(2)S') (CHAR(15)) Truncation of sign
	,TO_CHAR(COALESCE(C.CLM_PTNT_LBLTY_AMT,0),'0000000000000.00S')  AS CLM_PTNT_LBLTY_AMT
 	,RPAD(CASE WHEN BENE.BENE_EQTBL_BIC_CD = '~' THEN ' ' ELSE COALESCE(BENE.BENE_EQTBL_BIC_CD,' ') END,2,' ')  AS  BENE_EQTBL_BIC_CD

	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_1_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_1_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_2_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_2_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_3_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_3_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_CITY_NAME,' '),30,' ')       AS CLM_BPRVDR_CITY_NAME
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_USPS_STATE_CD,' '),2,' ')    AS CLM_BPRVDR_USPS_STATE_CD
	,RPAD(COALESCE(ADRTEMP.BPRVDR_GEO_ZIP5_CD,' '),5,' ') || 
	 RPAD(COALESCE(ADRTEMP.BPRVDR_GEO_ZIP4_CD,' '),4,' ')          AS ADR_BPRVDR_ZIP_CD 

	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_1_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_1_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_2_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_2_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_3_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_3_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_CITY_NAME,' '),30,' ')       AS CLM_SUBSCR_CITY_NAME
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_USPS_STATE_CD,' '),2,' ')    AS CLM_SUBSCR_USPS_STATE_CD
	,RPAD(COALESCE(ADRTEMP.SUBSCR_GEO_ZIP5_CD,' '),5,' ') || 
	 RPAD(COALESCE(ADRTEMP.SUBSCR_GEO_ZIP4_CD,' '),4,' ')          AS ADR_SUBSCR_ZIP_CD 

    ,RPAD(CASE WHEN C.CLM_BLG_PRVDR_TAX_NUM ='~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_TAX_NUM,' ') END,10,' ') AS CLM_BLG_PRVDR_TAX_NUM

	,RPAD(C.BENE_ID_TYPE_CD,1,' ')  AS BENE_ID_TYPE_CD
	,RPAD(COALESCE(BENE.BENE_MBI_ID,' '),11,' ')  AS CLM_BENE_MBI_ID
	,RPAD(COALESCE(CED.CLM_CHRT_RVW_EFCTV_SW,' '),1,' ')  AS CLM_CHRT_RVW_EFCTV_SW
	,RPAD(COALESCE(CED.CLM_EDPS_CHRT_RVW_SW,' '),1,' ')   AS CLM_EDPS_CHRT_RVW_SW	
	,'END' AS END_OF_FILE

	FROM CLM_ENC_CLMS CX

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM C
	ON  C.GEO_BENE_SK     = CX.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CX.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CX.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CX.CLM_NUM_SK

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR DT
	ON DT.CLM_DT_SGNTR_SK = C.CLM_DT_SGNTR_SK
	  
	INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE BENE
	ON C.BENE_SK          =  BENE.BENE_SK
	--   and        BENE.BENE_SRC_DLT_IND = 'N'

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_INSTNL CI
	ON  C.GEO_BENE_SK     = CI.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CI.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CI.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CI.CLM_NUM_SK
					 
	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN CDN
	ON  C.GEO_BENE_SK     = CDN.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CDN.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CDN.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CDN.CLM_NUM_SK

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ENCTR CE
	ON  C.GEO_BENE_SK     = CE.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CE.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CE.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CE.CLM_NUM_SK

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ENCTR_DCMTN  CED
	ON  C.GEO_BENE_SK     = CED.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CED.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CED.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CED.CLM_NUM_SK

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD_MTRLZD PROD_MT
	ON  C.GEO_BENE_SK     = PROD_MT.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = PROD_MT.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = PROD_MT.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = PROD_MT.CLM_NUM_SK

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ENCTR_OTHR_PYR_DTL CEOPD
	ON  C.GEO_BENE_SK      = CEOPD.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CEOPD.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CEOPD.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CEOPD.CLM_NUM_SK
	AND CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P'

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_ENCTR_OTHR_PYR_PMT CEOPP
	ON  C.GEO_BENE_SK      = CEOPP.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CEOPP.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CEOPP.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CEOPP.CLM_NUM_SK
	AND CEOPP.CLM_OTHR_PYR_PMT_SQNC_NUM = 1

	INNER JOIN  IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP5
	ON ZIP5.GEO_SK        = C.GEO_BENE_SK

	LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP9_CD ZIP9
	ON ZIP9.GEO_SK        = ZIP5.GEO_SK
	AND BENE.GEO_ZIP4_CD  = ZIP9.GEO_ZIP4_CD

	--LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD GFCC 
	--ON  GFCC.GEO_FIPS_CNTY_CD  = ZIP5.GEO_FIPS_CNTY_CD 
	--AND GFCC.GEO_FIPS_STATE_CD = ZIP5.GEO_FIPS_STATE_CD

	LEFT OUTER JOIN ( 
			SELECT DISTINCT 
			GCNTY.GEO_FIPS_CNTY_CD,GCNTY.GEO_FIPS_STATE_CD,GCNTY.GEO_SSA_STATE_CD,GCNTY.GEO_SSA_CNTY_CD
			FROM IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD GCNTY ) GFCC
	ON  ZIP5.GEO_FIPS_CNTY_CD   = GFCC.GEO_FIPS_CNTY_CD
	AND ZIP5.GEO_FIPS_STATE_CD  = GFCC.GEO_FIPS_STATE_CD
						
	-- Claim Line joins
	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
	ON  C.GEO_BENE_SK      = CL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CL.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CL.CLM_NUM_SK
	AND C.CLM_FROM_DT      = CL.CLM_FROM_DT

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_ENCTR CLE
	ON  CL.GEO_BENE_SK      = CLE.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK  = CLE.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD      = CLE.CLM_TYPE_CD
	AND CL.CLM_NUM_SK       = CLE.CLM_NUM_SK
	AND CL.CLM_LINE_NUM     = CLE.CLM_LINE_NUM

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_ENCTR_DCMTN  CLED
	 ON CL.GEO_BENE_SK      = CLED.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK  = CLED.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD      = CLED.CLM_TYPE_CD
	AND CL.CLM_NUM_SK       = CLED.CLM_NUM_SK
	AND CL.CLM_LINE_NUM     = CLED.CLM_LINE_NUM

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_ENCTR_OTHR_PYR_DTL CLEOPD
	ON  CL.GEO_BENE_SK     =  CLEOPD.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK =  CLEOPD.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD     =  CLEOPD.CLM_TYPE_CD
	AND CL.CLM_NUM_SK      =  CLEOPD.CLM_NUM_SK
	AND CL.CLM_LINE_NUM    =  CLEOPD.CLM_LINE_NUM
	AND CLEOPD.CLM_LINE_OTHR_PYR_SQNC_NUM = 1

	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_ENCTR_OTHR_PYR_PMT CLEOPP
	ON  CL.GEO_BENE_SK     =  CLEOPP.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK =  CLEOPP.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD     =  CLEOPP.CLM_TYPE_CD
	AND CL.CLM_NUM_SK      =  CLEOPP.CLM_NUM_SK
	AND CL.CLM_LINE_NUM    =  CLEOPP.CLM_LINE_NUM
	AND CLEOPP.CLM_LINE_OTHR_PYR_PMT_SQNC_NUM = 1

	LEFT OUTER JOIN TMP_ADR ADRTEMP
	ON  C.GEO_BENE_SK      = ADRTEMP.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = ADRTEMP.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = ADRTEMP.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = ADRTEMP.CLM_NUM_SK
			
	LEFT OUTER JOIN IDRC_PRD.CMS_FCT_BENE_MTRLZD_PRD.BENE_FCT_TRANS BF
	ON  BF.BENE_SK = C.BENE_SK
	AND TO_DATE(BF.IDR_TRANS_OBSLT_TS) = '9999-12-31'
	AND C.CLM_FROM_DT BETWEEN BENE_FCT_EFCTV_DT AND
		CASE WHEN BF.BENE_DEATH_DT IS NOT NULL
		THEN  ADD_MONTHS(( BENE_FCT_OBSLT_DT - EXTRACT(DAY FROM BENE_FCT_OBSLT_DT) + 1),1)-1
		ELSE BENE_FCT_OBSLT_DT END

	WHERE CL.CLM_LINE_FINL_ACTN_IND = 'Y'


) FILE_FORMAT = (TYPE = CSV field_delimiter = "|"  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
                        SINGLE=TRUE  max_file_size=5368709120 