
COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ103WALMART_PTD_Y2014_20250812.120000.txt.gz FROM (


SELECT 

	'START' AS HDR

    ,CASE WHEN C.CLM_PTNT_BIRTH_DT IS NULL         THEN '0000'
           WHEN C.CLM_PTNT_BIRTH_DT = '0001-01-01' THEN '0000'
           WHEN C.CLM_PTNT_BIRTH_DT = '1000-01-01' THEN '0000'
           ELSE to_char(C.CLM_PTNT_BIRTH_DT,'YYYY') 
     END            AS  CLM_PTNT_BIRTH_DT

    -- Format 9(9)
    ,TO_CHAR(CLR.CLM_LINE_RX_FILL_NUM,'FM000000000')       AS  CLM_LINE_RX_FILL_NUM

    ,CASE WHEN C.CLM_PD_DT         IS NULL         THEN '00000000'
          WHEN C.CLM_PD_DT        = '0001-01-01'   THEN '00000000'
          WHEN C.CLM_PD_DT        = '1000-01-01'   THEN '00000000'
          ELSE TO_CHAR(C.CLM_PD_DT,'YYYYMMDD')
     END            AS  CLM_PD_DT


    ,RPAD(TRIM(C.CLM_PRSBNG_PRVDR_GNRC_ID_NUM),35,' ')  AS  PRTY_PRVDR_PHYSN_PRSCRB_ID	

    ,RPAD(C.PRVDR_PRSBNG_ID_QLFYR_CD,2,' ')          AS  PRVDR_PRSBNG_ID_QLFYR_CD
    ,RPAD(TRIM(C.CLM_SRVC_PRVDR_GNRC_ID_NUM),20,' ') AS  CLM_SRVC_PRVDR_GNRC_ID_NUM			

    ,RPAD(C.PRVDR_SRVC_ID_QLFYR_CD,2,' ')            AS  PRTY_GNRC_ID_QLFYR
    
    ,RPAD(COALESCE(C.CLM_OTHR_PRVDR_GNRC_ID_NUM,' '),20,' ') AS CLM_OTHR_PRVDR_GNRC_ID_NUM

    ,RPAD(COALESCE(C.PRVDR_OTHR_ID_QLFYR_CD,' '),2,' ')      AS  PRVDR_OTHR_ID_QLFYR_CD

    ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')  AS CLM_FROM_DT 
    ,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')  AS CLM_THRU_DT  

    ,TO_CHAR(CLR.CLM_LINE_DAYS_SUPLY_QTY,'FM000000000')     AS  CLM_LINE_DAYS_SUPLY_QTY
    ,RPAD(CLR.CLM_DSPNSNG_STUS_CD,1,' ')                    AS  CLM_DSPNSNG_STUS_CD

    ,RPAD(CL.CLM_LINE_NDC_CD,11,' ')                        AS  PROD_NDC_CODE
	-- Format S9(15).999
    ,TO_CHAR(CL.CLM_LINE_NDC_QTY,'S000000000000000.000')    AS  CLM_LINE_NDC_QTY

	,TO_CHAR(DENSE_RANK() OVER (ORDER BY BENE.BENE_SK),'FM000000000') AS DI_BENE_SK
   
    ,RPAD(REPLACE(P.PRVDR_NCPDP_ID,'~',''),5,' ')           AS  PRVDR_NCPDP_ID 
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LGL_BUSNS_NAME,''),60,' ') AS  PRVDR_NCPDP_LGL_BUSNS_NAME  
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LINE_1_ADR,''),55,' ')     AS  PRVDR_NCPDP_LINE_1_ADR    
    ,RPAD(COALESCE(P.PRVDR_NCPDP_LINE_2_ADR,''),55,' ')     AS  PRVDR_NCPDP_LINE_2_ADR 

	,TO_CHAR(COALESCE(NPI.GEO_PRVDR_PRCTC_SK,0),'FM00000')  AS  GEO_PRVDR_PRCTC_SK

    ,RPAD(COALESCE(ST1.GEO_USPS_STATE_CD,''),2,' ')         AS  GEO_USPS_STATE_CD  
	
    ,RPAD(REPLACE(COALESCE(BENE.BENE_RACE_CD,''),'~',''),2,' ')           AS  BENE_RACE_CD
    ,RPAD(REPLACE(COALESCE(BENE.BENE_RACE_SRC_CD,' '),'~',''),1,' ')      AS  BENE_RACE_SRC_CD 

    ,RPAD(COALESCE(TXNMY.PRVDR_NCPDP_DSPNSR_TYPE_CD,''),2,' ')  AS  PRVDR_NCPDP_DSPNSR_TYPE_CD  
    ,RPAD(COALESCE(TXNMY.PRVDR_NCPDP_TXNMY_CD,''),10,' ')       AS  PRVDR_NCPDP_TXNMY_CD     
    
    ,'END' AS END_MARKER

    /*
            
--BENE.BENE_SK
,DENSE_RANK() OVER (ORDER BY BENE.BENE_SK) AS MASK_BENE_ID
,EXTRACT (YEAR FROM BENE.BENE_BRTH_DT)

,CLM.CLM_PD_DT
,CLM.CLM_PRSBNG_PRVDR_GNRC_ID_NUM
,CLM.PRVDR_PRSBNG_ID_QLFYR_CD
,CLM.CLM_SRVC_PRVDR_GNRC_ID_NUM
,CLM.PRVDR_SRVC_ID_QLFYR_CD
,CLM.CLM_OTHR_PRVDR_GNRC_ID_NUM
,CLM.PRVDR_OTHR_ID_QLFYR_CD
,CLM.CLM_FROM_DT 
,CLM.CLM_THRU_DT 
,BENE.BENE_RACE_SRC_CD  --char(1)
,BENE.BENE_RACE_CD        --char(2)
,TXNMY.PRVDR_NCPDP_DSPNSR_TYPE_CD  --char(2)
,TXNMY.PRVDR_NCPDP_TXNMY_CD     --char(10)
,P.PRVDR_NCPDP_ID    --char(7)
,P.PRVDR_NCPDP_LGL_BUSNS_NAME  --char(55)
,P.PRVDR_NCPDP_LINE_1_ADR  --char(55)
,P.PRVDR_NCPDP_LINE_2_ADR --char(55)
,NPI.GEO_PRVDR_PRCTC_SK     --char(5)
,ST1.GEO_USPS_STATE_CD       --char(2)

*/


FROM IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_CLM C 

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
ON  C.GEO_BENE_SK      = CL.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CL.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CL.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CL.CLM_NUM_SK
AND C.CLM_FROM_DT=CL.CLM_FROM_DT

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_RX CLR
ON  C.GEO_BENE_SK      = CLR.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CLR.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CLR.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CLR.CLM_NUM_SK
    
INNER JOIN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_BENE BENE
ON C.BENE_SK = BENE.BENE_SK

--JOIN IDRC_PRD.CMS_SASTEMP_COMM_PRD.PVPV_NDC_LIST_W L1
--ON SUBSTR(CL.CLM_LINE_NDC_CD,1,9)= SUBSTR(NDC,1,9)

INNER JOIN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_PRVDR_NCPDP P
ON 
    CASE C.PRVDR_SRVC_ID_QLFYR_CD
         WHEN  '07' THEN C.CLM_SRVC_PRVDR_GNRC_ID_NUM
         WHEN  '01' THEN
                CASE C.PRVDR_OTHR_ID_QLFYR_CD
                     WHEN  '07' THEN C.CLM_OTHR_PRVDR_GNRC_ID_NUM
                      ELSE '         '
                 END  
          ELSE '         '
  END
      --PRVDR_NCPDP_ID_FNL
      = P.PRVDR_NCPDP_ID
    
INNER JOIN IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR NPI
ON 
    CASE C.PRVDR_SRVC_ID_QLFYR_CD
     WHEN  '01' THEN C.CLM_SRVC_PRVDR_GNRC_ID_NUM
     WHEN  '07' THEN
            CASE C.PRVDR_OTHR_ID_QLFYR_CD
                 WHEN  '01' THEN C.CLM_OTHR_PRVDR_GNRC_ID_NUM
                  ELSE '         '
             END  
      ELSE '         '
    END
      --PRVDR_NPI_FNL 
      = NPI.PRVDR_NPI_NUM

INNER JOIN (SELECT * FROM  IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR WHERE PRVDR_NPI_NUM IN      ('1831282896','1497729313','1518296839','1689720666','1487602900','1396772737',
        '1801883533','1841375284','1730252289','1841322104','1043292477',
        '1508915216','1578545513','1841252145','1922174234','1831132026',
        '1215000757','1922099910','1366620833','1467431320','1023183001',
        '1255308417','1952444846','1437198033','1104042357','1336116789','1881782373','1053360420') 
		) PRSBNG
ON C.CLM_PRSBNG_PRVDR_GNRC_ID_NUM = PRSBNG.PRVDR_NPI_NUM

LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP1
ON NPI.GEO_PRVDR_PRCTC_SK = ZIP1.GEO_SK

LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD FIPS1
ON FIPS1.GEO_FIPS_CNTY_CD   = ZIP1.GEO_FIPS_CNTY_CD
AND FIPS1.GEO_FIPS_STATE_CD = ZIP1.GEO_FIPS_STATE_CD 
 
LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_STATE_CD ST1
ON FIPS1.GEO_FIPS_STATE_CD = ST1.GEO_FIPS_STATE_CD
  
LEFT OUTER JOIN     IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR_NCPDP_DSPNSR TXNMY
ON TXNMY.PRVDR_NCPDP_ID = P.PRVDR_NCPDP_ID

WHERE C.CLM_TYPE_CD in (1,2,4) 
-- June 26, 2013 to December 22, 2020
AND C.CLM_FROM_DT BETWEEN TO_DATE('2014-01-01','YYYY-MM-DD') AND TO_DATE('2014-12-31','YYYY-MM-DD')
AND C.CLM_FINL_ACTN_IND = 'Y' 

ORDER BY bene.Bene_sk

)

		   FILE_FORMAT = (TYPE = CSV field_delimiter = "|"  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
			SINGLE=TRUE  max_file_size=5368709120 
