
--REQ#1

COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ126_QRY1_20260401.120000.txt.gz FROM (

SELECT 
     'START' AS START_IND
	,C.CLM_TYPE_CD
	,TO_CHAR(CL.CLM_LINE_NUM,'FM00000')         AS CLM_LINE_NUM
	,RPAD(C.CLM_CNTL_NUM,40,' ')                AS CLM_CNTL_NUM
    ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_TAX_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_TAX_NUM
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM
	,TO_CHAR(COALESCE(CL.CLM_LINE_ALOWD_CHRG_AMT,0),'S0000000000000.00')   AS CLM_LINE_ALOWD_CHRG_AMT
    ,TO_CHAR(COALESCE(CL.CLM_LINE_CVRD_PD_AMT,0),'S000000000.00')          AS CLM_LINE_CVRD_PD_AMT 

	,TO_CHAR(COALESCE(CLOA.CLM_LINE_OTHR_APLD_AMT,0),'S0000000000.00')     AS CLM_LINE_OTHR_APLD_AMT
    -- We are only interested in V (Positive amt) and W (Negative amt)
	,RPAD(COALESCE(CLOA.CLM_LINE_OTHR_APLD_CD,''),2,' ')                   AS MIPS_PYMT_AMT_APPLIED_CD
	,'END' AS END_IND

FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C    

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

INNER JOIN BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_REQ126_FF FF
ON  TO_CHAR(C.CLM_FROM_DT,'YYYY')  =  FF.PYMT_YR
AND CL.CLM_RNDRG_PRVDR_TAX_NUM     =  FF.TIN_NUM
AND CL.CLM_RNDRG_PRVDR_NPI_NUM     =  FF.NPI_NUM
AND TO_CHAR(CL.CLM_FROM_DT,'YYYY') =  FF.PYMT_YR 
--AND FF.PYMT_YR = '2020'

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_OTHR_APLD CLOA
ON  CL.GEO_BENE_SK     = CLOA.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK = CLOA.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD     = CLOA.CLM_TYPE_CD
AND CL.CLM_NUM_SK      = CLOA.CLM_NUM_SK
AND CL.CLM_LINE_NUM    = CLOA.CLM_LINE_NUM
--AND CLOA.CLM_TYPE_CD     IN ('71','72')
AND CLOA.CLM_LINE_OTHR_APLD_CD IN ('V','W')

WHERE C.CLM_TYPE_CD IN ('71','72')
AND C.CLM_FINL_ACTN_IND = 'Y'

)
;


--REQ#2

COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ126_QRY2_20260401.120000.txt.gz FROM (

WITH FF_MATCHING_RESULTS AS (

	SELECT DISTINCT FF.PYMT_YR, FF.TIN_NUM, FF.NPI_NUM

    FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C    

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
	ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
	AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

	INNER JOIN BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_REQ126_FF FF
	ON  TO_CHAR(C.CLM_FROM_DT,'YYYY')  =  FF.PYMT_YR
	AND CL.CLM_RNDRG_PRVDR_TAX_NUM     =  FF.TIN_NUM
	AND CL.CLM_RNDRG_PRVDR_NPI_NUM     =  FF.NPI_NUM

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_OTHR_APLD CLOA
	ON  CL.GEO_BENE_SK     = CLOA.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK = CLOA.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD     = CLOA.CLM_TYPE_CD
	AND CL.CLM_NUM_SK      = CLOA.CLM_NUM_SK
	AND CL.CLM_LINE_NUM    = CLOA.CLM_LINE_NUM
	--AND CLOA.CLM_TYPE_CD     IN ('71','72')
	AND CLOA.CLM_LINE_OTHR_APLD_CD IN ('V','W')

	WHERE C.CLM_TYPE_CD IN ('71','72')
	AND C.CLM_FINL_ACTN_IND = 'Y'

)

,FF_NON_MATCHES AS (

	SELECT PYMT_YR, TIN_NUM, NPI_NUM
	FROM BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_REQ126_FF FF
    MINUS
    SELECT PYMT_YR, TIN_NUM, NPI_NUM
    FROM FF_MATCHED_RESULTS 

)

	SELECT COUNT(DISTINCT C.BENE_SK)

     'START' AS START_IND
	,C.CLM_TYPE_CD
	,TO_CHAR(CL.CLM_LINE_NUM,'FM00000')         AS CLM_LINE_NUM
	,RPAD(C.CLM_CNTL_NUM,40,' ')                AS CLM_CNTL_NUM
    ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_TAX_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_TAX_NUM
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM
	,TO_CHAR(COALESCE(CL.CLM_LINE_ALOWD_CHRG_AMT,0),'S0000000000000.00')   AS CLM_LINE_ALOWD_CHRG_AMT
    ,TO_CHAR(COALESCE(CL.CLM_LINE_CVRD_PD_AMT,0),'S000000000.00')          AS CLM_LINE_CVRD_PD_AMT 

	,TO_CHAR(COALESCE(CLOA.CLM_LINE_OTHR_APLD_AMT,0),'S0000000000.00')     AS CLM_LINE_OTHR_APLD_AMT
    -- We are only interested in V (Positive amt) and W (Negative amt)
	,RPAD(COALESCE(CLOA.CLM_LINE_OTHR_APLD_CD,''),2,' ')                   AS MIPS_PYMT_AMT_APPLIED_CD
	,'END' AS END_IND
	
	FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C    

	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
	ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
	AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

	INNER JOIN FF_NON_MATCHES FF
	ON  TO_CHAR(C.CLM_FROM_DT,'YYYY') =  FF.PYMT_YR
	AND CL.CLM_RNDRG_PRVDR_NPI_NUM    =  FF.NPI_NUM
	
	INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_OTHR_APLD CLOA
	ON  CL.GEO_BENE_SK     = CLOA.GEO_BENE_SK
	AND CL.CLM_DT_SGNTR_SK = CLOA.CLM_DT_SGNTR_SK
	AND CL.CLM_TYPE_CD     = CLOA.CLM_TYPE_CD
	AND CL.CLM_NUM_SK      = CLOA.CLM_NUM_SK
	AND CL.CLM_LINE_NUM    = CLOA.CLM_LINE_NUM
	AND CLOA.CLM_LINE_OTHR_APLD_CD IN ('V','W')

	WHERE C.CLM_TYPE_CD IN ('71','72')
	AND C.CLM_FINL_ACTN_IND = 'Y'

)
FILE_FORMAT = (TYPE=CSV field_delimiter=none ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY=none )
                        max_file_size=5368709120


/*
SELECT *
FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_OTHR_APLD
limit 5
;
*/

/*

WITH STATEMENT 

1) SQL SELECT by YEAR, NPI, TIN  RIGHT OUTER JOIN to FF so no FF Keys (YEAR, NPI, TIN) are dropped. The CLM_TYPE_CD will be NULL for NON-Matches

2) SQL view of Matches using SQL results from #1 - filter CLM_TYPE_CD is NOT NULL; 

3) SQL view of non-Matches using SQL results from #1 - filter CLM_TYPE is NULL, include only FF.YEAR and FF.NPI in results set

4) SELECT clone of SQL #1 with INNER JOIN to Non-Matches View. This should satisfy the requirements for file #2

*/