
      SELECT 
           'START'
          ,C.CLM_TYPE_CD
          ,TO_CHAR(CL.CLM_LINE_NUM,'FM00000')       AS CLM_LINE_NUM
          ,RPAD(COALESCE(C.CLM_HIC_NUM,' '),12,' ')  AS BENE_HICN
          ,RPAD(REPLACE(COALESCE(C.BENE_SEX_CD,''),'~',''),1,' ') AS BENE_SEX_CD
          ,RPAD(COALESCE(TO_CHAR(C.CLM_PTNT_BIRTH_DT, 'YYYYMMDD'),''),8,' ') AS BENE_DOB

          ,RPAD(COALESCE(BENE.BENE_LAST_NAME,''),40,' ')    AS BENE_LAST_NAME 
          ,RPAD(COALESCE(BENE.BENE_1ST_NAME,''),30,' ')     AS BENE_1ST_NAME
          ,RPAD(COALESCE(BENE.BENE_MIDL_NAME,''),15,' ')    AS BENE_MIDL_NAME
                  
          ,RPAD(REPLACE(COALESCE(GCNTY.GEO_SSA_STATE_CD,''),'~',''),2,' ')  AS SSA_STATE_CD
          ,RPAD(REPLACE(COALESCE(ZIP5.GEO_ZIP5_CD,''),'~',''),5,' ')        AS BENE_MAILING_ZIPCD  
          
          ,TO_CHAR(CLM_ACTV_CARE_FROM_DT,'YYYYMMDD')  AS CLM_ACTV_CARE_FROM_DT
          ,TO_CHAR(CDS.CLM_DSCHRG_DT,'YYYYMMDD')      AS CLM_DSCHRG_DT
          ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
          ,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')          AS CLM_THRU_DT
          
          ,RPAD(C.CLM_CNTL_NUM,40,' ')                   AS CLAIM_CONTROL_NBR
          ,RPAD(COALESCE(C.CLM_ORIG_CNTL_NUM,''),40,' ') AS ORIG_CLAIM_CONTROL_NBR
          
          ,CI.CLM_TRANS_CD
          ,C.CLM_DISP_CD
          ,CI.BENE_PTNT_STUS_CD
          
          ,RPAD(CASE WHEN COALESCE(CI.CLM_ADMSN_TYPE_CD,' ') = '~' THEN ' ' ELSE CI.CLM_ADMSN_TYPE_CD END,2,' ')  AS CLM_ADMSN_TYPE_CD
          ,RPAD(CASE WHEN COALESCE(CI.CLM_ADMSN_SRC_CD,' ')  = '~' THEN ' ' ELSE CI.CLM_ADMSN_SRC_CD  END,2,' ')  AS CLM_ADMSN_SRC_CD
          
          ,CL.CLM_LINE_REV_CTR_CD
          ,C.CLM_BILL_FAC_TYPE_CD
          ,C.CLM_BILL_CLSFCTN_CD  
          
          ,TO_CHAR(CI.DGNS_DRG_VRSN_NUM,'FM00')  AS  DGNS_DRG_VRSN_NUM 
          ,TO_CHAR(CI.DGNS_DRG_CD,'FM0000')      AS  DGNS_DRG_CD 
          ,RPAD(CPM.CLM_PRNCPL_DGNS_CD,7,' ')    AS  CLM_PRNCPL_DGNS_CD 
          ,RPAD(COALESCE(DC1.DGNS_CD_DESC,' '),250,' ')  AS  DGNS_CD_DESC 
          
          ,RPAD(CASE WHEN CL.CLM_LINE_NDC_CD = '~' THEN ' ' ELSE CL.CLM_LINE_NDC_CD END,11,' ') AS CLM_LINE_NDC_CD
          ,RPAD(COALESCE(CL.CLM_LINE_HCPCS_CD,' '),5,' ')  AS CLM_LINE_HCPCS_CD
          ,RPAD(CL.HCPCS_1_MDFR_CD,2,' ')  AS HCPCS_1_MDFR_CD
          ,RPAD(CL.HCPCS_2_MDFR_CD,2,' ')  AS HCPCS_2_MDFR_CD
          ,RPAD(CL.HCPCS_3_MDFR_CD,2,' ')  AS HCPCS_3_MDFR_CD
          ,RPAD(CL.HCPCS_4_MDFR_CD,2,' ')  AS HCPCS_4_MDFR_CD

          ,RPAD(C.CLM_BLG_PRVDR_OSCAR_NUM,20,' ')   AS  CLM_BLG_PRVDR_OSCAR_NUM 
          ,RPAD(C.CLM_BLG_PRVDR_NPI_NUM,10,' ')     AS  CLM_BLG_PRVDR_NPI_NUM
          ,RPAD(C.CLM_ATNDG_PRVDR_NPI_NUM,10,' ')   AS  CLM_ATNDG_PRVDR_NPI_NUM
          ,RPAD(C.PRVDR_ATNDG_PRVDR_NPI_NUM,10,' ') AS  PRVDR_ATNDG_PRVDR_NPI_NUM

          ,RPAD(CASE WHEN C.PRVDR_OPRTG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_OPRTG_PRVDR_NPI_NUM END,10,' ')  AS PRVDR_OPRTG_PRVDR_NPI_NUM
          ,RPAD(CASE WHEN C.PRVDR_OTHR_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_OTHR_PRVDR_NPI_NUM END,10,' ')    AS PRVDR_OTHR_PRVDR_NPI_NUM
          
          ,RPAD(REPLACE(CL.PRVDR_FAC_PRVDR_NPI_NUM,'~',''),10,' ')  AS PRVDR_FAC_PRVDR_NPI_NUM
          ,RPAD(CASE WHEN C.PRVDR_SRVC_PRVDR_NPI_NUM = '~' THEN ' ' ELSE C.PRVDR_SRVC_PRVDR_NPI_NUM END,10,' ')  AS PRVDR_SRVC_PRVDR_NPI_NUM
          
          ,RPAD(COALESCE(P.PRVDR_LGL_NAME,' '),70,' ')         AS  PRVDR_LGL_NAME
          ,RPAD(COALESCE(P.PRVDR_MLG_TEL_NUM,' '),20,' ')      AS  PRVDR_MLG_TEL_NUM
          
          ,RPAD(COALESCE(P.PRVDR_MLG_LINE_1_ADR,' '),100,' ')  AS  PRVDR_MLG_LINE_1_ADR
          ,RPAD(COALESCE(P.PRVDR_MLG_LINE_2_ADR,' '),100,' ')  AS  PRVDR_MLG_LINE_2_ADR
          ,RPAD(COALESCE(P.PRVDR_INVLD_MLG_PLC_NAME,' '),40,' ')  AS  PRVDR_INVLD_MLG_PLC_NAME 
          ,RPAD(COALESCE(P.PRVDR_INVLD_MLG_STATE_CD,' '),2,' ')   AS  PRVDR_INVLD_MLG_STATE_CD
          ,RPAD(COALESCE(P.PRVDR_INVLD_MLG_ZIP_CD,' '),9,' ')     AS  PRVDR_INVLD_MLG_ZIP_CD 


          -- NUMERIC FORMATTING -- we should include decimal place and sign going forward?
          ,TO_CHAR(C.CLM_PMT_AMT,'S0000000000000.00')  AS  CLM_PMT_AMT 
          ,RPAD(CI.CLM_MDCR_NPMT_RSN_CD,2,' ')  AS  CLM_MDCR_NPMT_RSN_CD 
                   
          ,TO_CHAR(COALESCE(C.CLM_PRVDR_PMT_AMT,0),'S000000000.00')  AS  CLM_PRVDR_PMT_AMT 
          ,TO_CHAR(CL.CLM_LINE_SRVC_UNIT_QTY,'S00000000000000.0000')  AS  CLM_LINE_SRVC_UNIT_QTY 
                   
          ,TO_CHAR(COALESCE(C.CLM_BENE_PD_AMT,0),'S0000000000000.00')  AS CLM_BENE_PD_AMT  
          ,TO_CHAR(C.CLM_SBMT_CHRG_AMT,'S0000000000000.00')            AS CLM_SBMT_CHRG_AMT 
                   
          ,TO_CHAR(COALESCE(C.CLM_ALOWD_CHRG_AMT,0),'S0000000000000.00')  AS CLM_ALOWD_CHRG_AMT 
          ,TO_CHAR(COALESCE(C.CLM_MDCR_DDCTBL_AMT,0),'S0000000000000.00') AS CLM_MDCR_DDCTBL_AMT 
                   
          ,TO_CHAR(CL.CLM_LINE_CVRD_PD_AMT,'S000000000.00')           AS CLM_LINE_CVRD_PD_AMT
                   
          ,TO_CHAR(CL.CLM_LINE_BENE_PD_AMT,'S0000000000000.00')     AS  CLM_LINE_BENE_PD_AMT
          ,TO_CHAR(CL.CLM_LINE_BENE_PMT_AMT,'S0000000000000.00')    AS  CLM_LINE_BENE_PMT_AMT
                   
          ,TO_CHAR(CL.CLM_LINE_PRVDR_PMT_AMT,'S000000000.00')       AS  CLM_LINE_PRVDR_PMT_AMT
          ,TO_CHAR(CL.CLM_LINE_MDCR_DDCTBL_AMT,'S000000000.00')     AS  CLM_LINE_MDCR_DDCTBL_AMT 

          ,RPAD(COALESCE(C.CLM_NCH_PRMRY_PYR_CD,' '),1,' ') AS CLM_NCH_PRMRY_PYR_CD
          ,TO_CHAR(COALESCE(CI.CLM_MDCR_INSTNL_BENE_PD_AMT,0),'S000000000.00')  AS CLM_MDCR_INSTNL_BENE_PD_AMT
          ,TO_CHAR(CI.CLM_MDCR_INSTNL_PRMRY_PYR_AMT,'S000000000.00')            AS CLM_MDCR_INSTNL_PRMRY_PYR_AMT
          ,TO_CHAR(COALESCE(CL.CLM_LINE_MDCR_COINSRNC_AMT,0),'S000000000.00')   AS CLM_LINE_MDCR_COINSRNC_AMT
                   
          ,TO_CHAR(COALESCE(CL.CLM_LINE_PTB_BLOOD_DDCTBL_QTY,0),'FM000') AS CLM_LINE_PTB_BLOOD_DDCTBL_QTY
                   
          ,TO_CHAR(CL.CLM_LINE_SBMT_CHRG_AMT,'S0000000000000.00')                AS CLM_LINE_SBMT_CHRG_AMT
          ,TO_CHAR(COALESCE(CL.CLM_LINE_ALOWD_CHRG_AMT,0),'S0000000000000.00') AS CLM_LINE_ALOWD_CHRG_AMT
          ,TO_CHAR(COALESCE(CL.CLM_LINE_OTHR_TP_PD_AMT,0),'S0000000000000.00') AS CLM_LINE_OTHR_TP_PD_AMT

          ,TO_CHAR(COALESCE(C.CLM_OTHR_TP_PD_AMT,0),'S0000000000000.00')       AS CLM_OTHR_TP_PD_AMT
          ,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_COPMT_AMT,0),'S0000000000000.00') AS CLM_LINE_BENE_COPMT_AMT
          ,CLM_FINL_ACTN_IND
          ,RPAD(COALESCE(C.CLM_BENE_MBI_ID,''),11,' ') AS BENE_MBI_ID
          ,'END'

            FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C   

            INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR CDS
            ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK

            INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE BENE
            ON C.BENE_SK = BENE.BENE_SK

            INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_INSTNL  CI
            ON  C.GEO_BENE_SK     = CI.GEO_BENE_SK
            AND C.CLM_DT_SGNTR_SK = CI.CLM_DT_SGNTR_SK
            AND C.CLM_TYPE_CD     = CI.CLM_TYPE_CD
            AND C.CLM_NUM_SK      = CI.CLM_NUM_SK 

            INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD_MTRLZD CPM 
            ON  C.GEO_BENE_SK     = CPM.GEO_BENE_SK
            AND C.CLM_DT_SGNTR_SK = CPM.CLM_DT_SGNTR_SK
            AND C.CLM_TYPE_CD     = CPM.CLM_TYPE_CD
            AND C.CLM_NUM_SK      = CPM.CLM_NUM_SK
      
            INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
            ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
            AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
            AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
            AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
            AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

            -- Getting PRVDR LGL_NAME --> for BILLING PRVDR_NPI_NUM?
            LEFT OUTER JOIN IDRC_PRD.CMS_DIM_PRVDR_PRD.PRVDR P
            ON C.CLM_BLG_PRVDR_NPI_NUM = P.PRVDR_NPI_NUM
      
            LEFT OUTER JOIN IDRC_PRD.CMS_VDM_VIEW_MDCR_PRD.V2_MDCR_DGNS_CD DC1
            ON  CPM.CLM_PRNCPL_DGNS_CD = DC1.DGNS_CD
            AND C.CLM_THRU_DT BETWEEN DC1.DGNS_CD_BGN_DT AND DC1.DGNS_CD_END_DT

            -- Zip code should be for what was active at time of claim  
            INNER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP5
            ON C.GEO_BENE_SK = ZIP5.GEO_SK

            LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD GCNTY
            ON  ZIP5.GEO_FIPS_CNTY_CD   = GCNTY.GEO_FIPS_CNTY_CD
            AND ZIP5.GEO_FIPS_STATE_CD  = GCNTY.GEO_FIPS_STATE_CD 
            
      -- January 1, 2010 – December 31, 2025      
      WHERE C.CLM_TYPE_CD IN (40,60)
        AND BENE.BENE_SSN_NUM = '297814945'
        AND C.CLM_FINL_ACTN_IND = 'Y'
        AND C.CLM_FROM_DT BETWEEN TO_DATE('2010-01-01','YYYY-MM-DD') AND TO_DATE('2025-12-31','YYYY-MM-DD')
        ;


-- FFS PTB CAR = 15 DME = 0

--COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ113Morelos_FFS_PTB_CAR_20250808.120000.txt.gz FROM (
                                                FROM (
												
          SELECT 
               'START'
              ,C.CLM_TYPE_CD
              ,TO_CHAR(CL.CLM_LINE_NUM,'FM00000')        AS CLM_LINE_NUM
              ,RPAD(COALESCE(C.CLM_HIC_NUM,''),12,' ')   AS BENE_HIC_NUM
              
              ,RPAD(REPLACE(COALESCE(GCNTY.GEO_SSA_STATE_CD,''),'~',''),2,' ') AS GEO_SSA_STATE_CD
              
              ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
              ,TO_CHAR(C.CLM_THRU_DT,'YYYYMMDD')          AS CLM_THRU_DT
              
              ,RPAD(C.CLM_CNTL_NUM,40,' ')                AS CLM_CNTL_NUM
              
              ,RPAD(COALESCE(TO_CHAR(CDS.CLM_CWF_ACRTN_DT, 'YYYYMMDD'),''),8,' ') AS CLM_CWF_ACRTN_DT
              ,RPAD(COALESCE(TO_CHAR(CDS.CLM_NCH_WKLY_PROC_DT, 'YYYYMMDD'),''),8,' ') AS CLM_NCH_WKLY_PROC_DT
                
              ,RPAD(REPLACE(COALESCE(C.CLM_DISP_CD,''),'~',''),2,' ') AS CLM_DISP_CD
              ,RPAD(REPLACE(C.CLM_QUERY_CD,'~',''),1,' ')             AS CLM_QUERY_CD
              ,RPAD(REPLACE(GCNTY.GEO_SSA_CNTY_CD,'~',''),3,' ')      AS GEO_SSA_CNTY_CD
              
              ,RPAD(COALESCE(TO_CHAR(CDS.CLM_SUBMSN_DT, 'YYYYMMDD'),''),8,' ') AS CLM_SUBMSN_DT
              ,RPAD(COALESCE(TO_CHAR(CDS.CLM_SCHLD_PMT_DT, 'YYYYMMDD'),''),8,' ') AS CLM_SCHLD_PMT_DT          

              ,RPAD(REPLACE(COALESCE(CL.CLM_CNTRCTR_NUM,''),'~',''),5,' ') AS CLM_CNTRCTR_NUM
              ,RPAD(REPLACE(COALESCE(ZIP5.GEO_ZIP5_CD,''),'~',''),5,' ') AS GEO_ZIP5_CD 
              ,RPAD(REPLACE(COALESCE(C.BENE_SEX_CD,''),'~',''),1,' ') AS BENE_SEX_CD
              ,RPAD(REPLACE(COALESCE(CDM.BENE_RACE_CD,''),'~',''),2,' ') AS BENE_RACE_CD
              
              ,RPAD(COALESCE(TO_CHAR(C.CLM_PTNT_BIRTH_DT, 'YYYYMMDD'),''),8,' ') AS CLM_PTNT_BIRTH_DT
              
              ,RPAD(COALESCE(CDM.CLM_CWF_BENE_MDCR_STUS_CD,''),2,' ') AS CLM_CWF_BENE_MDCR_STUS_CD
              
              ,RPAD(COALESCE(B.BENE_LAST_NAME,''),60,' ') AS BENE_LAST_NAME
              ,RPAD(COALESCE(B.BENE_1ST_NAME,''),35,' ') AS BENE_1ST_NAME
              ,COALESCE(B.BENE_MIDL_NAME,' ') AS BENE_MIDL_NAME
              
              -- on multiple tables
              ,COALESCE(CL.CLM_DGNS_PRCDR_ICD_IND, ' ') AS CLM_DGNS_PRCDR_ICD_IND
              
              ,RPAD(COALESCE(CPM.CLM_PRNCPL_DGNS_CD,''),7,' ')                    AS CLM_PRNCPL_DGNS_CD
              ,RPAD(REPLACE(COALESCE(CP.CLM_CARR_PMT_DNL_CD,''),'~',''),2,' ') AS CLM_CARR_PMT_DNL_CD
              
              ,TO_CHAR(C.CLM_PMT_AMT,'S0000000000000.00')  AS  CLM_PMT_AMT
              ,TO_CHAR(COALESCE(CP.CLM_MDCR_PRFNL_PRMRY_PYR_AMT,0),'S000000000.00') AS CLM_MDCR_PRFNL_PRMRY_PYR_AMT
              
              ,RPAD(REPLACE(COALESCE(C.CLM_RFRG_PRVDR_UPIN_NUM,''),'~',''),6,' ')   AS CLM_RFRG_PRVDR_UPIN_NUM
              ,RPAD(REPLACE(COALESCE(C.PRVDR_RFRG_PRVDR_NPI_NUM,''),'~',''),10,' ') AS PRVDR_RFRG_PRVDR_NPI_NUM
              ,RPAD(REPLACE(COALESCE(C.CLM_RFRG_PRVDR_NPI_NUM,''),'~',''),10,' ') AS CLM_RFRG_PRVDR_NPI_NUM
              
              ,TO_CHAR(COALESCE(C.CLM_PRVDR_PMT_AMT,0),'S000000000.00')    AS  CLM_PRVDR_PMT_AMT 
              ,TO_CHAR(COALESCE(C.CLM_BENE_PD_AMT,0),'S0000000000000.00')  AS CLM_BENE_PD_AMT  
              ,TO_CHAR(C.CLM_SBMT_CHRG_AMT,'S0000000000000.00')            AS CLM_SBMT_CHRG_AMT 
              
              ,TO_CHAR(COALESCE(C.CLM_ALOWD_CHRG_AMT,0),'S0000000000000.00')  AS CLM_ALOWD_CHRG_AMT 
              ,TO_CHAR(COALESCE(C.CLM_MDCR_DDCTBL_AMT,0),'S0000000000000.00') AS CLM_MDCR_DDCTBL_AMT 

              ,RPAD(REPLACE(COALESCE(CP.CLM_MCO_OVRRD_CD,''),'~',''),1,' ')      AS CLM_MCO_OVRRD_CD
              ,RPAD(REPLACE(COALESCE(C.CLM_RAC_ADJSTMT_IND_CD,''),'~',''),1,' ') AS CLM_RAC_ADJSTMT_IND_CD
              
              ,RPAD(REPLACE(COALESCE(CDM.CLM_FPS_RMRK_CD,''),'~',''),5,' ')          AS CLM_FPS_RMRK_CD
              ,RPAD(REPLACE(COALESCE(CDM.CLM_MASS_ADJSTMT_TYPE_CD,''),'~',''),1,' ') AS CLM_MASS_ADJSTMT_TYPE_CD
                    
              ,RPAD(REPLACE(COALESCE(C.CLM_RFRG_PRVDR_PIN_NUM,''),'~',''),14,' ')  AS CLM_RFRG_PRVDR_PIN_NUM
              ,RPAD(REPLACE(COALESCE(C.PRVDR_CPO_FAC_NPI_NUM,''),'~',''),10,' ')   AS PRVDR_CPO_FAC_NPI_NUM

              ,RPAD(TO_CHAR(COALESCE(C.CLM_BLOOD_PT_FRNSH_QTY,0)),3,'0')    AS CLM_BLOOD_PT_FRNSH_QTY
              ,RPAD(TO_CHAR(COALESCE(CDM.CLM_BLOOD_DDCTBL_PT_QTY,0)),4,'0') AS CLM_BLOOD_DDCTBL_PT_QTY
                    
              -- CLM and CLM_LINE
              ,RPAD(REPLACE(COALESCE(C.CLM_BLG_PRVDR_NPI_NUM,''),'~',''),10,' ')     AS CLM_BLG_PRVDR_NPI_NUM
              ,RPAD(REPLACE(COALESCE(C.PRVDR_BLG_PRVDR_NPI_NUM,''),'~',''),10,' ')   AS PRVDR_BLG_PRVDR_NPI_NUM

              ,TO_CHAR(COALESCE(CPM.CLM_DGNS_TOT_OCRNC_CNT,0),'FM00')              AS CLM_DGNS_TOT_OCRNC_CNT
              ,RPAD(REPLACE(COALESCE(CDM.CLM_MCO_1ST_CNTRCT_NUM,''),'~',''),5,' ') AS CLM_MCO_1ST_CNTRCT_NUM
              ,RPAD(REPLACE(COALESCE(CDM.CLM_MCO_2ND_CNTRCT_NUM,''),'~',''),5,' ') AS CLM_MCO_2ND_CNTRCT_NUM
            
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_1_CD,''),'~',''),7,' ') AS CLM_DGNS_1_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_2_CD,''),'~',''),7,' ') AS CLM_DGNS_2_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_3_CD,''),'~',''),7,' ') AS CLM_DGNS_3_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_4_CD,''),'~',''),7,' ') AS CLM_DGNS_4_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_5_CD,''),'~',''),7,' ') AS CLM_DGNS_5_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_6_CD,''),'~',''),7,' ') AS CLM_DGNS_6_CD
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_7_CD,''),'~',''),7,' ') AS CLM_DGNS_7_CD	
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_8_CD,''),'~',''),7,' ') AS CLM_DGNS_8_CD	
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_9_CD,''),'~',''),7,' ') AS CLM_DGNS_9_CD	
              ,RPAD(REPLACE(COALESCE(CPM.CLM_DGNS_10_CD,''),'~',''),7,' ') AS CLM_DGNS_10_CD


              ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_PIN_NUM,''),'~',''),14,' ') AS CLM_RNDRG_PRVDR_PIN_NUM	
             -- CLM CLM_LINE
              ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_UPIN_NUM,''),'~',''),6,' ') AS CLM_RNDRG_PRVDR_UPIN_NUM	
             -- CLM CLM_LINE
              ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,''),'~',''),10,' ') AS CLM_RNDRG_PRVDR_NPI_NUM	
             
             -- CLM CLM_LINE
             ,RPAD(REPLACE(COALESCE(CL.PRVDR_RNDRNG_PRVDR_NPI_NUM,''),'~',''),10,' ')     AS PRVDR_RNDRNG_PRVDR_NPI_NUM
             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_GRP_NPI_NUM,''),'~',''),10,' ')    AS CLM_RNDRG_PRVDR_GRP_NPI_NUM
             ,RPAD(REPLACE(COALESCE(CL.PRVDR_RNDRNG_PRVDR_GRP_NPI_NUM,''),'~',''),10,' ') AS PRVDR_RNDRNG_PRVDR_GRP_NPI_NUM
                                       
             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_TYPE_CD,''),'~',''),3,' ')  AS CLM_RNDRG_PRVDR_TYPE_CD	
             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_TAX_NUM,''),'~',''),10,' ') AS CLM_RNDRG_PRVDR_TAX_NUM	
             ,RPAD(REPLACE(COALESCE(CL.GEO_RNDRG_SSA_STATE_CD,''),'~',''),2,' ')   AS GEO_RNDRG_SSA_STATE_CD

             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_ZIP5_CD,''),'~',''),5,' ') || 
              RPAD(REPLACE(COALESCE(CL.GEO_RNDRG_ZIP4_CD,''),'~',''),4,' ') AS GEO_RNDRG_ZIP9_CD	

             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,''),'~',''),2,' ') AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD	
             ,RPAD(REPLACE(COALESCE(CLP.CLM_PRVDR_SPCLTY_CD,''),'~',''),2,' ')          AS CLM_PRVDR_SPCLTY_CD	
             ,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_PRTCPTG_CD,''),'~',''),1,' ')    AS CLM_RNDRG_PRVDR_PRTCPTG_CD
             ,RPAD(REPLACE(COALESCE(CLP.CLM_PHYSN_ASTNT_CD,''),'~',''),1,' ')           AS CLM_PHYSN_ASTNT_CD
             
             ,TO_CHAR(COALESCE(CL.CLM_LINE_SRVC_UNIT_QTY,0),'S00000000000000.0000')   AS CLM_LINE_SRVC_UNIT_QTY
            
             ,RPAD(REPLACE(COALESCE(CLP.CLM_FED_TYPE_SRVC_CD,''),'~',''),1,' ') AS CLM_FED_TYPE_SRVC_CD
             ,RPAD(REPLACE(COALESCE(CLP.CLM_TYPE_SRVC_CD,''),'~',''),2,' ')     AS CLM_TYPE_SRVC_CD
             ,RPAD(REPLACE(COALESCE(CLP.CLM_PRCNG_LCLTY_CD,''),'~',''),2,' ')   AS CLM_PRCNG_LCLTY_CD
             ,RPAD(REPLACE(COALESCE(CL.CLM_POS_CD,''),'~',''),2,' ')            AS CLM_POS_CD
             
             ,RPAD(COALESCE(TO_CHAR(CL.CLM_LINE_FROM_DT, 'YYYYMMDD'),''),8,' ') AS CLM_LINE_FROM_DT
             ,RPAD(COALESCE(TO_CHAR(CL.CLM_LINE_THRU_DT, 'YYYYMMDD'),''),8,' ') AS CLM_LINE_THRU_DT
            
             ,RPAD(REPLACE(COALESCE(CL.CLM_LINE_HCPCS_CD,''),'~',''),5,' ') AS CLM_LINE_HCPCS_CD
             ,RPAD(REPLACE(COALESCE(CL.HCPCS_1_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_1_MDFR_CD
             ,RPAD(REPLACE(COALESCE(CL.HCPCS_2_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_2_MDFR_CD
             ,RPAD(REPLACE(COALESCE(CL.HCPCS_3_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_3_MDFR_CD
             ,RPAD(REPLACE(COALESCE(CL.HCPCS_4_MDFR_CD,''),'~',''),2,' ')   AS HCPCS_4_MDFR_CD

             ,TO_CHAR(COALESCE(CL.CLM_LINE_CVRD_PD_AMT,0),'S000000000.00')      AS CLM_LINE_CVRD_PD_AMT 
             ,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_PD_AMT,0),'S0000000000000.00')  AS CLM_LINE_BENE_PD_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_PMT_AMT,0),'S0000000000000.00') AS CLM_LINE_BENE_PMT_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_PRVDR_PMT_AMT,0),'S000000000.00')    AS CLM_LINE_PRVDR_PMT_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_MDCR_DDCTBL_AMT,0),'S000000000.00')  AS CLM_LINE_MDCR_DDCTBL_AMT
                            
             ,RPAD(REPLACE(COALESCE(CLP.CLM_PRMRY_PYR_CD,''),'~',''),1,' ')       AS CLM_PRMRY_PYR_CD
             ,TO_CHAR(COALESCE(CLP.CLM_BENE_PRMRY_PYR_PD_AMT,0),'S000000000.00')  AS CLM_BENE_PRMRY_PYR_PD_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_MDCR_COINSRNC_AMT,0),'S000000000.00')  AS CLM_LINE_MDCR_COINSRNC_AMT

             ,TO_CHAR(COALESCE(CLP.CLM_MDCR_PRMRY_PYR_ALOWD_AMT,0),'S0000000000000.00') AS CLM_MDCR_PRMRY_PYR_ALOWD_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_PTB_BLOOD_DDCTBL_QTY,0),'FM000')             AS CLM_LINE_PTB_BLOOD_DDCTBL_QTY
             ,TO_CHAR(COALESCE(CL.CLM_LINE_SBMT_CHRG_AMT,0),'S0000000000000.00')        AS CLM_LINE_SBMT_CHRG_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_ALOWD_CHRG_AMT,0),'S0000000000000.00')       AS CLM_LINE_ALOWD_CHRG_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_OTHR_TP_PD_AMT,0),'S0000000000000.00')       AS CLM_LINE_OTHR_TP_PD_AMT
                            
             ,TO_CHAR(COALESCE(C.CLM_OTHR_TP_PD_AMT,0),'S0000000000000.00')       AS CLM_OTHR_TP_PD_AMT
             ,TO_CHAR(COALESCE(CL.CLM_LINE_BENE_COPMT_AMT,0),'S0000000000000.00') AS CLM_LINE_BENE_COPMT_AMT

             ,RPAD(REPLACE(COALESCE(CLP.CLM_PMT_IND_CD,''),'~',''),1,' ')           AS CLM_PMT_IND_CD
             ,RPAD(REPLACE(COALESCE(CL.CLM_LINE_DGNS_CD,''),'~',''),7,' ')          AS CLM_LINE_DGNS_CD
             
             ,RPAD(COALESCE(TO_CHAR(CLP.CLM_LINE_CARR_DME_CVRG_BGN_DT,'YYYYMMDD'),''),8,' ') AS CLM_LINE_CARR_DME_CVRG_BGN_DT
             ,TO_CHAR(COALESCE(CLP.CLM_LINE_PRFNL_DME_PRICE_AMT,0),'S000000000.00')  AS CLM_LINE_PRFNL_DME_PRICE_AMT
             ,RPAD(REPLACE(COALESCE(CLP.CLM_DUP_CHK_IND_CD,''),'~',''),1,' ')          AS CLM_DUP_CHK_IND_CD
             
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PHYSN_ORG_NAME,''),'~',''),60,' ')     AS CLM_POS_PHYSN_ORG_NAME
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_1ST_NAME,''),'~',''),35,' ')     AS CLM_POS_PRVDR_1ST_NAME
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_MDL_NAME,''),'~',''),25,' ')     AS CLM_POS_PRVDR_MDL_NAME
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_1ST_LINE_ADR,''),'~',''),55,' ') AS CLM_POS_PRVDR_1ST_LINE_ADR
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_2ND_LINE_ADR,''),'~',''),55,' ') AS CLM_POS_PRVDR_2ND_LINE_ADR
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_CITY_NAME,''),'~',''),30,' ')    AS CLM_POS_PRVDR_CITY_NAME
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_USPS_STATE_CD,''),'~',''),2,' ') AS CLM_POS_PRVDR_USPS_STATE_CD
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_ZIP5_CD,''),'~',''),5,' ')       AS CLM_POS_PRVDR_ZIP5_CD
             ,RPAD(REPLACE(COALESCE(CLP.CLM_POS_PRVDR_ZIP4_CD,''),'~',''),4,' ')       AS CLM_POS_PRVDR_ZIP4_CD

             ,C.CLM_FINL_ACTN_IND
             ,RPAD(COALESCE(C.CLM_BENE_MBI_ID,''),11,' ') AS BENE_MBI_ID
             ,'END'
			 
                FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
                    ON C.GEO_BENE_SK      = CL.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
                    AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

                INNER JOIN IDRC_PRD.CMS_DIM_BENE_PRD.BENE B
                    ON C.BENE_SK = B.BENE_SK

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DT_SGNTR CDS
                    ON CDS.CLM_DT_SGNTR_SK = C.CLM_DT_SGNTR_SK

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PROD_MTRLZD  CPM
                    ON  C.GEO_BENE_SK     = CPM.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CPM.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CPM.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CPM.CLM_NUM_SK

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_DCMTN CDN
                    ON C.GEO_BENE_SK      = CDN.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CDN.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CDN.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CDN.CLM_NUM_SK

                INNER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_ZIP5_CD ZIP5
                    ON ZIP5.GEO_SK = C.GEO_BENE_SK

                LEFT OUTER JOIN IDRC_PRD.CMS_DIM_GEO_PRD.GEO_FIPS_CNTY_CD GFCC
                    ON GFCC.GEO_FIPS_CNTY_CD = ZIP5.GEO_FIPS_CNTY_CD
                    AND GFCC.GEO_FIPS_STATE_CD = ZIP5.GEO_FIPS_STATE_CD

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_PRFNL CLP
                    ON  CL.GEO_BENE_SK     = CLP.GEO_BENE_SK
                    AND CL.CLM_DT_SGNTR_SK = CLP.CLM_DT_SGNTR_SK
                    AND CL.CLM_TYPE_CD     = CLP.CLM_TYPE_CD
                    AND CL.CLM_NUM_SK      = CLP.CLM_NUM_SK
                    AND CL.CLM_LINE_NUM    = CLP.CLM_LINE_NUM

                INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_PRFNL PRFNL
                    ON  C.GEO_BENE_SK     = PRFNL.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = PRFNL.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = PRFNL.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = PRFNL.CLM_NUM_SK


      WHERE C.CLM_TYPE_CD IN (40,60)
        AND C.CLM_FINL_ACTN_IND = 'Y'
        AND C.CLM_FROM_DT BETWEEN TO_DATE('{FROM_DT}','YYYY-MM-DD') AND TO_DATE('{THRU_DT}','YYYY-MM-DD')

                 
