COPY INTO @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DOJ_STG/DOJ_SFUI_REQ126_QRY1_20260415.120000.txt.gz FROM (

SELECT 
     'START' AS START_IND
	,C.CLM_TYPE_CD
	,TO_CHAR(CL.CLM_LINE_NUM,'FM00000')         AS CLM_LINE_NUM
	,RPAD(C.CLM_CNTL_NUM,40,' ')                AS CLM_CNTL_NUM
    ,TO_CHAR(C.CLM_FROM_DT,'YYYYMMDD')          AS CLM_FROM_DT
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_TAX_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_TAX_NUM
	,RPAD(REPLACE(COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,''),'~',''),10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM
	,TO_CHAR(COALESCE(C.CLM_ALOWD_CHRG_AMT,0),'S0000000000000.00')         AS CLM_ALOWD_CHRG_AMT
    ,TO_CHAR(COALESCE(C.CLM_PMT_AMT,0),'S000000000.00')                    AS CLM_PMT_AMT 

	,TO_CHAR(COALESCE(CLOA.CLM_LINE_OTHR_APLD_AMT,0),'S0000000000.00')     AS CLM_LINE_OTHR_APLD_AMT
    -- We are only interested in V (Positive amt) and W (Negative amt)
	,RPAD(COALESCE(CLOA.CLM_LINE_OTHR_APLD_CD,''),2,' ')                   AS MIPS_PYMT_AMT_APPLIED_CD
	,'END' AS END_IND

FROM IDRC_PRD.CMS_FCT_CLM_PRD.CLM C    

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE CL
ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CL.CLM_NUM_SK
AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

INNER JOIN BIA_PRD.CMS_TARGET_XTR_PRD.DOJ_REQ126_FF FF
ON  TO_CHAR(C.CLM_FROM_DT,'YYYY')  =  FF.PYMT_YR
AND CL.CLM_RNDRG_PRVDR_TAX_NUM     =  FF.TIN_NUM
AND CL.CLM_RNDRG_PRVDR_NPI_NUM     =  FF.NPI_NUM
AND TO_CHAR(CL.CLM_FROM_DT,'YYYY') =  FF.PYMT_YR 
--AND FF.PYMT_YR = '2020'

INNER JOIN IDRC_PRD.CMS_FCT_CLM_PRD.CLM_LINE_OTHR_APLD CLOA
ON  CL.GEO_BENE_SK     = CLOA.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK = CLOA.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD     = CLOA.CLM_TYPE_CD
AND CL.CLM_NUM_SK      = CLOA.CLM_NUM_SK
AND CL.CLM_LINE_NUM    = CLOA.CLM_LINE_NUM
--AND CLOA.CLM_TYPE_CD     IN ('71','72')
AND CLOA.CLM_LINE_OTHR_APLD_CD IN ('V','W')

WHERE C.CLM_TYPE_CD IN ('71','72')
AND C.CLM_FINL_ACTN_IND = 'Y'

)

	FILE_FORMAT = (TYPE=CSV field_delimiter="|" ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY=none )
	SINGLE = TRUE  max_file_size=5368709120
;