/*
create or replace TABLE BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY (

	DSCHRG_DT          DATE         NOT NULL,
	MEDPAR_VSN         VARCHAR(1)   NOT NULL,
	HICN               VARCHAR(11)  NOT NULL,
	ADM_DT             DATE         NOT NULL,
	SPCL_UNIT_CD       CHAR(1),
	LENGTH_OF_STAY     NUMBER(38,0) NOT NULL,
	PRE_RLNG_SSI_DAYS  NUMBER(38,0) NOT NULL,
	UTLZTN_DAYS        NUMBER(38,0) NOT NULL,
	POST_RLNG_SSI_DAYS NUMBER(38,0) NOT NULL,
	GHO_PD_CD          CHAR(1),
	IME_AMT            NUMBER(9,0),
    DRG_AMT            NUMBER(9,0),
    MA_STUS            CHAR(1),
    DSCHRG_DAYS        NUMBER(38,0) NOT NULL,
    ADMT_DAYS          NUMBER(38,0) NOT NULL,
	FED_FY             VARCHAR(4)   NOT NULL,
  	PRVDR_ID           VARCHAR(6)   NOT NULL,
	MBI_ID             VARCHAR(11),
	ETL_LOAD_TS        DATETIME     NOT NULL,
	ETL_UPDT_TS        DATETIME,
	
    constraint PK_DSH_EDX_STAY primary key (PRVDR_ID, FED_FY, HICN) ENFORCED
);

create or replace TABLE BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_PRVDR (

  	PRVDR_ID           VARCHAR(6)   NOT NULL,
	PRVDR_ID_EFFCTV_DT DATE,
	PRVDR_ID_OBSOLT_DT DATE,
	PRVDR_NAME         VARCHAR(100),
	ETL_LOAD_TS        DATETIME,
	ETL_UPDT_TS        DATETIME,
	
    constraint PK_DSH_EDX_PRVDR primary key (PRVDR_ID ) NOT ENFORCED
);

                      --BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG
                      --BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG
CREATE OR REPLACE STAGE BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG
storage_integration = BIA_PROD_DATALAKE_XTR_SI
url = 's3://aws-hhs-cms-eadg-bia-ddom-extracts/xtr/DSH';

*/

/*

COPY INTO BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_PRVDR
  	(PRVDR_ID, PRVDR_ID_EFFCTV_DT, PRVDR_ID_OBSOLT_DT, PRVDR_NAME, ETL_LOAD_TS, ETL_UPDT_TS )
	FROM (SELECT f.$1
                   ,CASE WHEN f.$2 IS NULL THEN NULL
                         ELSE TO_DATE(TO_CHAR(f.$2),'DD-MON-YY') END
                   ,CASE WHEN f.$3 IS NULL THEN NULL
                         ELSE TO_DATE(TO_CHAR(f.$3),'DD-MON-YY') END
				   ,f.$4
				   ,TO_TIMESTAMP(SUBSTR(TO_CHAR(f.$5),1,18)||SUBSTR(TO_CHAR(f.$5),30,2),'DD-MON-YY HH24.MI.SS AM')
				   ,TO_TIMESTAMP(SUBSTR(TO_CHAR(f.$6),1,18)||SUBSTR(TO_CHAR(f.$6),30,2),'DD-MON-YY HH24.MI.SS AM')
          FROM @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG/dsh_edx_prvdr.csv f ) 
	FILE_FORMAT = (TYPE = CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"') FORCE=TRUE 
    ;

    SELECT * FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_PRVDR;
        
*/    
SELECT FED_FY, COUNT(*) FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY GROUP BY FED_FY ORDER BY FED_FY;
-- 240 Million rows between 2007 and 2022   
SELECT COUNT(*) FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY;

-- PROVIDER INFO
--SELECT COUNT(*)
--FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_PRVDR
--;

SELECT COUNT(DISTINCT PRVDR_ID)
FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY
;

SELECT *
FROM BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY
LIMIT 5;

--show stages like 'BIA_PRD_XTR_DSH_STG';

--0100012022-10-01R257270768A 2022-09-22 0000009000000000000090000009 +0000375+0000368N2022274202226520237TG1DT8QQ96010001
--010001,2022-10-01,R,257270768A ,2022-09-22, ,0000009,0000000,0000009,0000009,+0000375,+0000368,N,2022274,2022265,2023,7TG1DT8QQ96,010001

--MPRDSH-SSI-DAY-CNT = PRE_RLNG_SSI_DAYS;   MPRDSH-COV-DAYS = UTLZTN_DAYS
COPY INTO BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY
    (PRVDR_ID, DSCHRG_DT, MEDPAR_VSN, HICN, ADM_DT, SPCL_UNIT_CD, LENGTH_OF_STAY, PRE_RLNG_SSI_DAYS, UTLZTN_DAYS, POST_RLNG_SSI_DAYS,
     GHO_PD_CD, IME_AMT, DRG_AMT, MA_STUS,  DSCHRG_DAYS, ADMT_DAYS, FED_FY, MBI_ID, PRVDR_ID_BASE, ETL_LOAD_TS, ETL_UPDT_TS)
 
	FROM (SELECT SUBSTR(f.$1,1,6)   AS PRVDR_ID
                ,TO_DATE(SUBSTR(f.$1,7,10),'YYYY-MM-DD') AS DSCHRG_DT
                ,SUBSTR(f.$1,17,1)  AS MEDPAR_VSN
                ,SUBSTR(f.$1,18,11) AS HICN
                ,TO_DATE(SUBSTR(f.$1,29,10),'YYYY-MM-DD') AS ADM_DT
                ,SUBSTR(f.$1,39,1) AS SPCL_UNIT_CD
                ,SUBSTR(f.$1,40,7) AS LENGTH_OF_STAY
                ,SUBSTR(f.$1,47,7) AS PRE_RLNG_SSI_DAYS  
                ,SUBSTR(f.$1,54,7) AS UTLZTN_DAYS  
                ,SUBSTR(f.$1,61,7) AS POST_RLNG_SSI_DAYS  
                ,SUBSTR(f.$1,68,1) AS GHO_PD_CD          
                ,SUBSTR(f.$1,69,8) AS IME_AMT 
                ,SUBSTR(f.$1,77,8) AS DRG_AMT 
                ,SUBSTR(f.$1,85,1) AS MA_STUS 
                ,SUBSTR(f.$1,86,7) AS DSCHRG_DAYS 
                ,SUBSTR(f.$1,93,7) AS ADMT_DAYS 
                ,SUBSTR(f.$1,100,4)  AS FED_FY 
                ,SUBSTR(f.$1,104,11) AS MBI_ID
                ,SUBSTR(f.$1,115,6)  AS PRVDR_ID_BASE
                ,CURRENT_TIMESTAMP AS ETL_LOAD_TS
                ,NULL AS ETL_UPDT_TS
          FROM @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG/dsh_data_2023.txt  f ) 
	FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"') FORCE=TRUE 
    ;



/* "DSCHRG_DT","MEDPAR_VSN","HICN","ADM_DT","SPCL_UNIT_CD","LENGTH_OF_STAY","PRE_RLNG_SSI_DAYS","UTLZTN_DAYS","POST_RLNG_SSI_DAYS","GHO_PD_CD","IME_AMT","DRG_AMT","MA_STUS","DSCHRG_DAYS","ADMT_DAYS","FED_FY","PRVDR_ID","MBI_ID","ETL_LOAD_TS","ETL_UPDT_TS"
*/
/*
--01-OCT-87,"R","255289964A ",29-SEP-87," ",2,0,2,0,"0",0,1766," ",1987274,1987272,1988,"010001","           ",05-APR-18 01.20.58.659000000 PM,
COPY INTO BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY
    (DSCHRG_DT,	MEDPAR_VSN, HICN, ADM_DT, SPCL_UNIT_CD, LENGTH_OF_STAY, PRE_RLNG_SSI_DAYS, UTLZTN_DAYS, POST_RLNG_SSI_DAYS, 
     GHO_PD_CD, IME_AMT, DRG_AMT, MA_STUS, DSCHRG_DAYS, ADMT_DAYS, FED_FY, PRVDR_ID, MBI_ID, ETL_LOAD_TS, ETL_UPDT_TS )
    
	FROM (SELECT TO_DATE(TO_CHAR(f.$1),'DD-MON-YY'),f.$2,f.$3
    ,TO_DATE(TO_CHAR(f.$4),'DD-MON-YY'),f.$5,f.$6,f.$7,f.$8,f.$9
   ,f.$10,f.$11,f.$12,f.$13,f.$14,f.$15,f.$16,f.$17,f.$18
   ,TO_TIMESTAMP(SUBSTR(TO_CHAR(f.$19),1,18)||SUBSTR(TO_CHAR(f.$19),30,2),'DD-MON-YY HH24.MI.SS AM')
   ,TO_TIMESTAMP(SUBSTR(TO_CHAR(f.$20),1,18)||SUBSTR(TO_CHAR(f.$20),30,2),'DD-MON-YY HH24.MI.SS AM')
          FROM @BIA_PRD.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_DSH_STG/dsh_data_2022_v2.csv   f ) 
	FILE_FORMAT = (TYPE = CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"') FORCE=TRUE 
    ;

    select '|'||mbi_id||'|' 
    --SELECT COUNT(*)
    from  BIA_PRD.CMS_TARGET_XTR_PRD.DSH_EDX_STAY
    where fed_fy = '2022'
    --and trim(mbi_id) = ''
   ;
*/