#!/usr/bin/env python
########################################################################################################
# Name:  DUALS_MedAdv_PTB_Ext.py
#
# Desc: Duals Quarterly PTB Medicare Advantage extract 
#
# Created: Paul Baranoski 01/23/2025
# Modified:
#
# Paul Baranoski 2025-01-23 Create python code.
# Paul Baranoski 2026-06-04 Remove logic to execute SQL iteratively using a list of states.
########################################################################################################
import os
import sys
import datetime
from datetime import datetime

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

# Use Timestamp generated by shell script so logs and output files will have timestamp
ENVNAME=os.getenv('ENVNAME')
TMSTMP=os.getenv('TMSTMP')

CLM_FROM_DT=os.getenv('CLM_FROM_DT')
CLM_THRU_DT=os.getenv('CLM_THRU_DT')

CLM_PRD=os.getenv('CLM_PRD')

EXT_ST=os.getenv('EXT_ST')

# boolean - Python Exception status
bPythonExceptionOccurred=False

########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Execute SQL 
########################################################################################################

try:
    snowconvert_helpers.configure_log()
    con = snowconvert_helpers.log_on()   
    snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
    snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}  """, con,exit_on_error = True)


    print(f"Before Executing SQL DUALS_MedAdv BH-{EXT_ST} Extract" )

    #**************************************
    #   Extract NYSPAP Bene Contract data  
    #**************************************   
    snowconvert_helpers.execute_sql_statement(f"""COPY INTO @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_DUALS_MA_STG/DUALS_MedAdv_BH_{EXT_ST}_{CLM_PRD}_{TMSTMP}.txt.gz
                                                FROM (                                                               

                    SELECT  'BH' as record_type
                            ,C.CLM_TYPE_CD
                            ,RPAD(COALESCE(C.CLM_CNTL_NUM,' '),40,' ')                 AS  CLM_CNTL_NUM 
                            ,RPAD(COALESCE(BENE.BENE_EQTBL_BIC_HICN_NUM,' '),11,' ' )  AS  HICN_NUM
                            ,RPAD(COALESCE(BENE.BENE_MBI_ID,' '),11,' ')               AS  BENE_MBI_ID
                            
                            ,RPAD(COALESCE(BENE.BENE_LAST_NAME,' '),40,' ')     AS  BENE_LAST_NAME 
                            ,RPAD(COALESCE(BENE.BENE_1ST_NAME,' '),30,' ')      AS  BENE_1ST_NAME
                            ,RPAD(COALESCE(BENE.BENE_MIDL_NAME,' '),15,' ')     AS  BENE_MIDL_NAME
                            
                            ,CASE WHEN BENE.BENE_BRTH_DT IS NULL THEN REPEAT(8,' ') ELSE to_char(BENE.BENE_BRTH_DT,'YYYYMMDD') END AS CLM_PTNT_BIRTH_DT
                            ,RPAD(COALESCE(BENE.BENE_SEX_CD,' '),1,' ')         AS  BENE_SEX_CD  
                            
                            ,RPAD(COALESCE(EC.CLM_CNTRCT_NUM,' '),5,' ')        AS  BENE_CNTRCT_NUM
                            ,RPAD(CASE WHEN C.CLM_SBMTR_CNTRCT_NUM = BF.CNTRCT_PTC_NUM THEN BF.CNTRCT_PBP_PTC_NUM ELSE ' ' END,3,' ')  AS CNTRCT_PBP_PTC_NUM

                            ,CASE WHEN C.CLM_FROM_DT IS NULL THEN '10000101' ELSE to_char(C.CLM_FROM_DT,'YYYYMMDD') END AS CLM_FROM_DT
                            ,CASE WHEN C.CLM_THRU_DT IS NULL THEN '10000101' ELSE to_char(C.CLM_THRU_DT,'YYYYMMDD') END AS CLM_THRU_DT			

                            --- CLM-DGNS-D  ************
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_1_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_1_CD,' ')  END,7,' ')  AS CLM_DGNS_1_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_CD,' ')  END,7,' ')  AS CLM_DGNS_2_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_CD,' ')  END,7,' ')  AS CLM_DGNS_3_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_4_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_4_CD,' ')  END,7,' ')  AS CLM_DGNS_4_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_5_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_5_CD,' ')  END,7,' ')  AS CLM_DGNS_5_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_6_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_6_CD,' ')  END,7,' ')  AS CLM_DGNS_6_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_7_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_7_CD,' ')  END,7,' ')  AS CLM_DGNS_7_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_8_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_8_CD,' ')  END,7,' ')  AS CLM_DGNS_8_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_9_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_9_CD,' ')  END,7,' ')  AS CLM_DGNS_9_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_10_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_10_CD,' ') END,7,' ')  AS CLM_DGNS_10_CD	
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_11_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_11_CD,' ') END,7,' ')  AS CLM_DGNS_11_CD
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_12_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_12_CD,' ') END,7,' ')  AS CLM_DGNS_12_CD
                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_13_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_13_CD,' ') END,7,' ')  AS CLM_DGNS_13_CD

                            ,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~'      THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ')      AS CLM_DGNS_PRCDR_ICD_IND

                            ,RPAD(COALESCE(C.CLM_ADJSTMT_TYPE_CD,' '),1,' ')        AS CLM_ADJSTMT_TYPE_CD 
                            ,RPAD(REPLACE(COALESCE(EC.CLM_POS_CD,''),'~',''),2,' ') AS CLM_POS_CD

                            ,RPAD(COALESCE(CED.CLM_CHRT_RVW_SW,' '),1,' ')          AS CLM_CHRT_RVW_SW
                            ,RPAD(COALESCE(C.CLM_ORIG_CNTL_NUM,' '),40,' ')         AS CLM_ORIG_CNTL_NUM 

                            ,RPAD(COALESCE(C.CLM_BLG_PRVDR_NPI_NUM,' '),10, ' ')    AS CLM_BLG_PRVDR_NPI_NUM 
                            ,RPAD(COALESCE(C.CLM_BLG_PRVDR_NAME,' '),70,' ')        AS PRVDR_LGL_NAME
                            ,RPAD(COALESCE(PRVDR.PRVDR_MLG_TEL_NUM,' '),70,' ')     AS PRVDR_MLG_TEL_NUM 
                            
                            ,RPAD(COALESCE(C.CLM_BLG_PRVDR_TYPE_CD,' '),3,' ')      AS CLM_BLG_PRVDR_TYPE_CD   
                            
                            ,RPAD(COALESCE(PRVDR.GEO_PRVDR_PRCTC_SK,' '),5,' ')     AS CLM_BLG_PRVDR_ZIP5_CD

                            ,RPAD(COALESCE(C.CLM_RFRG_PRVDR_NPI_NUM,' '),10,' ')    AS  CLM_RFRG_PRVDR_NPI_NUM 
                            ,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_NPI_NUM,' '),10,' ')   AS  CLM_RNDRG_PRVDR_NPI_NUM

                            ,RPAD(COALESCE(CDN.CLM_PTNT_CNTL_NUM,' '),30,' ')       AS  CLM_PTNT_CNTL_NUM  
                            ,RPAD(CASE WHEN C.CLM_BLG_PRVDR_TXNMY_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_TXNMY_CD,' ') END,10,' ') AS CLM_BLG_PRVDR_TXNMY_CD
                            ,RPAD(REPLACE(COALESCE(C.CLM_BLG_FED_PRVDR_SPCLTY_CD,''),'~',''),2,' ') AS CLM_BLG_FED_PRVDR_SPCLTY_CD


                    FROM IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM C 
                    
                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR EC
                    ON  C.GEO_BENE_SK     = EC.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = EC.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = EC.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = EC.CLM_NUM_SK 
                    
                    INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE BENE             
                    ON C.BENE_SK = BENE.BENE_SK

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_DT_SGNTR CDS
                    ON C.CLM_DT_SGNTR_SK = CDS.CLM_DT_SGNTR_SK

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_PROD_MTRLZD PROD_MT
                    ON C.GEO_BENE_SK      = PROD_MT.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = PROD_MT.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = PROD_MT.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = PROD_MT.CLM_NUM_SK  

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR_DCMTN   CED
                    ON C.GEO_BENE_SK      = CED.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CED.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CED.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CED.CLM_NUM_SK

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_DCMTN CDN 
                    ON C.GEO_BENE_SK      = CDN.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CDN.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CDN.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CDN.CLM_NUM_SK
                       
                    INNER JOIN IDRC_{ENVNAME}.CMS_DIM_PRVDR_{ENVNAME}.PRVDR  PRVDR
                    ON C.CLM_BLG_PRVDR_NPI_NUM = PRVDR.PRVDR_NPI_NUM

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_BENE_MTRLZD_{ENVNAME}.BENE_FCT_TRANS BF
                    ON C.BENE_SK = BF.BENE_SK
                    AND C.CLM_FROM_DT BETWEEN BF.BENE_FCT_EFCTV_DT AND BF.BENE_FCT_OBSLT_DT 
                    AND BF.BENE_DUAL_STUS_CD IN ('01','02','03','04','05','06','08')
                 
                    LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_ZIP5_CD ZIP5 
                    ON C.GEO_BENE_SK = ZIP5.GEO_SK
                    
                    LEFT OUTER JOIN  IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_FIPS_STATE_CD ST
                    ON ZIP5.GEO_FIPS_STATE_CD = ST.GEO_FIPS_STATE_CD 

                    WHERE (C.CLM_FINL_ACTN_IND = 'Y' OR CED.CLM_CHRT_RVW_SW = 'Y')
                    AND C.CLM_TYPE_CD IN (4700,4800)                 
                    AND C.CLM_THRU_DT between '{CLM_FROM_DT}' AND '{CLM_THRU_DT}' 
                    AND ST.GEO_USPS_STATE_CD = '{EXT_ST}'                      
                 
                    ORDER BY 1,2,3,4 

 )
                        FILE_FORMAT = (TYPE = CSV field_delimiter = none  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
                        SINGLE = TRUE  max_file_size=5368709120  """, con, exit_on_error=True)


    print(f"Before Executing SQL DUALS_MedAdv BL-{EXT_ST} Extract" )

    #**************************************
    #   Extract NYSPAP Bene Contract data  
    #**************************************   
    snowconvert_helpers.execute_sql_statement(f"""COPY INTO @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_DUALS_MA_STG/DUALS_MedAdv_BL_{EXT_ST}_{CLM_PRD}_{TMSTMP}.txt.gz
                                                FROM (                                                               

                    SELECT  'BL' as record_type
                            ,C.CLM_TYPE_CD
                            ,RPAD(COALESCE(C.CLM_CNTL_NUM,' '),40,' ')         AS CLM_CNTL_NUM
                            ,TO_CHAR(CL.CLM_LINE_NUM,'FM00')                     AS CLM_LINE_NUM
                            ,RPAD(REPLACE(COALESCE(CL.CLM_LINE_HCPCS_CD,''),'~',''),5,' ')     AS CLM_LINE_HCPCS_CD
                            ,RPAD(REPLACE(COALESCE(CL.HCPCS_1_MDFR_CD,''),'~',''),2,' ')       AS HCPCS_1_MDFR_CD
                            ,RPAD(REPLACE(COALESCE(CL.HCPCS_2_MDFR_CD,''),'~',''),2,' ')       AS HCPCS_2_MDFR_CD
                            ,RPAD(REPLACE(COALESCE(CL.HCPCS_3_MDFR_CD,''),'~',''),2,' ')       AS HCPCS_3_MDFR_CD
                            ,RPAD(REPLACE(COALESCE(CL.HCPCS_4_MDFR_CD,''),'~',''),2,' ')       AS HCPCS_4_MDFR_CD
                            ,RPAD(REPLACE(COALESCE(CL.CLM_LINE_NDC_CD,' '),'~',' '),11,' ')    AS CLM_LINE_NDC_CD
                            -- legacy field length was 10
                            ,to_char(COALESCE(CL.CLM_LINE_NDC_QTY,0),'FM000000.000') AS  CLM_LINE_NDC_QTY
                            ,TO_CHAR(COALESCE(CL.CLM_LINE_SRVC_UNIT_QTY,0),'FM0000000.00')       AS CLM_LINE_SRVC_UNIT_QTY
                            ,RPAD(REPLACE(COALESCE(C.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,''),'~',''),2,' ')  AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD


                    FROM IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM C 
                    
                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR EC
                    ON  C.GEO_BENE_SK     = EC.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = EC.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = EC.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = EC.CLM_NUM_SK 

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE CL
                    ON  C.GEO_BENE_SK     = CL.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CL.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CL.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CL.CLM_NUM_SK 
                    AND C.CLM_FROM_DT     = CL.CLM_FROM_DT

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR_DCMTN   CED
                    ON C.GEO_BENE_SK      = CED.GEO_BENE_SK
                    AND C.CLM_DT_SGNTR_SK = CED.CLM_DT_SGNTR_SK
                    AND C.CLM_TYPE_CD     = CED.CLM_TYPE_CD
                    AND C.CLM_NUM_SK      = CED.CLM_NUM_SK

                    INNER JOIN IDRC_{ENVNAME}.CMS_FCT_BENE_MTRLZD_{ENVNAME}.BENE_FCT_TRANS BF
                    ON C.BENE_SK = BF.BENE_SK
                    AND C.CLM_FROM_DT BETWEEN BF.BENE_FCT_EFCTV_DT AND BF.BENE_FCT_OBSLT_DT 
                    AND BF.BENE_DUAL_STUS_CD IN ('01','02','03','04','05','06','08')
                 
                    LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_ZIP5_CD ZIP5 
                    ON C.GEO_BENE_SK = ZIP5.GEO_SK
                    
                    LEFT OUTER JOIN  IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_FIPS_STATE_CD ST
                    ON ZIP5.GEO_FIPS_STATE_CD = ST.GEO_FIPS_STATE_CD 

                    WHERE (C.CLM_FINL_ACTN_IND = 'Y' OR CED.CLM_CHRT_RVW_SW = 'Y')
                    AND C.CLM_TYPE_CD IN (4700,4800)                 

                    AND C.CLM_THRU_DT between '{CLM_FROM_DT}' AND '{CLM_THRU_DT}' 
                    AND ST.GEO_USPS_STATE_CD = '{EXT_ST}'                           
                 
                    ORDER BY 1,2,3,4 

    )
                        FILE_FORMAT = (TYPE = CSV field_delimiter = none  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
                        SINGLE = TRUE  max_file_size=5368709120  """, con, exit_on_error=True)
  


    #**************************************
    # End Application
    #**************************************    
    snowconvert_helpers.quit_application()
    

except Exception as e:
    print(e)

    # Let shell script know that python code failed.
    bPythonExceptionOccurred=True   

finally:
    if con is not None:
      con.close()

    # Let shell script know that python code failed.      
    if bPythonExceptionOccurred == True:
      sys.exit(12) 
    else:   
      snowconvert_helpers.quit_application()

