#!/usr/bin/env python
########################################################################################################
# Name: PSP_SF_Table_Load.py
#
# Desc: PSP_SF_Table_Load.py will load PSPS_EXT_DATA with Extract data.
#
# Modified:
#
# Paul Baranoski 2025-07-11 Create SQL
########################################################################################################
import os
import sys
import datetime
from datetime import datetime
import sendEmail

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

# Use Timestamp generated by shell script so logs and output files will have timestamp
ENVNAME=os.getenv('ENVNAME')

PSPS_EXT_DT_YYYY=os.getenv('PSPS_EXT_DT_YYYY')
PSPS_EXT_QTR=os.getenv('PSPS_EXT_QTR')
PSPS_EXT_RUN_DT=os.getenv('PSPS_EXT_RUN_DT')
PSPS_EXT_FILENAME=os.getenv('PSPS_EXT_FILENAME')


# boolean - Python Exception status
bPythonExceptionOccurred=False

     
########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Method to execute the extract SQL using Timestamp 
########################################################################################################
try:
   snowconvert_helpers.configure_log()
   con = snowconvert_helpers.log_on()   
   snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
   snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}""", con,exit_on_error = True)

   ## Delete records from TARGET TABLE ##
   snowconvert_helpers.execute_sql_statement(f"""DELETE FROM BIA_{ENVNAME}.CMS_EXTNL_XTR_{ENVNAME}.PSPS_EXT_DATA 
                                                 WHERE EXT_DT_YYYY = '{PSPS_EXT_DT_YYYY}' 
                                                   AND EXT_QTR     = '{PSPS_EXT_QTR}'    
                                                   AND EXT_RUN_DT  = TO_DATE('{PSPS_EXT_RUN_DT}','YYYYMMDD')                                                     
                                              """, con,exit_on_error = True)
                                                        
   ## INSERT Extract FILE value into TO THE TARGET TABLE ##
   snowconvert_helpers.execute_sql_statement(f""" COPY INTO BIA_{ENVNAME}.CMS_EXTNL_XTR_{ENVNAME}.PSPS_EXT_DATA
                                                      ( EXT_DT_YYYY, EXT_QTR, EXT_RUN_DT,
                                                        HCPCS_CODE, HCPCS_INIT_MODIFIER_CODE, PROVIDER_SPECIALTY_CODE,
                                                        CARRIER_NUMBER, PRICING_LOCALITY_CODE, TYPE_OF_SERVICE_CODE,
                                                        PLACE_OF_SERVICE_CODE, HCPCS_SEC_MODIFIER_CODE,
                                                        SUBMITTED_SERVICE_COUNT, SUBMITTED_CHARGE_AMOUNT,
                                                        ALLOWED_CHARGE_AMOUNT, 
                                                        DENIED_SERVICES_COUNT, DENIED_CHARGE_AMOUNT,
                                                        ASSIGNED_SERVICES_COUNT, NCH_PAYMENT_AMOUNT,
                                                        HCPCS_ASC_INDICATOR_CODE, ERROR_INDICATOR_CODE, BETOS )
    
                                                FROM (SELECT '{PSPS_EXT_DT_YYYY}' AS EXT_DT_YYYY
                                                            ,'{PSPS_EXT_QTR}'     AS EXT_QTR
                                                            ,TO_DATE('{PSPS_EXT_RUN_DT}','YYYYMMDD')  AS EXT_RUN_DT
                                                            ,SUBSTR(f.$1,1,5)    AS HCPCS_CODE
                                                            ,SUBSTR(f.$1,6,2)    AS HCPCS_INIT_MODIFIER_CODE
                                                            ,SUBSTR(f.$1,8,2)    AS PROVIDER_SPECIALTY_CODE
                                                            ,SUBSTR(f.$1,10,5)   AS CARRIER_NUMBER
                                                            ,SUBSTR(f.$1,15,2)   AS PRICING_LOCALITY_CODE
                                                            ,SUBSTR(f.$1,17,1)   AS TYPE_OF_SERVICE_CODE
                                                            
                                                            ,SUBSTR(f.$1,18,2)   AS PLACE_OF_SERVICE_CODE
                                                            ,SUBSTR(f.$1,20,2)   AS HCPCS_SEC_MODIFIER_CODE
                                                            ,SUBSTR(f.$1,22,14)  AS SUBMITTED_SERVICE_COUNT
                                                            ,SUBSTR(f.$1,36,15)  AS SUBMITTED_CHARGE_AMOUNT
                                                            ,SUBSTR(f.$1,51,15)  AS ALLOWED_CHARGE_AMOUNT
                                                            ,SUBSTR(f.$1,66,14)  AS DENIED_SERVICES_COUNT
                                                            ,SUBSTR(f.$1,80,15)  AS DENIED_CHARGE_AMOUNT
                                                            ,SUBSTR(f.$1,95,14)  AS ASSIGNED_SERVICES_COUNT
                                                            ,SUBSTR(f.$1,109,15) AS NCH_PAYMENT_AMOUNT
                                                            ,SUBSTR(f.$1,124,1)  AS HCPCS_ASC_INDICATOR_CODE
                                                            ,SUBSTR(f.$1,125,1)  AS ERROR_INDICATOR_CODE
                                                            ,SUBSTR(f.$1,127,1)  AS BETOS
                                     
                                                        FROM @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_EFT_FILES_STG/{PSPS_EXT_FILENAME}  f)
                                                        FILE_FORMAT = (TYPE=CSV  EMPTY_FIELD_AS_NULL = false FIELD_DELIMITER='|') FORCE=TRUE """, con,exit_on_error = True)

   
   #**************************************
   # End Application
   #**************************************    
   snowconvert_helpers.quit_application()
   
except Exception as e:
   print(e)
   
   # Let shell script know that python code failed.
   bPythonExceptionOccurred=True   
   
finally:
   if con is not None:
      con.close()

   # Let shell script know that python code failed.      
   if bPythonExceptionOccurred == True:
      sys.exit(12) 
   else:   
      snowconvert_helpers.quit_application()

