--create or replace TABLE BIA_PRD.CMS_EXTERNAL_XTR_PRD.PSPS_EXT_DATA (
create or replace TABLE BIA_PRD.CMS_EXTNL_XTR.PSPS_EXT_DATA (
	EXT_DT_YYYY CHAR(4) NOT NULL,
    EXT_QTR CHAR(2) NOT NULL,
    EXT_RUN_DT DATE NOT NULL,
    HCPCS_CODE VARCHAR(5) NOT NULL,
    HCPCS_INIT_MODIFIER_CODE VARCHAR(2) NOT NULL,
    PROVIDER_SPECIALTY_CODE VARCHAR(2) NOT NULL,
    CARRIER_NUMBER VARCHAR(5) NOT NULL,
    PRICING_LOCALITY_CODE VARCHAR(2) NOT NULL,
    TYPE_OF_SERVICE_CODE VARCHAR(1) NOT NULL,
    PLACE_OF_SERVICE_CODE VARCHAR(2) NOT NULL,
    HCPCS_SEC_MODIFIER_CODE VARCHAR(2) NOT NULL,
    SUBMITTED_SERVICE_COUNT DECIMAL(18,2) NOT NULL,
    SUBMITTED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    ALLOWED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    DENIED_SERVICES_COUNT NUMBER(8) NOT NULL,
    DENIED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    ASSIGNED_SERVICES_COUNT DECIMAL(18,2) NOT NULL,
    NCH_PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    HCPCS_ASC_INDICATOR_CODE VARCHAR(1) NOT NULL,
    ERROR_INDICATOR_CODE VARCHAR(2) NOT NULL,
    BETOS VARCHAR(3) NOT NULL,
	constraint PK_PSPS_EXT_DATA primary key (EXT_DT_YYYY, EXT_QTR, EXT_RUN_DT)

);


COPY INTO BIA_PRD.CMS_EXTNL_XTR_PRD.PSPS_EXT_DATA
              ( EXT_DT_YYYY, EXT_QTR, EXT_RUN_DT,
                HCPCS_CODE, HCPCS_INIT_MODIFIER_CODE, PROVIDER_SPECIALTY_CODE,
                CARRIER_NUMBER, PRICING_LOCALITY_CODE, TYPE_OF_SERVICE_CODE,
                PLACE_OF_SERVICE_CODE, HCPCS_SEC_MODIFIER_CODE,
                SUBMITTED_SERVICE_COUNT, SUBMITTED_CHARGE_AMOUNT,
                ALLOWED_CHARGE_AMOUNT, 
                DENIED_SERVICES_COUNT, DENIED_CHARGE_AMOUNT,
                ASSIGNED_SERVICES_COUNT, NCH_PAYMENT_AMOUNT,
                HCPCS_ASC_INDICATOR_CODE, ERROR_INDICATOR_CODE, BETOS )
    
            FROM (SELECT '2025' AS EXT_DT_YYYY
                        ,'Q6'   AS EXT_QTR
                        ,TO_DATE('20250725','YYYYMMDD')  AS EXT_RUN_DT
                        ,SUBSTR(f.$1,1,5)    AS HCPCS_CODE
                        ,SUBSTR(f.$1,6,2)    AS HCPCS_INIT_MODIFIER_CODE
                        ,SUBSTR(f.$1,8,2)    AS PROVIDER_SPECIALTY_CODE
                        ,SUBSTR(f.$1,10,5)   AS CARRIER_NUMBER
                        ,SUBSTR(f.$1,15,2)   AS PRICING_LOCALITY_CODE
                        ,SUBSTR(f.$1,17,1)   AS TYPE_OF_SERVICE_CODE
                        
                        ,SUBSTR(f.$1,18,2)   AS PLACE_OF_SERVICE_CODE
                        ,SUBSTR(f.$1,20,2)   AS HCPCS_SEC_MODIFIER_CODE
                        ,SUBSTR(f.$1,22,14)  AS SUBMITTED_SERVICE_COUNT
                        ,SUBSTR(f.$1,36,15)  AS SUBMITTED_CHARGE_AMOUNT
                        ,SUBSTR(f.$1,51,15)  AS ALLOWED_CHARGE_AMOUNT
                        ,SUBSTR(f.$1,66,14)  AS DENIED_SERVICES_COUNT
                        ,SUBSTR(f.$1,80,15)  AS DENIED_CHARGE_AMOUNT
                        ,SUBSTR(f.$1,95,14)  AS ASSIGNED_SERVICES_COUNT
                        ,SUBSTR(f.$1,109,15) AS NCH_PAYMENT_AMOUNT
                        ,SUBSTR(f.$1,124,1)  AS HCPCS_ASC_INDICATOR_CODE
                        ,SUBSTR(f.$1,125,1)  AS ERROR_INDICATOR_CODE
                        ,SUBSTR(f.$1,127,1)  AS BETOS
 
                    FROM @BIA_DEV.CMS_STAGE_XTR_PRD.BIA_PRD_XTR_EFT_FILES_STG/P#EFT.ON.PSPSQ6.D250725.T0900021  f)
                    FILE_FORMAT = (TYPE=CSV ) FORCE=TRUE

/*



create or replace TABLE BIA_DEV.CMS_EXTNL_XTR_DEV.PSPS_EXT_DATA (
	EXT_DT_YYYY CHAR(4) NOT NULL,
    EXT_QTR CHAR(2) NOT NULL,
    EXT_RUN_DT DATE NOT NULL,
    HCPCS_CODE VARCHAR(5) NOT NULL,
    HCPCS_INIT_MODIFIER_CODE VARCHAR(2) NOT NULL,
    PROVIDER_SPECIALTY_CODE VARCHAR(2) NOT NULL,
    CARRIER_NUMBER VARCHAR(5) NOT NULL,
    PRICING_LOCALITY_CODE VARCHAR(2) NOT NULL,
    TYPE_OF_SERVICE_CODE VARCHAR(1) NOT NULL,
    PLACE_OF_SERVICE_CODE VARCHAR(2) NOT NULL,
    HCPCS_SEC_MODIFIER_CODE VARCHAR(2) NOT NULL,
    SUBMITTED_SERVICE_COUNT DECIMAL(18,2) NOT NULL,
    SUBMITTED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    ALLOWED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    DENIED_SERVICES_COUNT NUMBER(8) NOT NULL,
    DENIED_CHARGE_AMOUNT DECIMAL(18,2) NOT NULL,
    ASSIGNED_SERVICES_COUNT DECIMAL(18,2) NOT NULL,
    NCH_PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    HCPCS_ASC_INDICATOR_CODE VARCHAR(1) NOT NULL,
    ERROR_INDICATOR_CODE VARCHAR(2) NOT NULL,
    BETOS VARCHAR(3) NOT NULL,
	constraint PK_PSPS_EXT_DATA primary key (EXT_DT_YYYY, EXT_QTR, EXT_RUN_DT)
);

IDRBI-99641 (Create SF table in all environments, create SF stages)
*/

--BIA_TST.CMS_EXTNL_XTR_TST.PSPS_EXT_DATA