#!/usr/bin/env python
########################################################################################################
# Name:  SAFENC_HHA_Extract.py
#
# Desc: SAF Encounter HHA Extract script.
#
# Created: Viren Khanna  07/03/2023  
# Modified: 
#
# Paul Baranoski 2023-08-04 Update SQL Amount fields formatting to display sign as +/-, and remove one significant 
#                           digit.

# Viren Khanna 2023-08-17 Updated code for Bene Race CD 

########################################################################################################
import os
import sys
import datetime
from datetime import datetime

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

TMSTMP=os.getenv('TMSTMP')
ENVNAME=os.getenv('ENVNAME')
EXT_FROM_DT=os.getenv('EXT_FROM_DT')
EXT_TO_DT=os.getenv('EXT_TO_DT')
#Y21QTR1
RNG_LIT=os.getenv('RNG_LIT')
STUS_LIT=os.getenv('STUS_LIT')
CLM_TYPE_LIT=os.getenv('CLM_TYPE_LIT')
YYYY=os.getenv('YYYY')


# boolean - Python Exception status
bPythonExceptionOccurred=False

########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Method to execute the extract SQL using Timestamp 
########################################################################################################
try:
   snowconvert_helpers.configure_log()
   con = snowconvert_helpers.log_on()   
   snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
   snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}  """, con,exit_on_error = True)

   snowconvert_helpers.execute_sql_statement(f"""COPY INTO @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_SAFENCHHA_STG/SAFENC_HHA_{STUS_LIT}_{RNG_LIT}_{TMSTMP}.txt.gz
                                                FROM (

WITH CLM_ENC_CLMS AS (

	SELECT   C.GEO_BENE_SK
			,C.CLM_DT_SGNTR_SK
			,C.CLM_TYPE_CD
			,C.CLM_NUM_SK
			,C.CLM_RLT_COND_SGNTR_SK
			,C.CLM_RLT_OCRNC_SGNTR_SK
			,C.CLM_OCRNC_SGNTR_SK
		  
	FROM IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM C

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR CE
	ON  C.GEO_BENE_SK     = CE.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CE.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CE.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CE.CLM_NUM_SK

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE_ENCTR CLE
	ON  C.GEO_BENE_SK      = CLE.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = CLE.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = CLE.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = CLE.CLM_NUM_SK

	WHERE C.CLM_TYPE_CD IN (4032,4033)
	--and C.CLM_FINL_ACTN_IND = 'Y'
	AND CE.CLM_EDPS_STUS_CD = 'A'
	AND CLE.CLM_LINE_ENCTR_STUS_CD <> '84'
	AND C.CLM_THRU_DT BETWEEN to_date('{EXT_FROM_DT}','YYYY-MM-DD') AND to_date('{EXT_TO_DT}','YYYY-MM-DD') 


)

,ENC_CLM_PROD_INFO  AS (

	SELECT  
		 C.GEO_BENE_SK
		,C.CLM_DT_SGNTR_SK
		,C.CLM_TYPE_CD
		,C.CLM_NUM_SK
		,CASE WHEN PROD.CLM_PROD_TYPE_CD = '~'       THEN NULL ELSE PROD.CLM_PROD_TYPE_CD END AS CLM_PROD_TYPE_CD 
		,CASE WHEN PROD.CLM_DGNS_PRCDR_ICD_IND = '~' THEN NULL ELSE PROD.CLM_DGNS_PRCDR_ICD_IND END AS CLM_DGNS_PRCDR_ICD_IND 
		,PROD.CLM_VAL_SQNC_NUM
                ,CASE WHEN PROD.CLM_PRCDR_CD = '~' THEN NULL ELSE PROD.CLM_PRCDR_CD END AS CLM_PRCDR_CD
                ,PROD.CLM_PRCDR_PRFRM_DT
		,CASE WHEN PROD.CLM_DGNS_CD = '~' THEN NULL ELSE PROD.CLM_DGNS_CD END AS CLM_DGNS_CD 
		,CASE WHEN PROD.CLM_POA_IND = '~' THEN NULL ELSE PROD.CLM_POA_IND END AS CLM_POA_IND 	
	
	FROM CLM_ENC_CLMS C 
	
	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_PROD PROD
	ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
	AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK
	
        
)

,TMP_POA_DGNS_IND_HHA AS (

	
	SELECT
		   GEO_BENE_SK
		  ,CLM_DT_SGNTR_SK
		  ,CLM_TYPE_CD
		  ,CLM_NUM_SK
	  
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_POA_IND END) AS POA_DGNS_IND_1
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN CLM_POA_IND END) AS POA_DGNS_IND_2
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN CLM_POA_IND END) AS POA_DGNS_IND_3
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN CLM_POA_IND END) AS POA_DGNS_IND_4
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN CLM_POA_IND END) AS POA_DGNS_IND_5
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN CLM_POA_IND END) AS POA_DGNS_IND_6
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN CLM_POA_IND END) AS POA_DGNS_IND_7
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN CLM_POA_IND END) AS POA_DGNS_IND_8
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN CLM_POA_IND END) AS POA_DGNS_IND_9
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN CLM_POA_IND END) AS POA_DGNS_IND_10
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11 THEN CLM_POA_IND END) AS POA_DGNS_IND_11
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12 THEN CLM_POA_IND END) AS POA_DGNS_IND_12
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 13 THEN CLM_POA_IND END) AS POA_DGNS_IND_13
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 14 THEN CLM_POA_IND END) AS POA_DGNS_IND_14
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 15 THEN CLM_POA_IND END) AS POA_DGNS_IND_15
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 16 THEN CLM_POA_IND END) AS POA_DGNS_IND_16
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 17 THEN CLM_POA_IND END) AS POA_DGNS_IND_17
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 18 THEN CLM_POA_IND END) AS POA_DGNS_IND_18
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 19 THEN CLM_POA_IND END) AS POA_DGNS_IND_19
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 20 THEN CLM_POA_IND END) AS POA_DGNS_IND_20
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 21 THEN CLM_POA_IND END) AS POA_DGNS_IND_21
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 22 THEN CLM_POA_IND END) AS POA_DGNS_IND_22
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 23 THEN CLM_POA_IND END) AS POA_DGNS_IND_23
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 24 THEN CLM_POA_IND END) AS POA_DGNS_IND_24
		  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 25 THEN CLM_POA_IND END) AS POA_DGNS_IND_25  
	  
	FROM ENC_CLM_PROD_INFO  
	
	WHERE CLM_PROD_TYPE_CD = 'E'
	AND   CLM_VAL_SQNC_NUM <= 12

	GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK

	
)

,TMP_DGNS_E_CD_HHA AS (


	SELECT
	   GEO_BENE_SK
	  ,CLM_DT_SGNTR_SK
	  ,CLM_TYPE_CD
	  ,CLM_NUM_SK
	  
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_DGNS_PRCDR_ICD_IND END) AS  CLM_DGNS_PRCDR_ICD_IND
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_1
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_2
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_3
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_4
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_5
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_6
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_7
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_8
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN CLM_DGNS_CD END)  AS DGNS_E_CD_9
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN CLM_DGNS_CD END)  AS DGNS_E_CD_10
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11 THEN CLM_DGNS_CD END)  AS DGNS_E_CD_11
	  ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12 THEN CLM_DGNS_CD END)  AS DGNS_E_CD_12  

	FROM ENC_CLM_PROD_INFO C  

	WHERE CLM_PROD_TYPE_CD = 'E'
	AND   CLM_VAL_SQNC_NUM <= 12

	GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK


)

,TMP_PRCDR_CD_HHA AS (
       

            SELECT
		 GEO_BENE_SK
		,CLM_DT_SGNTR_SK
		,CLM_TYPE_CD
		,CLM_NUM_SK
                ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN REPLACE(CLM_DGNS_PRCDR_ICD_IND,'~',' ') END) AS CLM_DGNS_PRCDR_ICD_IND
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_1
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_2
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_3
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_4
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_5
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_6
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_7
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_8
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_9
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_10
            ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_11
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_12
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 13  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_13
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 14  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_14
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 15  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_15
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 16  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_16
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 17  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_17
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 18  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_18
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 19  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_19
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 20 THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_20
            ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 21  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_21
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 22  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_22
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 23  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_23
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 24  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_24
	    ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 25  THEN REPLACE(CLM_PRCDR_CD,'~',' ') END) AS PRCDR_CD_25
                ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_1
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_2
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_3
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_4
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_5
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_6
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_7
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_8
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_9
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_10
                ,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_11
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_12
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 13  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_13
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 14  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_14
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 15  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_15
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 16  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_16
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 17  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_17
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 18  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_18
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 19  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_19
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 20  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_20
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 21  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_21
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 22  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_22
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 23  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_23
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 24  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_24
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 25  THEN TO_CHAR(CLM_PRCDR_PRFRM_DT,'YYYYMMDD') ELSE '10000101' END) AS PRCDR_PRFRM_DT_25

              FROM ENC_CLM_PROD_INFO  
	
	      WHERE CLM_PROD_TYPE_CD = 'S'
	      AND   CLM_VAL_SQNC_NUM <= 25

	      GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK
)

,TMP_POA_DGNS_E_IND_HHA AS (

	SELECT
		 GEO_BENE_SK
		,CLM_DT_SGNTR_SK
		,CLM_TYPE_CD
		,CLM_NUM_SK
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 1  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_1
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 2  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_2
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 3  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_3
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 4  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_4
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 5  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_5
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 6  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_6
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 7  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_7
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 8  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_8
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 9  THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_9
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 10 THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_10
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 11 THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_11
		,MAX(CASE WHEN CLM_VAL_SQNC_NUM = 12 THEN CLM_POA_IND END)  AS POA_DGNS_E_IND_12	

	FROM ENC_CLM_PROD_INFO C  

	WHERE C.CLM_PROD_TYPE_CD = 'E'
	AND   C.CLM_VAL_SQNC_NUM <= 12

	GROUP BY GEO_BENE_SK, CLM_DT_SGNTR_SK, CLM_TYPE_CD, CLM_NUM_SK


)

,TMP_RLT_COND_SGNTR_MBR_HHA AS (


	SELECT C.CLM_RLT_COND_SGNTR_SK
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 1  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_1
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 2  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_2
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 3  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_3
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 4  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_4
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 5  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_5
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 6  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_6
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 7  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_7
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 8  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_8
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 9  THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_9
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 10 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_10
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 11 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_11
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 12 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_12
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 13 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_13
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 14 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_14
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 15 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_15
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 16 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_16
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 17 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_17
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 18 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_18
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 19 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_19
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 20 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_20
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 21 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_21
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 22 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_22
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 23 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_23
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 24 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_24
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 25 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_25
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 26 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_26
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 27 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_27
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 28 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_28
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 29 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_29
		  ,MAX(CASE WHEN CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM = 30 THEN REPLACE(CRCSM.CLM_RLT_COND_CD,'~',' ') END) AS RLT_COND_CD_30
	  

	FROM CLM_ENC_CLMS C 

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_RLT_COND_SGNTR_MBR CRCSM
	ON  C.CLM_RLT_COND_SGNTR_SK  = CRCSM.CLM_RLT_COND_SGNTR_SK

	WHERE CRCSM.CLM_RLT_COND_SGNTR_SQNC_NUM <= 30

	GROUP BY C.CLM_RLT_COND_SGNTR_SK

)

,TMP_RLT_OCRNC_SGNTR_MBR_HHA_TMP AS (


	SELECT C.CLM_RLT_OCRNC_SGNTR_SK
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 1  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_1
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 2  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_2
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 3  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_3
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 4  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_4
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 5  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_5
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 6  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_6
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 7  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_7
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 8  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_8
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 9  THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_9
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 10 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_10
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 11 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_11
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 12 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_12
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 13 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_13
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 14 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_14
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 15 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_15
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 16 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_16
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 17 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_17
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 18 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_18
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 19 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_19
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 20 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_20
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 21 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_21
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 22 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_22
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 23 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_23
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 24 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_24
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 25 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_25
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 26 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_26
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 27 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_27
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 28 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_28
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 29 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_29
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 30 THEN REPLACE(CROSM.CLM_RLT_OCRNC_CD,'~',' ') END) AS RLT_OCRNC_CD_30
		
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 1  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_1
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 2  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_2
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 3  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_3
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 4  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_4
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 5  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_5
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 6  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_6
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 7  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_7
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 8  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_8
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 9  THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_9
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 10 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_10
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 11 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_11
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 12 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_12
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 13 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_13
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 14 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_14
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 15 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_15
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 16 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_16
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 17 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_17
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 18 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_18
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 19 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_19
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 20 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_20
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 21 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_21
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 22 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_22
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 23 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_23
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 24 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_24
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 25 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_25
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 26 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_26
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 27 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_27
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 28 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_28
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 29 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_29
		,MAX(CASE WHEN CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM = 30 THEN TO_CHAR(CROSM.CLM_RLT_OCRNC_DT,'YYYYMMDD') ELSE '10000101' END)  AS RLT_OCRNC_DT_30
	  

	FROM CLM_ENC_CLMS C 
	
	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_RLT_OCRNC_SGNTR_MBR CROSM
	ON  C.CLM_RLT_OCRNC_SGNTR_SK  = CROSM.CLM_RLT_OCRNC_SGNTR_SK

	WHERE CROSM.CLM_RLT_OCRNC_SGNTR_SQNC_NUM <= 30

	GROUP BY C.CLM_RLT_OCRNC_SGNTR_SK
)

,TMP_OCRNC_SGNTR_MBR_HHA AS  (

	SELECT C.CLM_OCRNC_SGNTR_SK 
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_1
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_2
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_3
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_4
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_5
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_6
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_7
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_8
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_9
	    ,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN REPLACE(COSM.CLM_OCRNC_SPAN_CD,'~',' ') END) AS OCRNC_SPAN_CD_10


		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_1
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_2
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_3
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_4
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_5
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_6
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_7
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_8
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_9
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_FROM_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_FROM_DT_10

		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 1  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_1
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 2  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_2
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 3  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_3
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 4  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_4
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 5  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_5
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 6  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_6
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 7  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_7
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 8  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_8
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 9  THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_9
		,MAX(CASE WHEN COSM.CLM_OCRNC_SGNTR_SQNC_NUM = 10 THEN TO_CHAR(COSM.CLM_OCRNC_SPAN_THRU_DT,'YYYYMMDD') ELSE '10000101' END) AS OCRNC_SPAN_THRU_DT_10

	FROM CLM_ENC_CLMS C 

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_OCRNC_SGNTR_MBR COSM
	ON  C.CLM_OCRNC_SGNTR_SK  = COSM.CLM_OCRNC_SGNTR_SK

	WHERE COSM.CLM_OCRNC_SGNTR_SQNC_NUM <= 10

	GROUP BY C.CLM_OCRNC_SGNTR_SK

)




,TMP_PROD_HHA_VAL AS (

	SELECT
	   C.GEO_BENE_SK
	  ,C.CLM_DT_SGNTR_SK
	  ,C.CLM_TYPE_CD
	  ,C.CLM_NUM_SK
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 1  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_1
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 2  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_2
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 3  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_3
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 4  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_4
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 5  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_5
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 6  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_6
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 7  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_7
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 8  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_8
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 9  THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_9
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 10 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_10	  
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 11 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_11
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 12 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_12
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 13 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_13
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 14 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_14
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 15 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_15
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 16 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_16
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 17 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_17
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 18 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_18
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 19 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_19
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 20 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_20
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 21 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_21
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 22 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_22
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 23 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_23
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 24 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_24
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 25 THEN REPLACE(VAL.CLM_VAL_CD,'~',' ') END) AS VAL_CD_25

	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 1  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_1
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 2  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_2
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 3  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_3
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 4  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_4
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 5  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_5
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 6  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_6
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 7  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_7
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 8  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_8
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 9  THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_9
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 10 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_10	  
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 11 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_11
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 12 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_12
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 13 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_13
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 14 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_14
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 15 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_15
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 16 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_16
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 17 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_17
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 18 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_18
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 19 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_19
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 20 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_20
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 21 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_21
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 22 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_22
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 23 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_23
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 24 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_24
	  ,MAX(CASE WHEN VAL.CLM_VAL_SQNC_NUM = 25 THEN VAL.CLM_VAL_AMT END) AS VAL_AMT_25
	  
	  
	FROM CLM_ENC_CLMS C 

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_VAL VAL
	ON  C.GEO_BENE_SK     = VAL.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = VAL.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = VAL.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = VAL.CLM_NUM_SK

	WHERE VAL.CLM_VAL_SQNC_NUM  <= 25

	GROUP BY C.GEO_BENE_SK, C.CLM_DT_SGNTR_SK, C.CLM_TYPE_CD, C.CLM_NUM_SK

)

,TMP_HHA_ADR AS (

	SELECT
		 C.GEO_BENE_SK
		,C.CLM_DT_SGNTR_SK
		,C.CLM_TYPE_CD
		,C.CLM_NUM_SK

		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD = 'P' AND CA.CLM_ADR_SBTYP_CD = 'BP' 
				  THEN CA.CLM_ADR_LINE_1_TXT ELSE NULL END)          AS CLM_BPRVDR_ADR_LINE_1_TXT
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'  
						   THEN CA.CLM_ADR_LINE_2_TXT ELSE NULL END) AS CLM_BPRVDR_ADR_LINE_2_TXT
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD = 'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
						   THEN CA.CLM_ADR_LINE_3_TXT ELSE NULL END) AS CLM_BPRVDR_ADR_LINE_3_TXT
						   
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
						   THEN CA.CLM_CITY_NAME ELSE NULL END)      AS CLM_BPRVDR_CITY_NAME
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
						   THEN	CA.CLM_USPS_STATE_CD ELSE NULL END)  AS CLM_BPRVDR_USPS_STATE_CD
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
						   THEN CA.GEO_ZIP5_CD ELSE NULL END)        AS BPRVDR_GEO_ZIP5_CD
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'P' AND CA.CLM_ADR_SBTYP_CD = 'BP'   
						   THEN REPLACE(CA.GEO_ZIP4_CD,'~',' ') ELSE NULL END)    AS BPRVDR_GEO_ZIP4_CD

		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN CA.CLM_ADR_LINE_1_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_1_TXT
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN CA.CLM_ADR_LINE_2_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_2_TXT
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'    
						   THEN CA.CLM_ADR_LINE_3_TXT ELSE NULL END)  AS CLM_SUBSCR_ADR_LINE_3_TXT
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN CA.CLM_CITY_NAME ELSE NULL END)       AS CLM_SUBSCR_CITY_NAME
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN CA.CLM_USPS_STATE_CD ELSE NULL END)   AS CLM_SUBSCR_USPS_STATE_CD
						   
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN CA.GEO_ZIP5_CD ELSE NULL END)         AS SUBSCR_GEO_ZIP5_CD
		,MAX(CASE WHEN CA.CLM_ADR_TYPE_CD =  'B' AND CA.CLM_ADR_SBTYP_CD = 'SB'   
						   THEN REPLACE(CA.GEO_ZIP4_CD,'~',' ') ELSE NULL END)         AS SUBSCR_GEO_ZIP4_CD


	FROM CLM_ENC_CLMS C 

	INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ADR CA
	ON  C.GEO_BENE_SK     = CA.GEO_BENE_SK
	AND C.CLM_DT_SGNTR_SK = CA.CLM_DT_SGNTR_SK
	AND C.CLM_TYPE_CD     = CA.CLM_TYPE_CD
	AND C.CLM_NUM_SK      = CA.CLM_NUM_SK
	AND CA.CLM_ADR_SQNC_NUM = 1

	GROUP BY C.GEO_BENE_SK, C.CLM_DT_SGNTR_SK, C.CLM_TYPE_CD, C.CLM_NUM_SK
	 

)


SELECT DISTINCT

	 TO_CHAR(CL.GEO_BENE_SK,'FM0000000000')        AS GEO_BENE_SK
	,TO_CHAR(CL.CLM_DT_SGNTR_SK,'FM0000000000000') AS CLM_DT_SGNTR_SK
	,TO_CHAR(CL.CLM_TYPE_CD,'FM00000')             AS CLM_TYPE_CD
	,TO_CHAR(CL.CLM_NUM_SK,'FM00000')              AS CLM_NUM_SK
	,TO_CHAR(CL.CLM_LINE_NUM,'FM0000000000')       AS CLM_LINE_NUM 
	,TO_CHAR(CL.CLM_TYPE_CD,'FM00000')             AS CLM_TYPE_CD  

	,SUBSTR(RPAD(COALESCE(TRIM(C.CLM_HIC_NUM),' '),12,' '),1,12)  AS CLM_HIC_NUM

	,RPAD((CASE WHEN GFCC.GEO_SSA_STATE_CD = '~' THEN ' ' ELSE GFCC.GEO_SSA_STATE_CD END),2,' ')  AS GEO_SSA_STATE_CD

	,CASE WHEN C.CLM_FROM_DT IS NULL THEN '10000101' ELSE to_char(C.CLM_FROM_DT,'YYYYMMDD') END AS CLM_FROM_DT
	,CASE WHEN C.CLM_THRU_DT IS NULL THEN '10000101' ELSE to_char(C.CLM_THRU_DT,'YYYYMMDD') END AS CLM_THRU_DT
	,CASE WHEN CED.CLM_EDPS_CREATN_DT IS NULL THEN '10000101' ELSE to_char(CED.CLM_EDPS_CREATN_DT,'YYYYMMDD') END AS CLM_EDPS_CREATN_DT

	,RPAD(C.CLM_CNTL_NUM,40,' ') AS  CLM_CNTL_NUM
	,RPAD(CASE WHEN TRIM(C.CLM_ORIG_CNTL_NUM) = '~'       THEN ' ' ELSE COALESCE(C.CLM_ORIG_CNTL_NUM,' ') END,40,' ')       AS CLM_ORIG_CNTL_NUM
	
 
	,CASE WHEN CED.CLM_EDPS_LD_DT IS NULL THEN '10000101' ELSE to_char(CED.CLM_EDPS_LD_DT,'YYYYMMDD') END AS CLM_EDPS_LD_DT
 
	,RPAD(C.CLM_BILL_FAC_TYPE_CD,1,' ') AS CLM_BILL_FAC_TYPE_CD
	,RPAD(C.CLM_BILL_CLSFCTN_CD,1,' ')  AS CLM_BILL_CLSFCTN_CD
	,RPAD(C.CLM_BILL_FREQ_CD,1,' ')     AS CLM_BILL_FREQ_CD
	
	,RPAD(CASE WHEN GFCC.GEO_SSA_CNTY_CD = '~' THEN ' ' ELSE COALESCE(GFCC.GEO_SSA_CNTY_CD,' ') END,3,' ')  AS  GEO_SSA_CNTY_CD
	,CASE WHEN DT.CLM_SUBMSN_DT IS NULL THEN '10000101' ELSE to_char(DT.CLM_SUBMSN_DT,'YYYYMMDD') END       AS CLM_SUBMSN_DT
	 
	,RPAD(CE.CLM_CNTRCT_NUM,5,' ') AS  CLM_CNTRCT_NUM

	,RPAD(CASE WHEN ZIP5.GEO_ZIP5_CD ='~' THEN ' ' ELSE COALESCE(ZIP5.GEO_ZIP5_CD,' ') END,5,' ')  ||
     RPAD(CASE WHEN ZIP9.GEO_ZIP4_CD ='~' THEN ' ' ELSE COALESCE(ZIP9.GEO_ZIP4_CD,' ') END,4,' ')	AS GEO_ZIP9_CD
	
	,RPAD(CASE WHEN C.BENE_SEX_CD   = '~' THEN ' '  ELSE C.BENE_SEX_CD END,1,' ')   AS BENE_SEX_CD 
        ,RPAD(CASE WHEN COALESCE(BF.BENE_RACE_CD,' ') = '~' THEN ' '  ELSE COALESCE(BF.BENE_RACE_CD,' ') END,2,' ') AS BENE_RACE_CD
	,CASE WHEN C.CLM_PTNT_BIRTH_DT IS NULL THEN REPEAT(8,' ') ELSE to_char(C.CLM_PTNT_BIRTH_DT,'YYYYMMDD') END AS CLM_PTNT_BIRTH_DT

	,RPAD(COALESCE(BF.BENE_MDCR_STUS_CD,' '),2,' ')   AS BENE_MDCR_STUS_CD
	,RPAD(CDN.CLM_LAST_NAME,60,' ')     AS CLM_LAST_NAME
	,RPAD(CDN.CLM_1ST_NAME,35,' ')      AS CLM_1ST_NAME
	,RPAD(COALESCE(CDN.CLM_INTL_MDL_NAME,' '),1,' ') AS CLM_INTL_MDL_NAME
  

	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND
	,RPAD(CASE WHEN PROD_MT.CLM_PRNCPL_DGNS_CD = '~'     THEN ' ' ELSE COALESCE(PROD_MT.CLM_PRNCPL_DGNS_CD,' ') END,7,' ')     AS CLM_PRNCPL_DGNS_CD
  
	-- WARNING!! FORMAT '9(13)V9(2)S') (CHAR(15)
	,REPLACE(TO_CHAR(CASE WHEN CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P' THEN CEOPD.CLM_ENCTR_OTHR_PYR_PD_AMT ELSE 0 END,'000000000000.00S'),'.','') 
          	AS  CLM_ENCTR_OTHR_PYR_PD_AMT

	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_NPI_NUM = '~'      THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_NPI_NUM,' ')     END,10,' ')  AS  CLM_BLG_PRVDR_NPI_NUM 
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_NPI_NUM = '~'    THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_NPI_NUM,' ')   END,10,' ')  AS  CLM_ATNDG_PRVDR_NPI_NUM 
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_LAST_NAME = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_ATNDG_PRVDR_LAST_NAME 
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_ATNDG_PRVDR_1ST_NAME 
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_ATNDG_PRVDR_MDL_NAME 
	,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_NPI_NUM  = '~'   THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_NPI_NUM,' ')   END,10,' ')  AS  CLM_OPRTG_PRVDR_NPI_NUM 
	,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_LAST_NAME  = '~' THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_LAST_NAME,' ') END,60,' ')  AS  CLM_OPRTG_PRVDR_LAST_NAME 
	,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_1ST_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_1ST_NAME,' ')  END,35,' ')  AS  CLM_OPRTG_PRVDR_1ST_NAME 
	,RPAD(CASE WHEN C.CLM_OPRTG_PRVDR_MDL_NAME  = '~'  THEN ' ' ELSE COALESCE(C.CLM_OPRTG_PRVDR_MDL_NAME,' ')  END,25,' ')  AS  CLM_OPRTG_PRVDR_MDL_NAME 
	,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_NPI_NUM  = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_NPI_NUM,' ')    END,10,' ')  AS  CLM_OTHR_PRVDR_NPI_NUM 
	,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_LAST_NAME = '~'   THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_LAST_NAME,' ')  END,60,' ')  AS  CLM_OTHR_PRVDR_LAST_NAME 
	,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_1ST_NAME = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_1ST_NAME,' ')   END,35,' ')  AS  CLM_OTHR_PRVDR_1ST_NAME 
	,RPAD(CASE WHEN C.CLM_OTHR_PRVDR_MDL_NAME = '~'    THEN ' ' ELSE COALESCE(C.CLM_OTHR_PRVDR_MDL_NAME,' ')   END,25,' ')  AS  CLM_OTHR_PRVDR_MDL_NAME 

	,RPAD(CDN.CLM_PTNT_CNTL_NUM,80,' ')      AS CLM_PTNT_CNTL_NUM
	,RPAD(COALESCE(CDN.CLM_PTNT_MDCL_REC_NUM,' '),80,' ')  AS CLM_PTNT_MDCL_REC_NUM

    ,RPAD(CI.BENE_PTNT_STUS_CD,2,' ')        AS BENE_PTNT_STUS_CD 

	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_E_CD          = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_E_CD,' ') END,7,' ')          AS CLM_DGNS_E_CD 

	-- WARNING!! FORMAT '9(13)V9(2)S' (CHAR (15)
	,REPLACE(TO_CHAR(COALESCE(C.CLM_SBMT_CHRG_AMT,0),'000000000000.00S'),'.','')  AS CLM_SBMT_CHRG_AMT 
	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_ZIP5_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_ZIP5_CD,' ') END,5,' ')  ||
         RPAD(CASE WHEN C.CLM_BLG_PRVDR_ZIP4_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_ZIP4_CD,' ') END,4,' ') AS CLM_BLG_PRVDR_ZIP9_D		

	,RPAD(CASE WHEN C.CLM_RNDRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(C.CLM_RNDRG_PRVDR_NPI_NUM,' ') END,10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM

	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_LAST_NAME,' '),60,' ') AS CLM_RNDRG_PRVDR_LAST_NAME
	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_1ST_NAME,' '),35,' ')  AS CLM_RNDRG_PRVDR_1ST_NAME
	,RPAD(COALESCE(C.CLM_RNDRG_PRVDR_MDL_NAME,' '),25,' ')  AS CLM_RNDRG_PRVDR_MDL_NAME	

	,TO_CHAR(PROD_MT.CLM_DGNS_TOT_OCRNC_CNT,'FM00')   AS CLM_DGNS_TOT_OCRNC_CNT
	,CASE WHEN DT.CLM_DSCHRG_DT IS NULL THEN '10000101' ELSE TO_CHAR(DT.CLM_DSCHRG_DT,'YYYYMMDD') END  AS CLM_DSCHRG_DT
	,CASE WHEN DT.CLM_ACTV_CARE_FROM_DT IS NULL THEN '10000101' ELSE TO_CHAR(DT.CLM_ACTV_CARE_FROM_DT,'YYYYMMDD') END  AS CLM_ACTV_CARE_FROM_DT
	

	,RPAD(CASE WHEN C.CLM_RFRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(C.CLM_RFRG_PRVDR_NPI_NUM,' ') END,10,' ') AS CLM_RFRG_PRVDR_NPI_NUM
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_LAST_NAME,' '),60,' ') AS CLM_RFRG_PRVDR_LAST_NAME
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_1ST_NAME,' '),35,' ')  AS CLM_RFRG_PRVDR_1ST_NAME
	,RPAD(COALESCE(C.CLM_RFRG_PRVDR_MDL_NAME,' '),25,' ')  AS CLM_RFRG_PRVDR_MDL_NAME	



	--- DGNS_R_CD  **********
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ')   AS CLM_DGNS_PRCDR_ICD_IND
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD   = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_RSN_FOR_VISIT_CD,' ')   END,7,' ') AS CLM_DGNS_RSN_FOR_VISIT_CD 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_2_RSN_FOR_VISIT_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_RSN_FOR_VISIT_CD,' ') END,7,' ') AS CLM_DGNS_3_RSN_FOR_VISIT_CD 
 
	

	--- MCO_CNTRCT_NUM**********
	,RPAD(CASE WHEN CDN.CLM_MCO_1ST_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_1ST_CNTRCT_NUM
	,RPAD(CASE WHEN CDN.CLM_MCO_2ND_CNTRCT_NUM = '~'   THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_CNTRCT_NUM,' ') END,5,' ')    AS CLM_MCO_2ND_CNTRCT_NUM
	,RPAD(CASE WHEN CDN.CLM_MCO_1ST_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_1ST_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_1ST_HLTH_PLAN_ID
	,RPAD(CASE WHEN CDN.CLM_MCO_2ND_HLTH_PLAN_ID = '~' THEN ' ' ELSE COALESCE(CDN.CLM_MCO_2ND_HLTH_PLAN_ID,' ') END,14,' ') AS CLM_MCO_2ND_HLTH_PLAN_ID

	--- CLM-DGNS-D  ************
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_PRCDR_ICD_IND = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_PRCDR_ICD_IND,' ') END,1,' ') AS CLM_DGNS_PRCDR_ICD_IND 
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_1_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_1_CD,' ')  END,7,' ')  AS CLM_DGNS_1_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_2_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_2_CD,' ')  END,7,' ')  AS CLM_DGNS_2_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_3_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_3_CD,' ')  END,7,' ')  AS CLM_DGNS_3_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_4_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_4_CD,' ')  END,7,' ')  AS CLM_DGNS_4_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_5_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_5_CD,' ')  END,7,' ')  AS CLM_DGNS_5_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_6_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_6_CD,' ')  END,7,' ')  AS CLM_DGNS_6_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_7_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_7_CD,' ')  END,7,' ')  AS CLM_DGNS_7_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_8_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_8_CD,' ')  END,7,' ')  AS CLM_DGNS_8_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_9_CD = '~'  THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_9_CD,' ')  END,7,' ')  AS CLM_DGNS_9_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_10_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_10_CD,' ') END,7,' ')  AS CLM_DGNS_10_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_11_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_11_CD,' ') END,7,' ')  AS CLM_DGNS_11_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_12_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_12_CD,' ') END,7,' ')  AS CLM_DGNS_12_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_13_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_13_CD,' ') END,7,' ')  AS CLM_DGNS_13_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_14_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_14_CD,' ') END,7,' ')  AS CLM_DGNS_14_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_15_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_15_CD,' ') END,7,' ')  AS CLM_DGNS_15_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_16_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_16_CD,' ') END,7,' ')  AS CLM_DGNS_16_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_17_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_17_CD,' ') END,7,' ')  AS CLM_DGNS_17_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_18_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_18_CD,' ') END,7,' ')  AS CLM_DGNS_18_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_19_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_19_CD,' ') END,7,' ')  AS CLM_DGNS_19_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_20_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_20_CD,' ') END,7,' ')  AS CLM_DGNS_20_CD	
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_21_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_21_CD,' ') END,7,' ')  AS CLM_DGNS_21_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_22_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_22_CD,' ') END,7,' ')  AS CLM_DGNS_22_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_23_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_23_CD,' ') END,7,' ')  AS CLM_DGNS_23_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_24_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_24_CD,' ') END,7,' ')  AS CLM_DGNS_24_CD
	,RPAD(CASE WHEN PROD_MT.CLM_DGNS_25_CD = '~' THEN ' ' ELSE COALESCE(PROD_MT.CLM_DGNS_25_CD,' ') END,7,' ')  AS CLM_DGNS_25_CD	


	--- CLM-DGNS-E **********
	,RPAD(COALESCE(PROD.CLM_DGNS_PRCDR_ICD_IND,' '),1,' ') AS  CLM_DGNS_PRCDR_ICD_IND
	,RPAD(COALESCE(DECIT.DGNS_E_CD_1,' '),7,' ')   AS  DGNS_E_CD_1
	,RPAD(COALESCE(DECIT.DGNS_E_CD_2,' '),7,' ')   AS  DGNS_E_CD_2
	,RPAD(COALESCE(DECIT.DGNS_E_CD_3,' '),7,' ')   AS  DGNS_E_CD_3
	,RPAD(COALESCE(DECIT.DGNS_E_CD_4,' '),7,' ')   AS  DGNS_E_CD_4
	,RPAD(COALESCE(DECIT.DGNS_E_CD_5,' '),7,' ')   AS  DGNS_E_CD_5
	,RPAD(COALESCE(DECIT.DGNS_E_CD_6,' '),7,' ')   AS  DGNS_E_CD_6
	,RPAD(COALESCE(DECIT.DGNS_E_CD_7,' '),7,' ')   AS  DGNS_E_CD_7
	,RPAD(COALESCE(DECIT.DGNS_E_CD_8,' '),7,' ')   AS  DGNS_E_CD_8
	,RPAD(COALESCE(DECIT.DGNS_E_CD_9,' '),7,' ')   AS  DGNS_E_CD_9
	,RPAD(COALESCE(DECIT.DGNS_E_CD_10,' '),7,' ')  AS  DGNS_E_CD_10
	,RPAD(COALESCE(DECIT.DGNS_E_CD_11,' '),7,' ')  AS  DGNS_E_CD_11
	,RPAD(COALESCE(DECIT.DGNS_E_CD_12,' '),7,' ')  AS  DGNS_E_CD_12

	--- RLT-COND **********
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_1,' '),2,' ')  AS RLT_COND_CD_1
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_2,' '),2,' ')  AS RLT_COND_CD_2
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_3,' '),2,' ')  AS RLT_COND_CD_3
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_4,' '),2,' ')  AS RLT_COND_CD_4
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_5,' '),2,' ')  AS RLT_COND_CD_5
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_6,' '),2,' ')  AS RLT_COND_CD_6
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_7,' '),2,' ')  AS RLT_COND_CD_7
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_8,' '),2,' ')  AS RLT_COND_CD_8
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_9,' '),2,' ')  AS RLT_COND_CD_9
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_10,' '),2,' ') AS RLT_COND_CD_10
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_11,' '),2,' ') AS RLT_COND_CD_11
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_12,' '),2,' ') AS RLT_COND_CD_12
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_13,' '),2,' ') AS RLT_COND_CD_13
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_14,' '),2,' ') AS RLT_COND_CD_14
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_15,' '),2,' ') AS RLT_COND_CD_15
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_16,' '),2,' ') AS RLT_COND_CD_16
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_17,' '),2,' ') AS RLT_COND_CD_17
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_18,' '),2,' ') AS RLT_COND_CD_18
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_19,' '),2,' ') AS RLT_COND_CD_19
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_20,' '),2,' ') AS RLT_COND_CD_20	
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_21,' '),2,' ') AS RLT_COND_CD_21
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_22,' '),2,' ') AS RLT_COND_CD_22
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_23,' '),2,' ') AS RLT_COND_CD_23
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_24,' '),2,' ') AS RLT_COND_CD_24
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_25,' '),2,' ') AS RLT_COND_CD_25
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_26,' '),2,' ') AS RLT_COND_CD_26
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_27,' '),2,' ') AS RLT_COND_CD_27
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_28,' '),2,' ') AS RLT_COND_CD_28
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_29,' '),2,' ') AS RLT_COND_CD_29
	,RPAD(COALESCE(CRCSM.RLT_COND_CD_30,' '),2,' ') AS RLT_COND_CD_30

	--- RLT-OCRNC **********
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_1,' '),2,' ')  AS RLT_OCRNC_CD_1
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_2,' '),2,' ')  AS RLT_OCRNC_CD_2
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_3,' '),2,' ')  AS RLT_OCRNC_CD_3
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_4,' '),2,' ')  AS RLT_OCRNC_CD_4
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_5,' '),2,' ')  AS RLT_OCRNC_CD_5
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_6,' '),2,' ')  AS RLT_OCRNC_CD_6
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_7,' '),2,' ')  AS RLT_OCRNC_CD_7
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_8,' '),2,' ')  AS RLT_OCRNC_CD_8
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_9,' '),2,' ')  AS RLT_OCRNC_CD_9
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_10,' '),2,' ') AS RLT_OCRNC_CD_10
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_11,' '),2,' ') AS RLT_OCRNC_CD_11
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_12,' '),2,' ') AS RLT_OCRNC_CD_12
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_13,' '),2,' ') AS RLT_OCRNC_CD_13
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_14,' '),2,' ') AS RLT_OCRNC_CD_14
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_15,' '),2,' ') AS RLT_OCRNC_CD_15
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_16,' '),2,' ') AS RLT_OCRNC_CD_16
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_17,' '),2,' ') AS RLT_OCRNC_CD_17
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_18,' '),2,' ') AS RLT_OCRNC_CD_18
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_19,' '),2,' ') AS RLT_OCRNC_CD_19
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_20,' '),2,' ') AS RLT_OCRNC_CD_20
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_21,' '),2,' ') AS RLT_OCRNC_CD_21
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_22,' '),2,' ') AS RLT_OCRNC_CD_22
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_23,' '),2,' ') AS RLT_OCRNC_CD_23
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_24,' '),2,' ') AS RLT_OCRNC_CD_24
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_25,' '),2,' ') AS RLT_OCRNC_CD_25
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_26,' '),2,' ') AS RLT_OCRNC_CD_26
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_27,' '),2,' ') AS RLT_OCRNC_CD_27
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_28,' '),2,' ') AS RLT_OCRNC_CD_28
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_29,' '),2,' ') AS RLT_OCRNC_CD_29
	,RPAD(COALESCE(CROSM.RLT_OCRNC_CD_30,' '),2,' ') AS RLT_OCRNC_CD_30

	,COALESCE(CROSM.RLT_OCRNC_DT_1,'10000101')  AS RLT_OCRNC_DT_1  
	,COALESCE(CROSM.RLT_OCRNC_DT_2,'10000101')  AS RLT_OCRNC_DT_2
	,COALESCE(CROSM.RLT_OCRNC_DT_3,'10000101')  AS RLT_OCRNC_DT_3
	,COALESCE(CROSM.RLT_OCRNC_DT_4,'10000101')  AS RLT_OCRNC_DT_4
	,COALESCE(CROSM.RLT_OCRNC_DT_5,'10000101')  AS RLT_OCRNC_DT_5
	,COALESCE(CROSM.RLT_OCRNC_DT_6,'10000101')  AS RLT_OCRNC_DT_6
	,COALESCE(CROSM.RLT_OCRNC_DT_7,'10000101')  AS RLT_OCRNC_DT_7
	,COALESCE(CROSM.RLT_OCRNC_DT_8,'10000101')  AS RLT_OCRNC_DT_8
	,COALESCE(CROSM.RLT_OCRNC_DT_9,'10000101')  AS RLT_OCRNC_DT_9
	,COALESCE(CROSM.RLT_OCRNC_DT_10,'10000101') AS RLT_OCRNC_DT_10
	,COALESCE(CROSM.RLT_OCRNC_DT_11,'10000101') AS RLT_OCRNC_DT_11  
	,COALESCE(CROSM.RLT_OCRNC_DT_12,'10000101') AS RLT_OCRNC_DT_12
	,COALESCE(CROSM.RLT_OCRNC_DT_13,'10000101') AS RLT_OCRNC_DT_13
	,COALESCE(CROSM.RLT_OCRNC_DT_14,'10000101') AS RLT_OCRNC_DT_14
	,COALESCE(CROSM.RLT_OCRNC_DT_15,'10000101') AS RLT_OCRNC_DT_15
	,COALESCE(CROSM.RLT_OCRNC_DT_16,'10000101') AS RLT_OCRNC_DT_16
	,COALESCE(CROSM.RLT_OCRNC_DT_17,'10000101') AS RLT_OCRNC_DT_17
	,COALESCE(CROSM.RLT_OCRNC_DT_18,'10000101') AS RLT_OCRNC_DT_18
	,COALESCE(CROSM.RLT_OCRNC_DT_19,'10000101') AS RLT_OCRNC_DT_19
	,COALESCE(CROSM.RLT_OCRNC_DT_20,'10000101') AS RLT_OCRNC_DT_20
	,COALESCE(CROSM.RLT_OCRNC_DT_21,'10000101') AS RLT_OCRNC_DT_21  
	,COALESCE(CROSM.RLT_OCRNC_DT_22,'10000101') AS RLT_OCRNC_DT_22
	,COALESCE(CROSM.RLT_OCRNC_DT_23,'10000101') AS RLT_OCRNC_DT_23
	,COALESCE(CROSM.RLT_OCRNC_DT_24,'10000101') AS RLT_OCRNC_DT_24
	,COALESCE(CROSM.RLT_OCRNC_DT_25,'10000101') AS RLT_OCRNC_DT_25
	,COALESCE(CROSM.RLT_OCRNC_DT_26,'10000101') AS RLT_OCRNC_DT_26
	,COALESCE(CROSM.RLT_OCRNC_DT_27,'10000101') AS RLT_OCRNC_DT_27
	,COALESCE(CROSM.RLT_OCRNC_DT_28,'10000101') AS RLT_OCRNC_DT_28
	,COALESCE(CROSM.RLT_OCRNC_DT_29,'10000101') AS RLT_OCRNC_DT_29
	,COALESCE(CROSM.RLT_OCRNC_DT_30,'10000101') AS RLT_OCRNC_DT_30

	--- OCRNC-SPAN ******
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_1,' '),2,' ')  AS OCRNC_SPAN_CD_1
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_2,' '),2,' ')  AS OCRNC_SPAN_CD_2
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_3,' '),2,' ')  AS OCRNC_SPAN_CD_3
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_4,' '),2,' ')  AS OCRNC_SPAN_CD_4
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_5,' '),2,' ')  AS OCRNC_SPAN_CD_5
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_6,' '),2,' ')  AS OCRNC_SPAN_CD_6
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_7,' '),2,' ')  AS OCRNC_SPAN_CD_7
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_8,' '),2,' ')  AS OCRNC_SPAN_CD_8
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_9,' '),2,' ')  AS OCRNC_SPAN_CD_9
	,RPAD(COALESCE(COSM.OCRNC_SPAN_CD_10,' '),2,' ') AS OCRNC_SPAN_CD_10

	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_1,'10000101')   AS OCRNC_SPAN_FROM_DT_1 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_2,'10000101')   AS OCRNC_SPAN_FROM_DT_2 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_3,'10000101')   AS OCRNC_SPAN_FROM_DT_3 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_4,'10000101')   AS OCRNC_SPAN_FROM_DT_4 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_5,'10000101')   AS OCRNC_SPAN_FROM_DT_5 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_6,'10000101')   AS OCRNC_SPAN_FROM_DT_6 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_7,'10000101')   AS OCRNC_SPAN_FROM_DT_7 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_8,'10000101')   AS OCRNC_SPAN_FROM_DT_8 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_9,'10000101')   AS OCRNC_SPAN_FROM_DT_9 
	,COALESCE(COSM.OCRNC_SPAN_FROM_DT_10,'10000101')  AS OCRNC_SPAN_FROM_DT_10 

	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_1,'10000101')   AS OCRNC_SPAN_THRU_DT_1 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_2,'10000101')   AS OCRNC_SPAN_THRU_DT_2 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_3,'10000101')   AS OCRNC_SPAN_THRU_DT_3 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_4,'10000101')   AS OCRNC_SPAN_THRU_DT_4 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_5,'10000101')   AS OCRNC_SPAN_THRU_DT_5 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_6,'10000101')   AS OCRNC_SPAN_THRU_DT_6 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_7,'10000101')   AS OCRNC_SPAN_THRU_DT_7 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_8,'10000101')   AS OCRNC_SPAN_THRU_DT_8 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_9,'10000101')   AS OCRNC_SPAN_THRU_DT_9 
	,COALESCE(COSM.OCRNC_SPAN_THRU_DT_10,'10000101')  AS OCRNC_SPAN_THRU_DT_10 

	,RPAD(CL.CLM_LINE_REV_CTR_CD,10,' ') as CLM_LINE_REV_CTR_CD
	,CASE WHEN CL.CLM_LINE_FROM_DT IS NULL THEN '10000101' ELSE TO_CHAR(CL.CLM_LINE_FROM_DT,'YYYYMMDD') END  AS  CLM_LINE_FROM_DT

	,RPAD(CASE WHEN CL.CLM_LINE_HCPCS_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_LINE_HCPCS_CD,' ')  END,5,' ') AS CLM_LINE_HCPCS_CD
	
	,RPAD(CASE WHEN CL.HCPCS_1_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_1_MDFR_CD,' ')	END,2,' ') AS HCPCS_1_MDFR_CD	
	,RPAD(CASE WHEN CL.HCPCS_2_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_2_MDFR_CD,' ')	END,2,' ') AS HCPCS_2_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_3_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_3_MDFR_CD,' ')	END,2,' ') AS HCPCS_3_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_4_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_4_MDFR_CD,' ')	END,2,' ') AS HCPCS_4_MDFR_CD
	,RPAD(CASE WHEN CL.HCPCS_5_MDFR_CD = '~'   THEN ' ' ELSE COALESCE(CL.HCPCS_5_MDFR_CD,' ')	END,2,' ') AS HCPCS_5_MDFR_CD
	

	,RPAD(CASE WHEN CL.CLM_LINE_NDC_CD ='~' THEN ' ' ELSE CL.CLM_LINE_NDC_CD END,11,' ')  AS CLM_LINE_NDC_CD
	,RPAD(CASE WHEN CL.CLM_LINE_NDC_QTY_QLFYR_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_LINE_NDC_QTY_QLFYR_CD,' ') END,2,' ') AS  CLM_LINE_NDC_QTY_QLFYR_CD

	-- WARNING !!  (FORMAT '9(14)V9(4)S') CHAR(18) Truncation of SIGN
	,REPLACE(TO_CHAR(COALESCE(CL.CLM_LINE_NDC_QTY,0),'0000000000000.0000S'),'.','')  AS CLM_LINE_NDC_QTY 
	-- WARNING !!  (FORMAT '9(14)V9(4)S') CHAR(18) Truncation of SIGN
	,REPLACE(TO_CHAR(COALESCE(CL.CLM_LINE_SRVC_UNIT_QTY,0),'0000000000000.0000S'),'.','')  AS CLM_LINE_SRVC_UNIT_QTY 

	-- WARNING !!  (FORMAT '9(13)V9(2)S') (CHAR(15)) TRUNCATION OF SIGN 
	,REPLACE(TO_CHAR(CASE WHEN CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P'  THEN COALESCE(CLEOPD.CLM_LINE_OTHR_PYR_PD_AMT,0)  ELSE 0 END,'000000000000.00S'),'.','')  AS CLM_LINE_OTHR_PYR_PD_AMT
	-- WARNING !! (FORMAT '9(13)V9(2)S') (CHAR(15)) 
	,REPLACE(TO_CHAR(COALESCE(CL.CLM_LINE_SBMT_CHRG_AMT,0),'000000000000.00S'),'.','') AS CLM_LINE_SBMT_CHRG_AMT 

	,RPAD(CASE WHEN CL.CLM_RNDRG_PRVDR_NPI_NUM = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_PRVDR_NPI_NUM,' ') END,10,' ')  AS CLM_RNDRG_PRVDR_NPI_NUM
	,RPAD(CASE WHEN CL.CLM_RNDRG_PRVDR_NAME = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_PRVDR_NAME,' ') END,120,' ')  AS CLM_RNDRG_PRVDR_NAME
	,RPAD(CASE WHEN CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD = '~' THEN ' ' ELSE COALESCE(CL.CLM_RNDRG_FED_PRVDR_SPCLTY_CD,' ') END,2,' ') AS CLM_RNDRG_FED_PRVDR_SPCLTY_CD

	,CASE WHEN CL.CLM_LINE_THRU_DT IS NULL THEN '10000101' ELSE TO_CHAR(CL.CLM_LINE_THRU_DT,'YYYYMMDD') END  AS  CLM_LINE_THRU_DT

	,RPAD(CASE WHEN C.CLM_SBMTR_CNTRCT_NUM = BF.CNTRCT_PTC_NUM THEN BF.CNTRCT_PBP_PTC_NUM ELSE ' ' END,3,' ')  AS CNTRCT_PBP_PTC_NUM
	,RPAD(CASE WHEN CED.CLM_CNTRCT_TYPE_CD = '~' THEN ' ' ELSE COALESCE(CED.CLM_CNTRCT_TYPE_CD,' ') END,2,' ') AS CLM_CNTRCT_TYPE_CD
	,RPAD(CASE WHEN CLED.CLM_LINE_CNTRCT_TYPE_CD = '~' THEN ' ' ELSE COALESCE(CLED.CLM_LINE_CNTRCT_TYPE_CD,' ') END,2,' ')  AS CLM_LINE_CNTRCT_TYPE_CD
	,CASE WHEN CED.CLM_CHRT_RVW_SW = '~' THEN ' ' ELSE COALESCE(CED.CLM_CHRT_RVW_SW,' ') END AS CLM_CHRT_RVW_SW 

	-- FORMAT '9(18)')
	,TO_CHAR(BENE.BENE_SK,'FM000000000000000000')  AS BENE_SK
	,C.CLM_FINL_ACTN_IND
	,CL.CLM_LINE_FINL_ACTN_IND
	,C.CLM_LTST_CLM_IND
	,CL.CLM_LINE_LTST_CLM_IND
	,RPAD(CLE.CLM_LINE_ENCTR_STUS_CD,20,' ')
	
	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_TXNMY_CD = '~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_TXNMY_CD,' ') END,50,' ') AS CLM_BLG_PRVDR_TXNMY_CD
	,RPAD(CASE WHEN C.CLM_ATNDG_PRVDR_TXNMY_CD ='~' THEN ' ' ELSE COALESCE(C.CLM_ATNDG_PRVDR_TXNMY_CD,' ') END,10,' ') AS CLM_ATNDG_PRVDR_TXNMY_CD
	,RPAD(CE.CLM_EDPS_STUS_CD,20,' ')
	,CASE WHEN C.CLM_OBSLT_DT IS NULL THEN REPEAT(8,' ') ELSE TO_CHAR(C.CLM_OBSLT_DT,'YYYYMMDD') END  AS  CLM_OBSLT_DT

	-- (FORMAT '9(18)')
	,TO_CHAR(C.CLM_ERR_SGNTR_SK,'FM000000000000000000') AS CLM_ERR_SGNTR_SK  
	-- (FORMAT '9(10)')
	,TO_CHAR(C.GEO_BENE_EFCTV_SK,'FM0000000000')        AS GEO_BENE_EFCTV_SK
	-- (FORMAT '9(13)')
	,TO_CHAR(C.CLM_DT_SGNTR_EFCTV_SK,'FM0000000000000')  AS  CLM_DT_SGNTR_EFCTV_SK  
	,TO_CHAR(C.CLM_TYPE_EFCTV_CD,'FM00000')  AS  CLM_TYPE_EFCTV_CD
	
	,TO_CHAR(C.CLM_NUM_EFCTV_SK,'FM00000') AS CLM_NUM_EFCTV_SK
	-- WARNING!! (FORMAT '9(13)V9(2)S') (CHAR(15)) Truncation of sign
	,REPLACE(TO_CHAR(COALESCE(CED.CLM_CNTRCT_AMT,0),'000000000000.00S'),'.','')  AS  CLM_CNTRCT_AMT

	-- WARNING!! (FORMAT '9(13)V9(2)S') (CHAR(15)) Truncation of sign
	,REPLACE(TO_CHAR(COALESCE(C.CLM_PTNT_LBLTY_AMT,0),'000000000000.00S'),'.','')  AS CLM_PTNT_LBLTY_AMT
 	,RPAD(CASE WHEN BENE.BENE_EQTBL_BIC_CD = '~' THEN ' ' ELSE COALESCE(BENE.BENE_EQTBL_BIC_CD,' ') END,2,' ')  AS  BENE_EQTBL_BIC_CD

	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_1_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_1_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_2_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_2_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_ADR_LINE_3_TXT,' '),55,' ')  AS CLM_BPRVDR_ADR_LINE_3_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_CITY_NAME,' '),30,' ')       AS CLM_BPRVDR_CITY_NAME
	,RPAD(COALESCE(ADRTEMP.CLM_BPRVDR_USPS_STATE_CD,' '),2,' ')    AS CLM_BPRVDR_USPS_STATE_CD
	,RPAD(COALESCE(ADRTEMP.BPRVDR_GEO_ZIP5_CD,' '),5,' ') || 
	 RPAD(COALESCE(ADRTEMP.BPRVDR_GEO_ZIP4_CD,' '),4,' ')          AS ADR_BPRVDR_ZIP_CD 

	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_1_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_1_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_2_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_2_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_ADR_LINE_3_TXT,' '),55,' ')  AS CLM_SUBSCR_ADR_LINE_3_TXT
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_CITY_NAME,' '),30,' ')       AS CLM_SUBSCR_CITY_NAME
	,RPAD(COALESCE(ADRTEMP.CLM_SUBSCR_USPS_STATE_CD,' '),2,' ')    AS CLM_SUBSCR_USPS_STATE_CD
	,RPAD(COALESCE(ADRTEMP.SUBSCR_GEO_ZIP5_CD,' '),5,' ') || 
	 RPAD(COALESCE(ADRTEMP.SUBSCR_GEO_ZIP4_CD,' '),4,' ')          AS ADR_SUBSCR_ZIP_CD 

	,RPAD(COALESCE(PHVT.VAL_CD_1, ' '),2,' ')  AS  VAL_CD_1
	,RPAD(COALESCE(PHVT.VAL_CD_2, ' '),2,' ')  AS  VAL_CD_2
	,RPAD(COALESCE(PHVT.VAL_CD_3, ' '),2,' ')  AS  VAL_CD_3
	,RPAD(COALESCE(PHVT.VAL_CD_4, ' '),2,' ')  AS  VAL_CD_4
	,RPAD(COALESCE(PHVT.VAL_CD_5, ' '),2,' ')  AS  VAL_CD_5
	,RPAD(COALESCE(PHVT.VAL_CD_6, ' '),2,' ')  AS  VAL_CD_6
	,RPAD(COALESCE(PHVT.VAL_CD_7, ' '),2,' ')  AS  VAL_CD_7
	,RPAD(COALESCE(PHVT.VAL_CD_8, ' '),2,' ')  AS  VAL_CD_8
	,RPAD(COALESCE(PHVT.VAL_CD_9, ' '),2,' ')  AS  VAL_CD_9
	,RPAD(COALESCE(PHVT.VAL_CD_10, ' '),2,' ') AS  VAL_CD_10
	,RPAD(COALESCE(PHVT.VAL_CD_11, ' '),2,' ') AS  VAL_CD_11
	,RPAD(COALESCE(PHVT.VAL_CD_12, ' '),2,' ') AS  VAL_CD_12
	,RPAD(COALESCE(PHVT.VAL_CD_13, ' '),2,' ') AS  VAL_CD_13
	,RPAD(COALESCE(PHVT.VAL_CD_14, ' '),2,' ') AS  VAL_CD_14
	,RPAD(COALESCE(PHVT.VAL_CD_15, ' '),2,' ') AS  VAL_CD_15
	,RPAD(COALESCE(PHVT.VAL_CD_16, ' '),2,' ') AS  VAL_CD_16
	,RPAD(COALESCE(PHVT.VAL_CD_17, ' '),2,' ') AS  VAL_CD_17
	,RPAD(COALESCE(PHVT.VAL_CD_18, ' '),2,' ') AS  VAL_CD_18
	,RPAD(COALESCE(PHVT.VAL_CD_19, ' '),2,' ') AS  VAL_CD_19
	,RPAD(COALESCE(PHVT.VAL_CD_20, ' '),2,' ') AS  VAL_CD_20
	,RPAD(COALESCE(PHVT.VAL_CD_21, ' '),2,' ') AS  VAL_CD_21
	,RPAD(COALESCE(PHVT.VAL_CD_22, ' '),2,' ') AS  VAL_CD_22
	,RPAD(COALESCE(PHVT.VAL_CD_23, ' '),2,' ') AS  VAL_CD_23
	,RPAD(COALESCE(PHVT.VAL_CD_24, ' '),2,' ') AS  VAL_CD_24
	,RPAD(COALESCE(PHVT.VAL_CD_25, ' '),2,' ') AS  VAL_CD_25

	-- WARNING!! (FORMAT '9(13)V9(2)S') (CHAR(15)) Truncation of sign
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_1,0), '000000000000.00S'),'.','')  AS  VAL_AMT_1 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_2,0), '000000000000.00S'),'.','')  AS  VAL_AMT_2 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_3,0), '000000000000.00S'),'.','')  AS  VAL_AMT_3 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_4,0), '000000000000.00S'),'.','')  AS  VAL_AMT_4 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_5,0), '000000000000.00S'),'.','')  AS  VAL_AMT_5 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_6,0), '000000000000.00S'),'.','')  AS  VAL_AMT_6 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_7,0), '000000000000.00S'),'.','')  AS  VAL_AMT_7 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_8,0), '000000000000.00S'),'.','')  AS  VAL_AMT_8 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_9,0), '000000000000.00S'),'.','')  AS  VAL_AMT_9 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_10,0),'000000000000.00S'),'.','') AS  VAL_AMT_10 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_11,0),'000000000000.00S'),'.','') AS  VAL_AMT_11 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_12,0),'000000000000.00S'),'.','') AS  VAL_AMT_12 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_13,0),'000000000000.00S'),'.','') AS  VAL_AMT_13 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_14,0),'000000000000.00S'),'.','') AS  VAL_AMT_14 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_15,0),'000000000000.00S'),'.','') AS  VAL_AMT_15 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_16,0),'000000000000.00S'),'.','') AS  VAL_AMT_16 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_17,0),'000000000000.00S'),'.','') AS  VAL_AMT_17 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_18,0),'000000000000.00S'),'.','') AS  VAL_AMT_18 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_19,0),'000000000000.00S'),'.','') AS  VAL_AMT_19 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_20,0),'000000000000.00S'),'.','') AS  VAL_AMT_20 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_21,0),'000000000000.00S'),'.','') AS  VAL_AMT_21 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_22,0),'000000000000.00S'),'.','') AS  VAL_AMT_22 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_23,0),'000000000000.00S'),'.','') AS  VAL_AMT_23 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_24,0),'000000000000.00S'),'.','') AS  VAL_AMT_24 
	,REPLACE(TO_CHAR(COALESCE(PHVT.VAL_AMT_25,0),'000000000000.00S'),'.','') AS  VAL_AMT_25 

	,RPAD(CASE WHEN C.CLM_BLG_PRVDR_TAX_NUM ='~' THEN ' ' ELSE COALESCE(C.CLM_BLG_PRVDR_TAX_NUM,' ') END,10,' ') AS CLM_BLG_PRVDR_TAX_NUM

	,RPAD(C.BENE_ID_TYPE_CD,1,' ')  AS BENE_ID_TYPE_CD
	,RPAD(COALESCE(BENE.BENE_MBI_ID,' '),11,' ')  AS CLM_BENE_MBI_ID
	,RPAD(COALESCE(CED.CLM_CHRT_RVW_EFCTV_SW,' '),1,' ')  AS CLM_CHRT_RVW_EFCTV_SW
	,RPAD(COALESCE(CED.CLM_EDPS_CHRT_RVW_SW,' '),1,' ')   AS CLM_EDPS_CHRT_RVW_SW	
	,'END' AS END_OF_FILE

		
FROM IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM C

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_DT_SGNTR DT
ON DT.CLM_DT_SGNTR_SK = C.CLM_DT_SGNTR_SK
  
INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE BENE
ON C.BENE_SK          =  BENE.BENE_SK
--   and        BENE.BENE_SRC_DLT_IND = 'N'

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_INSTNL CI
ON  C.GEO_BENE_SK     = CI.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CI.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CI.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CI.CLM_NUM_SK
				 
INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_DCMTN CDN
ON  C.GEO_BENE_SK     = CDN.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CDN.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CDN.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CDN.CLM_NUM_SK

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR CE
ON  C.GEO_BENE_SK     = CE.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CE.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CE.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CE.CLM_NUM_SK

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR_DCMTN  CED
ON  C.GEO_BENE_SK     = CED.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = CED.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = CED.CLM_TYPE_CD
AND C.CLM_NUM_SK      = CED.CLM_NUM_SK

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_PROD_MTRLZD PROD_MT
ON  C.GEO_BENE_SK     = PROD_MT.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK = PROD_MT.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD     = PROD_MT.CLM_TYPE_CD
AND C.CLM_NUM_SK      = PROD_MT.CLM_NUM_SK

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR_OTHR_PYR_DTL CEOPD
ON  C.GEO_BENE_SK      = CEOPD.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CEOPD.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CEOPD.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CEOPD.CLM_NUM_SK
AND CEOPD.CLM_OTHR_PYR_RSPNSBLTY_SQNC_CD = 'P'

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_ENCTR_OTHR_PYR_PMT CEOPP
ON  C.GEO_BENE_SK      = CEOPP.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CEOPP.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CEOPP.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CEOPP.CLM_NUM_SK
AND CEOPP.CLM_OTHR_PYR_PMT_SQNC_NUM = 1

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_PROD PROD
ON  C.GEO_BENE_SK      = PROD.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = PROD.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = PROD.CLM_TYPE_CD
AND C.CLM_NUM_SK       = PROD.CLM_NUM_SK
AND PROD.CLM_PROD_TYPE_CD = 'D'

INNER JOIN  IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_ZIP5_CD ZIP5
ON ZIP5.GEO_SK        = C.GEO_BENE_SK

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_ZIP9_CD ZIP9
ON ZIP9.GEO_SK        = ZIP5.GEO_SK
AND BENE.GEO_ZIP4_CD  = ZIP9.GEO_ZIP4_CD

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_DIM_GEO_{ENVNAME}.GEO_FIPS_CNTY_CD GFCC 
ON  GFCC.GEO_FIPS_CNTY_CD  = ZIP5.GEO_FIPS_CNTY_CD 
AND GFCC.GEO_FIPS_STATE_CD = ZIP5.GEO_FIPS_STATE_CD


-- Claim Line joins
INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE CL
ON  C.GEO_BENE_SK      = CL.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = CL.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = CL.CLM_TYPE_CD
AND C.CLM_NUM_SK       = CL.CLM_NUM_SK
AND C.CLM_FROM_DT      = CL.CLM_FROM_DT

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE_ENCTR CLE
ON  CL.GEO_BENE_SK      = CLE.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK  = CLE.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD      = CLE.CLM_TYPE_CD
AND CL.CLM_NUM_SK       = CLE.CLM_NUM_SK
AND CL.CLM_LINE_NUM     = CLE.CLM_LINE_NUM

INNER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE_ENCTR_DCMTN  CLED
 ON CL.GEO_BENE_SK      = CLED.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK  = CLED.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD      = CLED.CLM_TYPE_CD
AND CL.CLM_NUM_SK       = CLED.CLM_NUM_SK
AND CL.CLM_LINE_NUM     = CLED.CLM_LINE_NUM

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE_ENCTR_OTHR_PYR_DTL CLEOPD
ON  CL.GEO_BENE_SK     =  CLEOPD.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK =  CLEOPD.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD     =  CLEOPD.CLM_TYPE_CD
AND CL.CLM_NUM_SK      =  CLEOPD.CLM_NUM_SK
AND CL.CLM_LINE_NUM    =  CLEOPD.CLM_LINE_NUM
AND CLEOPD.CLM_LINE_OTHR_PYR_SQNC_NUM = 1

LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_CLM_{ENVNAME}.CLM_LINE_ENCTR_OTHR_PYR_PMT CLEOPP
ON  CL.GEO_BENE_SK     =  CLEOPP.GEO_BENE_SK
AND CL.CLM_DT_SGNTR_SK =  CLEOPP.CLM_DT_SGNTR_SK
AND CL.CLM_TYPE_CD     =  CLEOPP.CLM_TYPE_CD
AND CL.CLM_NUM_SK      =  CLEOPP.CLM_NUM_SK
AND CL.CLM_LINE_NUM    =  CLEOPP.CLM_LINE_NUM
AND CLEOPP.CLM_LINE_OTHR_PYR_PMT_SQNC_NUM = 1


LEFT OUTER JOIN TMP_POA_DGNS_IND_HHA PDIIT
ON  C.GEO_BENE_SK      = PDIIT.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = PDIIT.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = PDIIT.CLM_TYPE_CD
AND C.CLM_NUM_SK       = PDIIT.CLM_NUM_SK

LEFT OUTER JOIN TMP_POA_DGNS_E_IND_HHA PDEIIT
ON  C.GEO_BENE_SK      = PDEIIT.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = PDEIIT.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = PDEIIT.CLM_TYPE_CD
AND C.CLM_NUM_SK       = PDEIIT.CLM_NUM_SK

LEFT OUTER JOIN TMP_DGNS_E_CD_HHA DECIT
ON  C.GEO_BENE_SK      = DECIT.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = DECIT.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = DECIT.CLM_TYPE_CD
AND C.CLM_NUM_SK       = DECIT.CLM_NUM_SK

LEFT OUTER JOIN TMP_OCRNC_SGNTR_MBR_HHA COSM
ON COSM.CLM_OCRNC_SGNTR_SK  = C.CLM_OCRNC_SGNTR_SK

LEFT OUTER JOIN TMP_RLT_OCRNC_SGNTR_MBR_HHA_TMP CROSM
ON CROSM.CLM_RLT_OCRNC_SGNTR_SK = C.CLM_RLT_OCRNC_SGNTR_SK

LEFT OUTER JOIN TMP_RLT_COND_SGNTR_MBR_HHA CRCSM
ON C.CLM_RLT_COND_SGNTR_SK  = CRCSM.CLM_RLT_COND_SGNTR_SK

LEFT OUTER JOIN TMP_PROD_HHA_VAL PHVT
ON  C.GEO_BENE_SK      = PHVT.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = PHVT.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = PHVT.CLM_TYPE_CD
AND C.CLM_NUM_SK       = PHVT.CLM_NUM_SK

LEFT OUTER JOIN TMP_HHA_ADR ADRTEMP
ON  C.GEO_BENE_SK      = ADRTEMP.GEO_BENE_SK
AND C.CLM_DT_SGNTR_SK  = ADRTEMP.CLM_DT_SGNTR_SK
AND C.CLM_TYPE_CD      = ADRTEMP.CLM_TYPE_CD
AND C.CLM_NUM_SK       = ADRTEMP.CLM_NUM_SK
		
		
LEFT OUTER JOIN IDRC_{ENVNAME}.CMS_FCT_BENE_MTRLZD_{ENVNAME}.BENE_FCT_TRANS BF
ON  BF.BENE_SK = C.BENE_SK
AND TO_DATE(BF.IDR_TRANS_OBSLT_TS) = '9999-12-31'
AND C.CLM_FROM_DT BETWEEN BENE_FCT_EFCTV_DT AND
    CASE WHEN BF.BENE_DEATH_DT IS NOT NULL
    THEN  ADD_MONTHS(( BENE_FCT_OBSLT_DT - EXTRACT(DAY FROM BENE_FCT_OBSLT_DT) + 1),1)-1
    ELSE BENE_FCT_OBSLT_DT END

		

WHERE C.CLM_TYPE_CD  IN (4032,4033)
--and C.CLM_FINL_ACTN_IND = 'Y'
and CE.CLM_EDPS_STUS_CD = 'A'
AND CLE.CLM_LINE_ENCTR_STUS_CD <> '84'
AND C.CLM_THRU_DT BETWEEN to_date('{EXT_FROM_DT}','YYYY-MM-DD') AND to_date('{EXT_TO_DT}','YYYY-MM-DD') 
 
ORDER BY 1,2,3,4,5

                        ) 
                        FILE_FORMAT = (TYPE=CSV field_delimiter=none ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY=none )
                        max_file_size=5368709120  """, con, exit_on_error=True)


   
   #**************************************
   # End Application
   #**************************************    
   snowconvert_helpers.quit_application()
   
except Exception as e:
   print(e)
   
   # Let shell script know that python code failed.
   bPythonExceptionOccurred=True   
   
finally:
   if con is not None:
      con.close()

   # Let shell script know that python code failed.      
   if bPythonExceptionOccurred == True:
      sys.exit(12) 
   else:   
      snowconvert_helpers.quit_application()
