#!/usr/bin/env python
########################################################################################################
# Name:  TRICARE_extract.py
#
# Desc: TRICARE Extract
#
# Created: Paul Baranoski 09/13/2023
# Modified:
#
# Paul Baranoski 2023-09-13 Created python code.
# 
########################################################################################################
import os
import sys
import datetime
from datetime import datetime
import sendEmail

currentDirectory = os.path.dirname(os.path.realpath(__file__))
rootDirectory = os.path.abspath(os.path.join(currentDirectory, ".."))
utilDirectory = os.getenv('CMN_UTIL')

sys.path.append(rootDirectory)
sys.path.append(utilDirectory)
script_name = os.path.basename(__file__)

import snowconvert_helpers
from snowconvert_helpers import Export

########################################################################################################
# VARIABLE ASSIGNMENT
########################################################################################################
con = None 
now = datetime.now()
date_time = now.strftime("%m/%d/%Y, %H:%M:%S")

# Use Timestamp generated by shell script so logs and output files will have timestamp
TMSTMP=os.getenv('TMSTMP')
ENVNAME=os.getenv('ENVNAME')
MNUP_YR=os.getenv('MNUP_YR')


# boolean - Python Exception status
bPythonExceptionOccurred=False

########################################################################################################
# RUN
########################################################################################################
print('')
print("Run date and time: " + date_time  )
print('')

########################################################################################################
# Method to execute the extract SQL using Timestamp 
########################################################################################################
try:
   snowconvert_helpers.configure_log()
   con = snowconvert_helpers.log_on()   
   snowconvert_helpers.execute_sql_statement(f"alter session set query_tag='{script_name}'",con,exit_on_error = True)
   snowconvert_helpers.execute_sql_statement("""USE WAREHOUSE ${sf_xtr_warehouse}""", con,exit_on_error = True)
   
   #**************************************
   #   Extract NYSPAP Bene Contract data  
   #**************************************   
   snowconvert_helpers.execute_sql_statement(f"""COPY INTO @BIA_{ENVNAME}.CMS_STAGE_XTR_{ENVNAME}.BIA_{ENVNAME}_XTR_TRICARE_STG/TRICARE_EXTRACT_{TMSTMP}.txt.gz
                                                FROM (


                WITH BENES AS (

                    SELECT 
                         TO_CHAR(BENE.BENE_SK,'FM000000000')               AS BENE_SK
                        ,RPAD(COALESCE(BENE.BENE_SSN_NUM,' '),9,' ')       AS BENE_SSN_NUM
                        ,RPAD(COALESCE(BENE.BENE_CAN_NUM,' ' ),9,' ')      AS BENE_CAN_NUM
                        ,RPAD(COALESCE(BENE.BENE_BIC_CD,' '),2,' ')        AS BENE_BIC_CD
                        ,RPAD(COALESCE(BENE.BENE_LAST_NAME,' '),40,' ')    AS BENE_LAST_NAME
                        ,RPAD(COALESCE(BENE.BENE_1ST_NAME,' '),30,' ')     AS BENE_1ST_NAME
                        ,RPAD(COALESCE(BENE.BENE_MIDL_NAME,' '),15,' ')    AS BENE_MIDL_NAME
                        
                        ,RPAD(COALESCE(TO_CHAR(BENE.BENE_BRTH_DT,'YYYYMMDD'),' '),8,' ') AS BENE_BRTH_DT
                        
                        ,COALESCE(BENE.BENE_SEX_CD,' ')   AS BENE_SEX_CD
                        ,RPAD(COALESCE(TO_CHAR(BENE.BENE_DEATH_DT,'YYYYMMDD'),' '),8,' ') AS BENE_DEATH_DT	
                  
                        ,CASE WHEN BENE_PTB_NENTLMT_RSN_CD = '~'          
                              THEN ' '                                    
                              ELSE COALESCE(BENE_PTB_NENTLMT_RSN_CD,' ')                
                         END    AS BENE_PTB_NENTLMT_RSN_CD  
                  
                        ,RPAD(COALESCE(BENE.BENE_MBI_ID,' '),11,' ') AS BENE_MBI_ID
                    
                    FROM IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE BENE

                    INNER JOIN BIA_{ENVNAME}.CMS_TARGET_XTR_{ENVNAME}.TRICARE_FINDER_FILE FINDER
                    ON FINDER.SSN_NUM = BENE.BENE_SSN_NUM

                    WHERE TO_CHAR(BENE.IDR_TRANS_OBSLT_TS,'YYYY-MM-DD') = '9999-12-31'
                      AND IDR_LTST_TRANS_FLG = 'Y'
                    
                )

                ,PART_A_BENE_MDCR_ENTLMT AS (

                    SELECT *
                    FROM (
                        SELECT BENE.BENE_SK 
                            ,RPAD(COALESCE(TO_CHAR(A.BENE_RNG_BGN_DT,'YYYYMMDD'),' '),8,' ') AS PTA_ENTLMT_STRT_DT
                            
                            ,RPAD(CASE WHEN TO_CHAR(A.BENE_RNG_END_DT,'YYYY-MM-DD') = '9999-12-31'
                                       THEN ' '
                                       ELSE TO_CHAR(A.BENE_RNG_END_DT,'YYYYMMDD')
                                  END,8,' ')     AS PTA_ENTLMT_END_DT

                            ,A.BENE_MDCR_ENTLMT_STUS_CD as PTA_ENTLMT_STUS_CD
                            ,Rank() OVER (Partition by A.BENE_SK, A.BENE_MDCR_ENTLMT_TYPE_CD ORDER BY A.BENE_RNG_BGN_DT DESC, A.BENE_RNG_END_DT DESC  ) as MOST_RECENT_PTA_ENTLMT

                        FROM BENES BENE

                        -- ENTITLEMENT PART A
                        INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE_MDCR_ENTLMT A
                        ON  BENE.BENE_SK               = A.BENE_SK
                        AND A.BENE_MDCR_ENTLMT_TYPE_CD = 'A'
                        AND A.IDR_LTST_TRANS_FLG       = 'Y'
                        AND TO_CHAR(A.IDR_TRANS_OBSLT_TS,'YYYY-MM-DD') = '9999-12-31'
                    
                    )
                    
                    WHERE MOST_RECENT_PTA_ENTLMT = 1

                )


                ,PART_B_BENE_MDCR_ENTLMT AS (

                    SELECT *
                    FROM (
                    
                        SELECT BENE.BENE_SK 
                            ,RPAD(COALESCE(TO_CHAR(B.BENE_RNG_BGN_DT,'YYYYMMDD'),' '),8,' ') AS PTB_ENTLMT_STRT_DT
                            
                            ,RPAD(CASE WHEN TO_CHAR(B.BENE_RNG_END_DT,'YYYY-MM-DD') = '9999-12-31'
                                       THEN ' '
                                       ELSE TO_CHAR(B.BENE_RNG_END_DT,'YYYYMMDD')
                                  END,8,' ')     AS PTB_ENTLMT_END_DT

                            ,B.BENE_MDCR_ENTLMT_STUS_CD as PTB_ENTLMT_STUS_CD

                      
                            ,Rank() OVER (Partition by B.BENE_SK, B.BENE_MDCR_ENTLMT_TYPE_CD ORDER BY B.BENE_RNG_BGN_DT DESC, B.BENE_RNG_END_DT DESC  ) as MOST_RECENT_PTB_ENTLMT

                        FROM BENES BENE

                        --!!!! NOTE: There are some Bene who do not have a PART B record
                        -- ENTITLEMENT PART B
                        INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE_MDCR_ENTLMT B
                        ON  BENE.BENE_SK               = B.BENE_SK
                        AND B.BENE_MDCR_ENTLMT_TYPE_CD = 'B'
                        AND B.IDR_LTST_TRANS_FLG       = 'Y'
                        AND TO_CHAR(B.IDR_TRANS_OBSLT_TS,'YYYY-MM-DD') = '9999-12-31'

                    )
                    
                    WHERE MOST_RECENT_PTB_ENTLMT = 1

                )

                ,MAPD_ENRLMT AS (

                    SELECT *
                    FROM (
                    
                        SELECT BENE.BENE_SK
                            ,RPAD(COALESCE(D.BENE_CNTRCT_NUM,' '),5,' ')  AS BENE_CNTRCT_NUM
                                  
                            ,COALESCE(LPAD(RTRIM(D.BENE_CVRG_TYPE_CD),2,'0'),'  ') AS CVRG_TYPE_CD


                            ,RPAD(COALESCE(TO_CHAR(D.BENE_ENRLMT_CNTRCT_EFCTV_DT,'YYYYMMDD'),' '),8,' ') AS BENE_ENRLMT_CNTRCT_EFCTV_DT
                             --,D.BENE_ENRLMT_END_DT  (CME file has this field occur twice

                            ,REPLACE(RPAD(COALESCE(D.BENE_PBP_NUM,' '),3,' '),'~',' ') AS  BENE_PBP_NUM
                            
                            ,RPAD(COALESCE(TO_CHAR(D.BENE_ENRLMT_BGN_DT,'YYYYMMDD'),' '),8,' ') AS BENE_ENRLMT_BGN_DT

                            ,RPAD(CASE WHEN TO_CHAR(D.BENE_ENRLMT_END_DT,'YYYY-MM-DD') = '9999-12-31'
                                       THEN ' '
                                       ELSE TO_CHAR(D.BENE_ENRLMT_END_DT,'YYYYMMDD')
                                  END,8,' ')     AS BENE_ENRLMT_END_DT

                            ,Rank() OVER (Partition by D.BENE_SK ORDER BY D.BENE_ENRLMT_BGN_DT DESC, D.BENE_ENRLMT_END_DT DESC, D.BENE_CNTRCT_NUM, D.BENE_PBP_NUM ) as MOST_RECENT_MA_CNTRCT_ENRLMT

                                  
                        FROM BENES BENE
                        
                        INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE_MAPD_ENRLMT D
                        ON  BENE.BENE_SK = D.BENE_SK
                        AND D.IDR_LTST_TRANS_FLG = 'Y'
                        AND TO_CHAR(D.IDR_TRANS_OBSLT_TS,'YYYY-MM-DD') ='9999-12-31'
                        
                        -- This will ensure that we are getting the most recent Contract that is currently active
                        WHERE D.BENE_ENRLMT_BGN_DT IS NOT NULL
                          AND D.BENE_ENRLMT_BGN_DT <= CURRENT_DATE

                    )
                    
                    WHERE MOST_RECENT_MA_CNTRCT_ENRLMT = 1

                )

                ,ENTLMT_RSN AS (

                    SELECT *
                    FROM (
                            SELECT BENE.BENE_SK
                                ,RSN.BENE_MDCR_ENTLMT_RSN_CD
                                ,RPAD(COALESCE(TO_CHAR(RSN.BENE_RNG_BGN_DT,'YYYYMMDD'),' '),8,' ') AS RSN_LAST_CHG_DT
                                
                                ,Rank() OVER (Partition by RSN.BENE_SK ORDER BY RSN.BENE_RNG_BGN_DT DESC ) as MOST_RECENT_ENTLMT_RSN

                            FROM BENES BENE
                            
                            -- REASON CODE INFO
                            INNER JOIN IDRC_{ENVNAME}.CMS_DIM_BENE_{ENVNAME}.BENE_MDCR_ENTLMT_RSN RSN
                            ON  BENE.BENE_SK               = RSN.BENE_SK
                            AND RSN.IDR_LTST_TRANS_FLG       = 'Y'
                            AND TO_CHAR(RSN.IDR_TRANS_OBSLT_TS,'YYYY-MM-DD') = '9999-12-31'
                    )
                    
                    WHERE MOST_RECENT_ENTLMT_RSN = 1
                    
                ) 



                SELECT 
                     BENE.BENE_SSN_NUM
                    ,BENE.BENE_CAN_NUM
                    ,BENE.BENE_BIC_CD
                    ,BENE.BENE_LAST_NAME
                    ,BENE.BENE_1ST_NAME
                    ,BENE.BENE_MIDL_NAME
                    ,BENE.BENE_BRTH_DT
                    ,BENE.BENE_SEX_CD
                    ,BENE.BENE_DEATH_DT


                    ,CASE WHEN BENE_PTB_NENTLMT_RSN_CD = '~'          
                          THEN ' '                                    
                          ELSE COALESCE(BENE_PTB_NENTLMT_RSN_CD,' ')                
                     END    AS BENE_PTB_NENTLMT_RSN_CD  

                    ,RPAD(COALESCE(PTA_ENTLMT_STRT_DT,' '),8,' ') AS PTA_ENTLMT_STRT_DT 
                    ,RPAD(COALESCE(PTA_ENTLMT_END_DT,' '),8,' ')  AS PTA_ENTLMT_END_DT

                    ,COALESCE(A.PTA_ENTLMT_STUS_CD,' ')           AS PTA_ENTLMT_STUS_CD   

                    ,RPAD(COALESCE(PTB_ENTLMT_STRT_DT,' '),8,' ') AS PTB_ENTLMT_STRT_DT 
                    ,RPAD(COALESCE(PTB_ENTLMT_END_DT,' '),8,' ')  AS PTB_ENTLMT_END_DT

                    ,COALESCE(B.PTB_ENTLMT_STUS_CD,' ')           AS PTB_ENTLMT_STUS_CD
                   
                    ,RPAD(COALESCE(RSN.RSN_LAST_CHG_DT,' '),8,' ') AS RSN_LAST_CHG_DT

                    ,COALESCE(RSN.BENE_MDCR_ENTLMT_RSN_CD,' ')     AS BENE_MDCR_ENTLMT_RSN_CD 
                   
                    ,RPAD(COALESCE(D.BENE_CNTRCT_NUM,' '),5,' ')  AS BENE_CNTRCT_NUM
                          
                    ,RPAD(COALESCE(D.CVRG_TYPE_CD,' '),2,' ')    AS CVRG_TYPE_CD


                    ,RPAD(COALESCE(BENE_ENRLMT_CNTRCT_EFCTV_DT,' '),8,' ')  AS  BENE_ENRLMT_CNTRCT_EFCTV_DT 
                    
                    ,RPAD(COALESCE(BENE_ENRLMT_END_DT,' '),8,' ') AS BENE_ENRLMT_END_DT

                    ,RPAD(COALESCE(D.BENE_PBP_NUM,' '),3,' ')     AS  BENE_PBP_NUM
                    
                    ,RPAD(COALESCE(BENE_ENRLMT_BGN_DT,' '),8,' ') AS BENE_ENRLMT_BGN_DT

                    ,RPAD(COALESCE(BENE_ENRLMT_END_DT,' '),8,' ') AS BENE_ENRLMT_END_DT
                          
                    ,BENE.BENE_MBI_ID
                    
                    ,REPEAT(' ',11)  AS BLANKS_NEEDED_FOR_EFT_LRECL


                    FROM BENES BENE

                    -- ENTITLEMENT PART A
                    LEFT OUTER JOIN PART_A_BENE_MDCR_ENTLMT A
                    ON  BENE.BENE_SK  =  A.BENE_SK

                    -- ENTITLEMENT PART B
                    LEFT OUTER JOIN PART_B_BENE_MDCR_ENTLMT B
                    ON  BENE.BENE_SK  =  B.BENE_SK

                    LEFT OUTER JOIN MAPD_ENRLMT D
                    ON  BENE.BENE_SK  =  D.BENE_SK
                    
                    -- REASON CODE INFO
                    LEFT OUTER JOIN ENTLMT_RSN RSN
                    ON  BENE.BENE_SK  =  RSN.BENE_SK

                    --WHERE  D.CVRG_TYPE_CD <> '~'
                    --AND (A.BENE_SK IS NOT NULL OR B.BENE_SK IS NOT NULL OR D.BENE_SK IS NOT NULL OR RSN.BENE_SK IS NOT NULL)
                      

                --ORDER BY BENE_SK
                --	,BENE_SSN_NUM
                --,BENE_CNTRCT_NUM
                --,BENE_PBP_NUM
                --,BENE_ENRLMT_BGN_DT
                --,BENE_ENRLMT_END_DT
                ORDER BY 
                 BENE_SSN_NUM
                ,BENE_CAN_NUM
                ,BENE_BIC_CD
                ,BENE_ENRLMT_BGN_DT
                ,BENE_ENRLMT_CNTRCT_EFCTV_DT
                ,PTB_ENTLMT_STRT_DT
                ,PTA_ENTLMT_STRT_DT
                ,RSN_LAST_CHG_DT

 
 )
                        FILE_FORMAT = (TYPE = CSV field_delimiter = none  ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY = none )
                        SINGLE = TRUE  max_file_size=5368709120  """, con, exit_on_error=True)


   
   #**************************************
   # End Application
   #**************************************    
   snowconvert_helpers.quit_application()
   
except Exception as e:
   print(e)
   
   # Let shell script know that python code failed.
   bPythonExceptionOccurred=True   
   
finally:
   if con is not None:
      con.close()

   # Let shell script know that python code failed.      
   if bPythonExceptionOccurred == True:
      sys.exit(12) 
   else:   
      snowconvert_helpers.quit_application()

